### ISSUE TITLE
java.lang.RuntimeException Error during eglCreateContext

### ISSUE THREAD

**Issue by yefengjie** [natario1/CameraView#1002]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.6.4
- Camera engine used: camera2
- Reproducible in official demo app: no
- Device / Android version: 三星 SM G9650 Android 10,level 29  
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### Error Stack
`VideoEncoder(2692)
java.lang.RuntimeException
Error during eglCreateContext (2): EGL error 0x3006

1 com.otaliastudios.opengl.core.Egloo.checkEglError(Egloo.kt:60)
2 com.otaliastudios.opengl.core.EglNativeCore.<init>(EglNativeCore.kt:78)
3 com.otaliastudios.opengl.core.EglCore.<init>(EglCore.kt:17)
4 com.otaliastudios.cameraview.video.encoding.TextureMediaEncoder.onPrepare(TextureMediaEncoder.java:99)
5 com.otaliastudios.cameraview.video.encoding.MediaEncoder$1.run(MediaEncoder.java:191)
6 android.os.Handler.handleCallback(Handler.java:883)
7 android.os.Handler.dispatchMessage(Handler.java:100)
8 android.os.Looper.loop(Looper.java:237)
9 android.os.HandlerThread.run(HandlerThread.java:67)
`

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
    android:id="@+id/camera"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    android:visibility="visible"
    app:cameraAudio="on"
    app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker"
    app:cameraEngine="camera2"
    app:cameraExperimental="true"
    app:cameraFacing="back"
    app:cameraFlash="off"
    app:cameraGestureLongTap="none"
    app:cameraGesturePinch="zoom"
    app:cameraGestureScrollHorizontal="filterControl1"
    app:cameraGestureScrollVertical="exposureCorrection"
    app:cameraGestureTap="autoFocus"
    app:cameraGrid="off"
    app:cameraMode="video"
    app:cameraPictureSizeAspectRatio="1:1"
    app:cameraPictureSizeMaxHeight="1280"
    app:cameraPictureSizeMaxWidth="720"
    app:cameraPictureSizeMinHeight="1280"
    app:cameraPictureSizeMinWidth="720"
    app:cameraPictureSizeSmallest="true"
    app:cameraPlaySounds="true"
    app:cameraPreview="glSurface"
    app:cameraSnapshotMaxHeight="1280"
    app:cameraSnapshotMaxWidth="720"
    app:cameraVideoSizeAspectRatio="1:1"
    app:cameraVideoSizeMaxHeight="1280"
    app:cameraVideoSizeMaxWidth="720"
    app:cameraVideoSizeMinHeight="1280"
    app:cameraVideoSizeMinWidth="720"
    app:cameraVideoSizeSmallest="true"
    app:cameraPreviewFrameRate="35"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent”/>

```

**Comment by rohilla17** [comment]
I am facing the same issue.
Please help me solve.

**Comment by manofgpa** [comment]
Got the same issue. Did you guys manage to fix this?
