### ISSUE TITLE
Manipulation CaptureRequest's settings

### ISSUE THREAD

**Issue by afurtak** [natario1/CameraView#1028]
Hi, I would like to ask, if CameraView gives us possibility to manipulate CaptureRequest's settings like for instance   https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#CONTROL_EFFECT_MODE 

I am using the newest version: 2.6.4

**Comment by natario1** [comment]
Not easily, but you can subclass CameraView, override instantiateCameraEngine, subclass Camera2Engine and override protected methods there

**Comment by afurtak** [comment]
Great, thank you!
