### ISSUE TITLE
How to save the photo in bitmap always with the same rotation as the user see it on the device?

### ISSUE THREAD

**Issue by nestoleh** [natario1/CameraView#1037]
### How do I?
I can't understand how CameraView orient bitmap with a photo.

#### Example.
I need to take the HORIZONTAL photo and cut a rectangle with a specific ratio from it. Sample below

![image](https://user-images.githubusercontent.com/10635470/105467507-786e1300-5c9e-11eb-9185-dcd0695827a5.png)

To do it I set activity landscape mode `requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE` and disable orientation for CameraView `app:cameraUseDeviceOrientation="false"`

To get bitmap I use the next code:

```
  cameraView.addCameraListener(object : CameraListener() {
            override fun onPictureTaken(result: PictureResult) {
                cameraView.close()
                result.toBitmap { bitmap ->
                    if (bitmap == null) {
                        showPhotoSavingError()
                        cameraView.open()
                    } else {
                       // handle bitmap
                    }
                }
            }
        })
```

In most cases, the result bitmap is horizontal and looks exactly like on screen, but sometimes (is ~5% cases) it vertical, and my cut fragment is wrong (sample below)

![image](https://user-images.githubusercontent.com/10635470/105469039-5aa1ad80-5ca0-11eb-8b02-d02674b86aa9.png)

The same happens if I need a vertical photo, in most cases all ok, but sometimes on some devices in SCREEN_ORIENTATION_PORTRAIT and with the disabled app:cameraUseDeviceOrientation saves the photo to bitmap as horizontal image rotated to -90 deg.

Of course, I can check the bitmap ratio and rotate it to the proper orientation, but I don't know if I need to rotate it clockwise or counterclockwise. How to save the photo in bitmap always in the same rotation as the user see it on the device?

### Version used
2.6.4
 
P/S/ Sorry for my bad English, I hope I explained the problem

**Comment by jemshit** [comment]
Any answer? 
I get similar behavior on video taking with same config above. Mostly output is landscape, sometimes it is still portrait. 
What is desired is force the output to be landscape no matter how device is held. 
@nestoleh @natario1

**Comment by nestoleh** [comment]
@jemshit I don't have a 100% correct solution, so currently I just rotate the picture to landscape (if height > width) before processing. Of course, there are can be some troubles because I don't know the correct angle for rotating (90 deg or -90 deg) so the result will be rotated to 180deg on some devices
