### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by VGJohn** [natario1/CameraView#1043]
[Starting from May 1, 2021 JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Describe the solution you'd like
CameraView artifacts should be available outside of JCenter, preferably in Maven Central.

Describe alternatives you've considered
[JitPack](https://jitpack.io/)
[GitHub Packages](https://docs.github.com/en/packages)

**Comment by peterfortuin** [comment]
Is this going to happen?

**Comment by reactivedroid** [comment]
@natario1 Since the day for shut down is coming near, is there an action plan for the migration? Happy to discuss

**Comment by natario1** [comment]
JCenter will keep serving artifacts until February 2022, so we have 11 months. As soon as we have a new version rolling out and JCenter does not accept packages anymore, we'll move to maven central.

**Comment by troy-lamerton** [comment]
@natario1 is there a rough ETA on the next release?

It's currently not possible to use jitpack.io for example, because of this error:

```
Execution failed for task ':golive:mergeReleaseResources'.
> Could not resolve all files for configuration ':golive:releaseRuntimeClasspath'.
   > Could not find com.otaliastudios.opengl:egloo:0.5.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/otaliastudios/opengl/egloo/0.5.3/egloo-0.5.3.pom
       - https://repo.maven.apache.org/maven2/com/otaliastudios/opengl/egloo/0.5.3/egloo-0.5.3.pom
       - http://jitpack.io/com/otaliastudios/opengl/egloo/0.5.3/egloo-0.5.3.pom
     Required by:
         project :golive > com.github.natario1:cameraview:v2.7.0
```

**Comment by ergunkocak** [comment]
required library (egloo) moved to maven with version 0.6.0 :

https://github.com/natario1/Egloo/issues?q=maven

**Comment by troy-lamerton** [comment]
resolved in https://github.com/natario1/CameraView/releases/tag/v2.7.1

this can be closed?

**Comment by natario1** [comment]
Yes!

**Comment by VGJohn** [comment]
Thanks so much for getting this sorted 🥳

**Comment by amar-w** [comment]
So from 2.7.1 it will be served via Maven Central? 

What about older versions if a developer, by any chance, is still using them?

**Comment by natario1** [comment]
You can keep using jcenter for older versions until May 2022, if I remember correctly. After this, you will need to update.
