### ISSUE TITLE
The phone becomes stuck after denying permission

### ISSUE THREAD

**Issue by LG12300** [natario1/CameraView#1045]
When I set'cameraRequestPermissions' to true, and denied the permission, the phone becomes very stuck.
![](https://user-images.githubusercontent.com/49315781/107106163-367bca00-6865-11eb-8e3c-d5a07db519b6.jpg)
### Device
Redmi k20 api29
### Version used
2.7.0
### xml
```
    <com.otaliastudios.cameraview.CameraView
        android:id="@+id/cameraView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toTopOf="@id/v_bottom"
        app:layout_constraintEnd_toEndOf="parent"
        app:cameraPlaySounds="false"
        app:cameraAudio="off"
        app:cameraMode="picture"
        app:cameraRequestPermissions="true"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Comment by LG12300** [comment]
I have checked the problem, although this is not a bug, it is not a good idea to request permission in the 'onResume' function,because every time you request permission,'onPause' and'onResume' will be called, which will be an endless loop

**Comment by xxxifan** [comment]
same issue.
