### ISSUE TITLE
NPE at CameraUtils.java line 93 

### ISSUE THREAD

**Issue by muammil** [natario1/CameraView#1061]
### Describe the bug
In my production app, I am getting this bug very often now(crashlytics), I have been using this library for almost 2 years this issue was not there before, this one popped up very recently, in just about one month. Please look in to it

Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.7.0*
- Camera engine used: *both*
- Reproducible in official demo app: *not sure*
- Device / Android version: *Had this issue on xiaomi, oppo, samsung, vivo and other, android versions from 9 to 11*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

### Expected behavior
On shutter button tap, save the image to local storage with the help of camera listener onPictureTaken method

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
    <com.otaliastudios.cameraview.CameraView
      android:id="@+id/camera"
      android:keepScreenOn="true"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_gravity="center"
      app:cameraFacing="back"
      app:cameraFlash="auto"
      app:cameraPictureFormat="jpeg"
      app:cameraAudio="off"
      app:cameraMode="picture"
      app:cameraUseDeviceOrientation="false"
      app:cameraPictureSizeMinWidth="640"
      app:cameraPictureSizeMinHeight="480"
      app:cameraPictureSizeMaxWidth="960"
      app:cameraPictureSizeMaxHeight="720" />
```

### Logs

> Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
>        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
>        at com.otaliastudios.cameraview.CameraUtils.writeToFile(CameraUtils.java:93)
>        at com.otaliastudios.cameraview.CameraUtils$1.run(CameraUtils.java:121)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:237)
>        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by muammil** [comment]
I am still getting this issue in my production app, dev team please look in to it

**Comment by MrChriZ** [comment]
Seeing the same here

**Comment by javaherisaber** [comment]
@muammil @MrChriZ 
Has anyone managed to fix this issue?
I have the bug in production app

**Comment by javaherisaber** [comment]
@natario1 
This issue is serious and causing crash on many devices
can you take a look and fix it?
