### ISSUE TITLE
Does our CameraView library supports External (USB) camera connectivity? 

### ISSUE THREAD

**Issue by SreeniMannem** [natario1/CameraView#1062]
Hi @natario1, Does our CameraView library will support connectivity and streaming using External cameras like USB/UVC? **If Yes**, Please help me on how to integrate USB camera functionality using our CameraView library. **If No**, are there any plans in future for external camera integration using our CameraView library? 

Thanks in advance.

**Comment by Qdafengzi** [comment]
I also want to know ,becase I have a requirement to connect an external camera via USB
