### ISSUE TITLE
Corrupted Video From Samsung J7 Neo

### ISSUE THREAD

**Issue by sachin-sivadasan** [natario1/CameraView#1064]
### Describe the bug
Video output is corrupted on samsung J7 Neo (SM-J701F)
- CameraView version: *2.7.0*
- Camera engine used: *both*
- Reproducible in official demo app: *yes*
- Device / Android version: *samsung J7 Neo (SM-J701F), API 28*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

### To Reproduce
1. Install demo app and go to main screen.
2. Click on record 5sec video.
3. See the video is not playing well and duration of the video is more than 5 sec (around 50min). And video is stuck from beginning and audio plays in background for sometime.
4. For example 1 minute video showing 55 hour duration.

### Expected behavior
Video should play with duration of 5sec

### XML layout
Part of the XML layout from demo app (unchanged).
```xml
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginBottom="88dp"
        android:keepScreenOn="true"
        app:cameraExperimental="true"
        app:cameraEngine="camera2"
        app:cameraPreview="glSurface"
        app:cameraPlaySounds="true"
        app:cameraGrid="off"
        app:cameraFlash="auto"
        app:cameraAudio="on"
        app:cameraFacing="back"
        app:cameraGestureTap="autoFocus"
        app:cameraGestureLongTap="none"
        app:cameraGesturePinch="zoom"
        app:cameraGestureScrollHorizontal="filterControl1"
        app:cameraGestureScrollVertical="exposureCorrection"
        app:cameraMode="picture"
        app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker">
    </com.otaliastudios.cameraview.CameraView>

```

### APK
Reproducible on demo app

**Comment by sachin-sivadasan** [comment]
@natario1

**Comment by HBiSoft** [comment]
I can't reproduce this on my Samsung J7 Neo
