### ISSUE TITLE
Add an option to enable hardware overlay capture

### ISSUE THREAD

**Issue by ObsidianX** [natario1/CameraView#1065]
### Problem to be addressed
Hardware accelerated views like video playback are not currently captured by snapshots.

### Describe the solution you'd like
I read a conversation in this repo that suggested using `lockHardwareCanvas` instead of `lockCanvas` in  `OverlayDrawer` which fixed video capture in my tests.  I propose exposing this as an attribute/API so users don't need to fork/compile the library to enable hardware capture.

**Comment by natario1** [comment]
Thanks for PR!
