### ISSUE TITLE
Any way to disable auto focus?

### ISSUE THREAD

**Issue by vedmedenko** [natario1/CameraView#107]
Hi! 

Is it possible to disable camera auto focus feature with your library?

Thank you in advance!

**Comment by natario1** [comment]
No. May I ask why you want to disable it?

**Comment by vedmedenko** [comment]
I want to calibrate android camera using OpenCV methods for later use. That process, as far as i know, requires the camera focus to be locked. Your great library seems to be the best choice since i want to focus on other stuff instead of dealing with the camera, however i am missing this feature.

**Comment by natario1** [comment]
Calibrate what? (Just curious).

This feature was present but I have removed it months ago. I had (have) the feeling that 99.99% of users would just need the best focus option.

Also focus modes are complicated to wrap in a useful API. Maybe Focus.BEST and Focus.OFF. if anyone wants to work on it we can discuss.

**Comment by Flashspeed** [comment]
> No. May I ask why you want to disable it?

Would be nice to disable it so it can be locked to Infinite focus mode

**Comment by edward1988** [comment]
+1 May I ask, do you plan to add this functionality(disable auto focus)?

**Comment by Geraldo-Neto** [comment]
Would really be great to have more focus modes. But the best we can do for now is to set autofocus reset delay to 0 then focus on a given point. Like this:
`camera.setAutoFocusResetDelay(0); camera.startAutoFocus(camera.getWidth()/2,camera.getHeight()/2);`

**Comment by natario1** [comment]
Not planning to do this. But you can change focus in `Camera2` by simply subclassing the engine:

- Subclass `CameraView`, e.g. `MyCameraView`
- Subclass `Camera2Engine`, e.g. `MyCamera2Engine`
- Override `MyCameraView.instantiateCameraEngine()`, and return an instance of `My2CameraEngine`
- In `My2CameraEngine`, override protected methods like `applyDefaultFocus()` to do whatever you want

**Comment by wosiu** [comment]
Thank you for instructions :) Should be fine with it.
