### ISSUE TITLE
Using more than 2 filters in MultiFilter saves a black snapshot

### ISSUE THREAD

**Issue by juancarlosmendez** [natario1/CameraView#1074]
When using more than 2 filters in a MultiFIter it saves a black picture.  I'm using takePictureSnapshot.

**Comment by X-FAN** [comment]
Same issue. This can be fixed?

**Comment by EthanCo** [comment]
I've solved it.
[Android 解决CameraView叠加2个以上滤镜拍照黑屏的BUG (一) : 复现BUG](https://blog.csdn.net/EthanCo/article/details/134303809)  
[Android 解决CameraView叠加2个以上滤镜拍照黑屏的BUG(二) : 解决BUG](https://blog.csdn.net/EthanCo/article/details/134310244)
