### ISSUE TITLE
Rotated preview on front camera

### ISSUE THREAD

**Issue by Monster-king** [natario1/CameraView#108]
Preview rotated to 180 degrees on front camera (only preview)

- [x] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Take Samsung Galaxy Tab S (android 6.0.1)
2. Open CameraView demo app
3. Change camera to front

#### Expected behavior:
Normal preview
#### Actual behavior:
Rotated preview to 180 degrees
#### Screenshots:
![screenshot_2017-11-20-16-42-24](https://user-images.githubusercontent.com/18480424/33016851-dca2f6ac-ce11-11e7-9ca0-b258d9df3438.png)

**Comment by natario1** [comment]
Thanks. I don't have the device so we need more info.

1. Can you post logs coming from the demo app?

2. Can you try with another library, like this https://github.com/afollestad/material-camera ? What happens? Just to understand if it's a device specific issue.

**Comment by Monster-king** [comment]
1. there logs:
[logs.txt](https://github.com/natario1/CameraView/files/1490248/logs.txt)
2. I try https://github.com/afollestad/material-camera, but it don't work on my device. Instead it I tried https://github.com/google/cameraview and there error not observed

**Comment by natario1** [comment]
I think I have fixed this in #112 .

You can give it a try before we merge if you want. It's just one line to change by hand.

**Comment by Monster-king** [comment]
Working fine
