### ISSUE TITLE
Gradle 7.0+ support

### ISSUE THREAD

**Issue by gorynalexander** [natario1/CameraView#1082]
`Gradle 7.0 will also deprecate the use of jcenter() to resolve dependencies. You will still be able to use JCenter as a repository, but Gradle will emit a deprecation warning. The jcenter() method will be removed in the next major release.`

Please add gradle 7.0 support, you need to add your lib to the Maven Central.

**Comment by Damercy** [comment]
__+1__ to this. Please migrate from `jCenter()` as soon as possible. Thanks!

**Comment by ergunkocak** [comment]
required library moved to maven with version 0.6.0 :

https://github.com/natario1/Egloo/issues?q=maven
