### ISSUE TITLE
How to turn off  RECORD_AUDIO permission?

### ISSUE THREAD

**Issue by ducthang123** [natario1/CameraView#1090]
Your library requires RECORD_AUDIO permission but I use the library for taking photos not record videos. How do I turn off requires RECORD_AUDIO permission?

### Version used 
CameraView exact version 2.7.0.

**Comment by natario1** [comment]
You can disable the audio with the app:cameraAudio setting.

**Comment by ducthang123** [comment]
thank you so much it work for me.
