### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'

### ISSUE THREAD

**Issue by Jayce-2177** [natario1/CameraView#1097]
### Describe the bug
So I updated my android studio today and I am getting the lint warning "jcenter is at end of life", when I try to remove JCenter() as suggested by android studio I now get the following build failed message.

Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.otaliastudios:cameraview:2.7.0.
     Required by:
         project :app

Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.7.0
- Camera engine used: both
- Reproducible in official demo app: yes
- Device / Android version: N/A
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Use android studio latest version
2. Remove Jcenter from gradle
3. See error

### Expected behavior
Build to compile, I knew this was coming for awhile, but I have been waiting to see if this repo would be updated to accommodate this change.

**Comment by joehy** [comment]
same problem

**Comment by carlossilvaf** [comment]
same problem

**Comment by HBiSoft** [comment]
@Jayce-2177 @joehy @carlossilvaf Did you resolve this issue? I'm currently facing the same issue.

**Comment by HBiSoft** [comment]
Never mind, I fixed it by upgrading my Gradle build version using Upgrade Assistant. I also upgraded `api 'com.otaliastudios:cameraview:2.7.0'` to `api 'com.otaliastudios:cameraview:2.7.2'`
