### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by osama-raddad** [natario1/CameraView#110]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

I am trying to update the library to v1.4.0 from v1.2.1

#### Expected behavior:

update and build with no exceptions 

#### Actual behavior:

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:support-v13:26.0.2] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:exifinterface:26.1.0] AndroidManifest.xml:25:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
Thanks! This is not our problem. You have conflicts with other dependencies. Take a look on StackOverflow to see what's happening.
