### ISSUE TITLE
Last version support API 16 ?

### ISSUE THREAD

**Issue by TechComet** [natario1/CameraView#1119]
### Hi,

this version now min support to API 19?

what last version support API 16 ?

**Comment by EzequielAdrianM** [comment]
Please [read the docs](https://natario1.github.io/CameraView/about/install) before asking this kind of questions. According to the current documentation: 

> "The library works on API 15+, which is the only requirement and should be met by most projects nowadays."

**Comment by TechComet** [comment]
I read in commit for .gitignore `Revert min support to API 19`

thanks
