### ISSUE TITLE
 picture is rotated

### ISSUE THREAD

**Issue by changyoutianxia** [natario1/CameraView#1124]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.7.1
- Camera engine used: both
- Reproducible in official demo app: yes
- Device / Android version: realme gtNeo or xiaomi6X, API 30
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1、setting
![AF3D23A6D0F3CC9E5ABCE350E26911D7](https://user-images.githubusercontent.com/46896358/130888797-9c7bf80a-5a4d-4785-bdca-3440e02b38fc.jpg)
![12A5D99477A44712EFFCECCD453D9ACB](https://user-images.githubusercontent.com/46896358/130888808-c4479def-f749-48a6-93b6-c31bce353c64.jpg)
![9BDAC3DF3595A9D7F500600FF61FA717](https://user-images.githubusercontent.com/46896358/130888818-9d25c88f-28d5-4249-9029-9a8fc4d81c3d.jpg)
![E96EB71EE666192FD070ED30B400F9ED](https://user-images.githubusercontent.com/46896358/130888828-dce7a5da-0a2e-4731-a1ec-85d8b3b3ee43.jpg)
![83729717A005EFA0E36518A046332917](https://user-images.githubusercontent.com/46896358/130888840-9d157222-df8d-487b-9de4-aea3719c87bd.jpg)

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
use demo
```

### description
When the camera rotates at a certain angle, the picture taken will rotate. The picture that should not rotate, but it rotates, and the rotation angle is always zero.

**Comment by yunisrasulzade** [comment]
Any solution?
