### ISSUE TITLE
preview and take picture is green screen in HUAWEI Harmony OS

### ISSUE THREAD

**Issue by gfzy9876** [natario1/CameraView#1141]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.7.1
- Camera engine used: both
- Reproducible in official demo app: yes
- Device / Android version: HUAWEI(Harmony OS) - ELS-AN00(P40 Pro 5G), Api 29
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): 

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
```
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="103dp"
        android:layout_marginBottom="133dp"
        android:keepScreenOn="true"
        app:cameraExperimental="true"
        app:cameraEngine="camera2"
        app:cameraPreview="glSurface"
        app:cameraAudio="off"
        app:cameraFacing="front"
        app:cameraGestureTap="autoFocus" />
```

both using `app:cameraExperimental="true"`, `app:cameraEngine="camera2"`, `app:cameraPreview="glSurface"`

preview and take picture is this thing and with no error callback:

![111](https://user-images.githubusercontent.com/34124544/139622131-3acafce7-c044-4663-ae20-f7d26598f93b.jpg)

it just happen in Harmony OS

**Comment by gfzy9876** [comment]
@natario1

**Comment by kaitian521** [comment]
//        if (Build.VERSION.SDK_INT >= 21) {
//            sizeToProfileMap.put(new Size(3840, 2160),
//                    CamcorderProfile.QUALITY_2160P);
//        }

**Comment by leocreater** [comment]
怎么处理的？我这也遇到了

**Comment by gfzy9876** [comment]
@leocreater 
我把cameraEngine用camera1没问题了

```
<com.otaliastudios.cameraview.CameraView
            android:id="@+id/camera"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="103dp"
            android:layout_marginBottom="133dp"
            android:keepScreenOn="true"
            app:cameraEngine="camera1"
            app:cameraAudio="off"
            app:cameraFacing="front"
            app:cameraGestureTap="autoFocus" />
```

**Comment by Qdafengzi** [comment]
anyone udpate?
