### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by LuongNgoc19999** [natario1/CameraView#1144]
### How do I?
how do i control the output image on different devices
because in xiaomi output image is rotated 90 degrees but sumsung is not
### Version used
CameraView:2.7.2

**Comment by SweetD3v** [comment]
Just check the rotation of output image using `Exif`.
After that, If you want to rotate the image, then rotate it as per your needs. There are plenty of methods to do it.
Just check the rotation first of the output image, so you can apply your logic after that.
