### ISSUE TITLE
Is it possible to use 3d model view as overlay?

### ISSUE THREAD

**Issue by MadCoderme** [natario1/CameraView#1152]
### How do I?
The example in the docs showed a demo of adding ImageView as overlay, Is it possible to render 3d models as overlay as well as get them in snapshot?

### Version used
Latest version

**Comment by SweetD3v** [comment]
Have you tried anything to achieve that?

**Comment by MadCoderme** [comment]
I did. I tried 3d rendering libraries as well as webview. Doesn't work :(

**Comment by SweetD3v** [comment]
It's not a feature currently. So if you want to implement that type of functionality, then you should try it out yourself. :)
