### ISSUE TITLE
Problem with video recording. It's 90 degree rotation.

### ISSUE THREAD

**Issue by Dilawar-maavan** [natario1/CameraView#1154]
### How do I?
My camera activity is on portrait. And I'm recording the video. When video recording finished I'm sending it to BE to perform some processing on it.
The issue is that video is having 90 degree rotation issue. By look it's fine I mean video playing on portrait and looks like it's recorded as portrait but when I see the detail the frame width is grater than frame height. But frame width should be smaller than frame height in portrait screen.

### Version used
2.7.2.

**Comment by SweetD3v** [comment]
Can you attatch the required details like resolutions & screenshots?
