### ISSUE TITLE
Distortion in the the frozen preview of the picture that has just been taken 

### ISSUE THREAD

**Issue by siralam** [natario1/CameraView#116]
(I tested in Android 4.4.1, 5.0.2, 7.0.0 and 7.1.1, only reproduced in 4.4.1. (API19)).

```
            app:cameraCropOutput="true"
```
The above line has been set in XML.
However, the preview image right after clicking shutter, is still distorted in an Android 4.4.1 device.
The image is horizontally squeezed. i.e. Things look thinner than in real world.

**Comment by lsw19921030** [comment]
By the way, the output bitmap is correct. This aspect ratio problem appears only in the preview.

**Comment by lsw19921030** [comment]
I have tried all kinds of attributes:
```
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
```
```
            android:layout_width="match_parent"
            android:layout_height="match_parent"
```
With or without 
```
            app:cameraCropOutput="true"
```
With or without
```
            app:cameraPictureSizeAspectRatio="4:3"
```

But none of them produce correct result.

I have also checked that hardware acceleration is turned on.

**Comment by lsw19921030** [comment]
Here are the screenshots.

The "normal" preview (no picture token):
![screenshot_2017-11-27-17-58-11-942_com cehl windsorhouse](https://user-images.githubusercontent.com/28033467/33299750-1960ee8e-d428-11e7-9181-354ca9cabca4.png)

The distorted preview (The static preview when a picture is token):
![screenshot_2017-11-27-17-58-18-936_com cehl windsorhouse](https://user-images.githubusercontent.com/28033467/33299784-388cc3b4-d428-11e7-909a-65f1cd4a2824.png)

And the real bitmap that I saved in the device:
![screenshot_cameraview_final](https://user-images.githubusercontent.com/28033467/33299846-6e84ef5a-d428-11e7-9b27-36f20b8fc72b.jpg)

As you can see, the real bitmap (saved in the device) is actually larger (contains area that is not shown in the preview). 
The distorted preview showed the horizontal larger area, but not the vertical larger area, and thus distorted.

**Comment by natario1** [comment]
Hi, thanks for the report. What is the "static preview when a picture is taken"? 

We only have a preview (not distorted, I hope) and an output picture (not distorted, I hope). If I didn't get this, can you post a video?

**Comment by lsw19921030** [comment]
You got it, it is the preview that you mentioned. I call it static because in my mind there are 2 previews:
(1) Continuous picture showing in SurfaceView, when user takes no action
(2) The preview that freeze for about 1 second, act as the preview for the picture that user has taken

And I mean (2) is this issue

**Comment by natario1** [comment]
@siralam let me see if I got this, you mean that after you tap "take picture", the preview is distorted for some time (before loading the picture)?

**Comment by siralam** [comment]
I don't think this is that hard to understand...
So there indeed are 2 kinds of previews, as I have mentioned:
(1) The preview of the **camera**, which will change and move when you move your device, **before tapping "take picture"**
(2) The preview of the **picture taken**, which will **not** change and move when your move your device, and is **after tapping "take picture"**. And when this preview is ended, CameraView returns to preview of (1).

And the distortion occurs in (2).  
I hope this should be clear enough?!

**Comment by natario1** [comment]
2 is just an artifact, it's not something we can control, so I don't think this can be fixed. But I'll take a look.

(It should not happen if you use wrap_content for both dimensions and nothing else, but I don't know for sure)

**Comment by natario1** [comment]
(if this is so easy to understand to you, maybe it's easy for you to fix it too?)

**Comment by siralam** [comment]
At that time when I am choosing different libraries, only your library has this problem, no matter it is using Camera1 API or Camera2 API. So I think that should not be something that you cannot control, especially you mentioned in the doc that you have your own way to ensure previews are not distorted no matter what size of CameraView we specify (Which indicates you did something to the image returned from camera, before displaying it as a preview).

Understanding this issue and fixing it is of course 2 completely different difficulties, but I guess you are not saying this seriously, but rather offensively. Although I am not, I apologize if I made you feel offensive.

**Comment by natario1** [comment]
No problem, I should have added some smile face.

I can not reproduce this on my devices. But the thing is that we do not change the preview after 'capture' is clicked, it's something done by the internals in your specific device. 

Is your device/app hardware accelerated? What does `cameraView.isHardwareAccelerated()` return?
