### ISSUE TITLE
Changing session is slow also previews are not the same

### ISSUE THREAD

**Issue by Monster-king** [natario1/CameraView#117]
- [x] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Change session type from picture to video or from video to picture.

#### Expected behavior:
Fast changing and same previews
#### Actual behavior:
Changing session taking about 1.5 - 2 seconds, also preview in picture session is zoomed when preview in video session is not (see screenshots).
#### Screenshots:
when session type is video
![screenshot_2017-11-28-10-58-38](https://user-images.githubusercontent.com/18480424/33304972-a5d0d9a6-d42d-11e7-83cc-8ace652b60b4.jpg)
when session type is photo
![screenshot_2017-11-28-10-58-49](https://user-images.githubusercontent.com/18480424/33304984-b6e442e6-d42d-11e7-87eb-a4892df24840.jpg)

**Comment by natario1** [comment]
This is all working as intended. We change the preview size when recording video, to match the video output ratio. The whole logic is a bit messy but that's how it is at the moment.

For this reason (close preview, change size, open preview) changing session type is slow. This is common in camera apps though.

**Comment by Monster-king** [comment]
@natario1 How I can avoid this? Because in my case preview size not changing when session changes.

**Comment by natario1** [comment]
You can just use video mode without switching.

**Comment by Monster-king** [comment]
@natario1 Is it possible capture picture in video mode?

**Comment by natario1** [comment]
Yes, but the preview size will try to match the *video* output size, not the *picture* output size. Might not be a big deal.

**Comment by Monster-king** [comment]
@natario1 thx, works fine
