### ISSUE TITLE
How to rotate just the camera preview?

### ISSUE THREAD

**Issue by Adrianogba** [natario1/CameraView#1180]
### How do I rotate just the preview?
I received some devices with a problem with the camera, it's rotated 90º by default. How can I rotate just the preview of the camera in order to fix it on the app, since there will be no firmware update to fix the camera itself?
I've already implemented an example of solving the issue on a simple case using only CameraX, but I'm not finding something equivalent on CameraView.

Example of solving the issue I've done on CameraX: https://github.com/Adrianogba/k2_camera_rotation
![Screenshot_20220628_093236](https://user-images.githubusercontent.com/2891052/176180341-5eccc9ee-0840-4be0-adc6-28bec393d48f.png)

### Version used
CameraView 2.7.2.

**Comment by Abs-11001** [comment]
Have you solved this problem on cameraView? Because my equipment is having the same problem.

**Comment by xyhuangjia** [comment]
> Have you solved this problem on cameraView? Because my equipment is having the same problem.

大佬解决了？我这边也遇到这种问题了，预览和拍照旋转方案都不尽人意
