### ISSUE TITLE
Image lagging on 4.4.2 lg device

### ISSUE THREAD

**Issue by meparam** [natario1/CameraView#12]
after image taken it is lagging , not giving smooth scrolling of bottom layout.

**Comment by natario1** [comment]
You mean in the demo app? Can you explain better?

**Comment by meparam** [comment]
yes when i take the pic  afterword three option coming then in the PicturePreviewActivity when i scroll up it is lagging. please suggest

**Comment by natario1** [comment]
I can't reproduce this, but I think it might be due to us calling `startPreview()` from the UI thread after pictures taken. Threading still has to be improved. I will investigate, thanks

**Comment by meparam** [comment]
I think size of image is bigger in size that is causing for slow the UI.
Hopping to see update from u soon thanks.

**Comment by natario1** [comment]
I have fixed threading in latest version. You can check and let me know

**Comment by natario1** [comment]
So, I guess this is just a performance bug in the demo app, that should not load the full image in memory but rather show a smaller preview.
