### ISSUE TITLE
How to Record and Preview Video in Aspect ration 1:1

### ISSUE THREAD

**Issue by ritesh94** [natario1/CameraView#120]
How do I record and preview a video in 1:1 aspect ratio.

Currently, I am only able to record in 1:1 ratio but while previewing the video in bigger than ratio.

**Comment by natario1** [comment]
You can't, see existing issues

**Comment by ritesh94** [comment]
Is there any possibility that in near future this feature can be implemented , as  the library is good and I am proceeding to use this library.?

**Comment by natario1** [comment]
I have no time schedule, please subscribe to the open issue about this

**Comment by ritesh94** [comment]
ok Thanks for the support
