### ISSUE TITLE
Flash not working when using takePictureSnapshot

### ISSUE THREAD

**Issue by Vishal-beep136** [natario1/CameraView#1216]
- CameraView version: *2.7.2*
- Camera engine used: *camera2*
- Reproducible in official demo app: *Don't Know*
- Device / Android version: *Android 11*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

### To Reproduce
 Capture Picture using ```takePictureSnapshot()``` with flash enabled. I'm enabling flash on user clicks on flash icon then setting `camera.flash = Flash.ON`

### Expected behavior
Able to enable flash light i.e - ```Flash.ON```

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

```xml
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginVertical="@dimen/_8sdp"
        android:keepScreenOn="false"
        app:cameraAudio="off"
        app:cameraEngine="camera2"
        app:cameraFacing="back"
        app:cameraFlash="off"
        app:cameraGesturePinch="zoom"
        app:cameraGestureTap="autoFocus"
        app:cameraMode="picture"
        app:cameraPlaySounds="true"
        app:cameraPreview="glSurface"
        app:cameraUseDeviceOrientation="true"
        app:layout_constraintBottom_toTopOf="@id/cameraOptionLL"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/cameraGoHomeBtn" />
```

### Important NOTE

If I just tap on camera preview for some reason it enable flash light. But if just capture picture with ```takePictureSnapshot```
not working.

I appreciate any fix for this bug. I've already seen these issues #1204,  #1205 but no help.

**Comment by EzequielAdrianM** [comment]
This is no bug, it's expected behavior. Take picture snapshot directly records the glSurface, not sending any instruction to the Android Camera API's.
