### ISSUE TITLE
Preview stretches for a moment while switching front/back

### ISSUE THREAD

**Issue by DineshRajput21** [natario1/CameraView#126]
All functionality working perfectly but facing issue when switching camera from front to back. Camera jumps little bit and it is not like as native camera (like flip right to left with animation).

**Comment by developer--** [comment]
same for me

**Comment by LuckySambial** [comment]
having this issue with samsung devices only

**Comment by developer--** [comment]
Nope I tested it for Lenovo API 23

**Comment by LuckySambial** [comment]
I have done with all required functionalities in project but now I am stuck with this issue only...I can not replace this lib with another because I have used lot of functionality of this library in my project....can anyone help me on this ?

**Comment by natario1** [comment]
I still have no idea what this issue is about :) please post a video and the code you are using to trigger the change.

**Comment by LuckySambial** [comment]
Sure I will share video with you soon
Thanks for reply!!!

**Comment by LuckySambial** [comment]
please check proper issue from this video
https://www.dropbox.com/s/z7o6q8hbijtk3nq/IMG_1478.MOV?dl=0

**Comment by LuckySambial** [comment]
Here is the code that I am using for toggle camera.
    private void toggleCamera() {
        if (mCapturingPicture) return;
        switch (camera.toggleFacing()) {
            case BACK:
                message("Switched to back camera!", false);
                break;

            case FRONT:
                message("Switched to front camera!", false);
                break;
        }
    }

**Comment by LuckySambial** [comment]
As you can see in above video when I am trying to change camera view from front to back or visa versa then image squeezed. This is the exact issue I am facing, hope you got exact issue.

**Comment by LuckySambial** [comment]
It seems device specific issue only reproduced in Samsung edge and Lenovo phone till now.

**Comment by LuckySambial** [comment]
working fine with Moto and MI phone.

**Comment by developer--** [comment]
I tested it also for Samsung edge and it has stretched preview, but sometimes it has correct preview. Any suggestions?

**Comment by LuckySambial** [comment]
@developer I am also waiting for @natario1 response. I think he is busy in Christmas and new year party :)

**Comment by natario1** [comment]
@LuckySambial so you are talking about the fact that for a small second the preview stretches before switching?

**Comment by LuckySambial** [comment]
@natario1 yes exactly. can you please help me to fix that issue because my project stuck due to that issue.

**Comment by kunaldawn** [comment]
Hi any update on this?

**Comment by arrabidas92** [comment]
Hi, I face the same issue when switching front/back, the preview stretches before switching.
Any solution ?
