### ISSUE TITLE
Flash Bug

### ISSUE THREAD

**Issue by Shahidzbi4213** [natario1/CameraView#1267]
**Flash Auto** and **Flash On** is not working with camera2.

Picture/Video using **snapShotApi**

Device **Redmi Note 12** 
Android Version **14**

**Comment by EzequielAdrianM** [comment]
Hi, if you use the Picture Snapshot and Video Snapshot, it is taking a screenshot directly from the OpenGL surface. This means that photo and video are taken much faster, but the Android camera was never actually ordered to take anything, thats why you see no flash. If you want all the camera functionalities you must use the takePicture and recordVideo (no snapshot) versions.

**Comment by Shahidzbi4213** [comment]
Thanks buddy for clearing that up but that also means with takePicture()/Video we will not be - able to show the watermark.

**Comment by EzequielAdrianM** [comment]
According to the [documentation](https://natario1.github.io/CameraView/docs/watermarks-and-overlays) watermark only works when using snapshot. Anyway, you can manually attach your watermark(bitmap) overlay into the picture using a canvas. And for watermark in video I highly recommend using [LiTr](https://github.com/linkedin/LiTr). We use it in production for overlay bitmap, gif, and stickers in our videos and works like a champ.

**Comment by Shahidzbi4213** [comment]
Actually my task is to show timer running on the video with geo-location tag is it possible to achieve using the recommended library?
