### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException startPreview failed

### ISSUE THREAD

**Issue by derohimat** [natario1/CameraView#132]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. I get this from Crashlytics [here for detail](http://crashes.to/s/04021218714)

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by sahityakumarsuman** [comment]
derohimat can you tell me how you solved this error

**Comment by derohimat** [comment]
@sahityakumarsuman I don't know, because I get this error and now didn't solved

**Comment by sahityakumarsuman** [comment]
if anyone solved this one please answer . it will be good help.

**Comment by natario1** [comment]
Subscribe or contribute to #122 please
