### ISSUE TITLE
Ability to choose the encoding format

### ISSUE THREAD

**Issue by Aissa-H** [natario1/CameraView#136]
Hi @natario1 and users, hope you're fine !

A small suggestion concerning the encoding format: I think it will be great if we can **choose the encoder** we want for the video : H264 ... 

In fact I'm working on an app currently and some devices use a deprecated encoder by default (for example the Huawei  MHA-L09 encode in HEVC (a.k.a. H.265) ). The problem of these encoder is that they can be **unreadable** on other OS like iOS devices and so the video is valid only on Android.

Maybe we can add a setter or pass in parameter of the `startVideo()` method the encoder we want to the cameraView object and the setted value will be used on this line:
https://github.com/natario1/CameraView/blob/1bd1816919ead3a721aa51cb3813395503762014/cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java#L663

What do you think about it ? 

Thank you in advance 👍

**Comment by natario1** [comment]
Yes, we should add this!
