### ISSUE TITLE
onPictureTaken() never gets called when capturePicture() is hit.

### ISSUE THREAD

**Issue by jaspreet-android** [natario1/CameraView#140]
public class MyCameraViewer extends AppCompatActivity {
    private CameraView cameraView;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
        setContentView(R.layout.activity_camera_viewer);
        CameraLogger.setLogLevel(CameraLogger.LEVEL_ERROR);
        cameraView = (CameraView) findViewById(R.id.aCamera);
        ImageView btnClick = (ImageView) findViewById(R.id.takePic);
        cameraView.addCameraListener(new CameraListener() {
            public void onPictureTaken(byte[] jpeg) {
                Log.e("Picture", "JPEG: " + jpeg.length);
                Intent intent = new Intent();
                intent.putExtra("byteArray", jpeg);
                setResult(RESULT_OK, intent);
                MyCameraViewer.this.finish();
            }
        });
        btnClick.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                cameraView.capturePicture();
            }
        });
    }
    @Override
    protected void onResume() {
        super.onResume();
        cameraView.start();
    }
   @Override
    protected void onPause() {
        super.onPause();
        cameraView.stop();
    }
    @Override
    protected void onDestroy() {
        super.onDestroy();
        cameraView.destroy();
    }
    @Override
    public void onBackPressed() {
        finish();
    }
}

- [x] *I am using the latest version*
- [x] *I can't see the bug in the demo app, so may need to create new sample without using controllers.
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Just create a new sample with above code and try to use this Activity with line startActivityForResult();
2. I have used same CameraView code in layout as you have in your example.
3. I used a imageView to click and capture image.

**Comment by DaCrAn** [comment]
Hi @jaspreet-android,
I got the same problem but you can actually fix it if you use a new tread.

Observable.just(cameraView)
                                        .observeOn(AndroidSchedulers.mainThread())
                                        .subscribeOn(Schedulers.newThread())
                                        .subscribe(new Observer<CameraView>() {
                                            @Override
                                            public void onSubscribe(Disposable d) {

                                            }

                                            @Override
                                            public void onNext(CameraView cameraView) {
                                                cameraView.capturePicture();
                                            }

                                            @Override
                                            public void onError(Throwable e) {
                                                Toast.makeText(getContext(), e.getMessage(), Toast.LENGTH_SHORT).show();
                                            }

                                            @Override
                                            public void onComplete() {

                                            }
                                        });
