### ISSUE TITLE
Handling rotation

### ISSUE THREAD

**Issue by HD-AD** [natario1/CameraView#141]
As the title says, the view is taking to long to be displayed. When the activity is created/rotated it takes time to load resulting in a white screen (background) to be displayed till cameraView is loaded.

**Comment by natario1** [comment]
It's much better if you don't recreate your camera activity for rotations. This is basic Android stuff, just Google it 🙂

The loading time is needed to connect to the hardware, allocate buffers etc.

**Comment by HD-AD** [comment]
@natario1 But when I disable screen orientation by adding this to my Activity in the Manifest `android:configChanges="keyboardHidden|orientation|screenSize"` the camera orientation is wrong when I rotate the device.

**Comment by natario1** [comment]
With this flag the preview won't change, like every camera app does. Rotating the device will have no effect and that's generally good

**Comment by natario1** [comment]
Using button.setRotation() and the orientation callback in the CameraListener

**Comment by HD-AD** [comment]
@natario1 `android:configChanges="keyboardHidden|orientation|screenSize"` still doesn't work for me, the screen still rotates, the Activity is not recreated but CameraView still rotates (in the wrong orientation) and if I set `android:screenOrientation="portrait"` then rotation is not picked up in CameraListner callback

**Comment by natario1** [comment]
You must use both lines!

**Comment by HD-AD** [comment]
Haaa! I got it working, thank you for taking the time to help me and creating a AWSOME library!
