### ISSUE TITLE
Camera capture and preview doesn't match when camera height/width changed from match_parent to anything else.

### ISSUE THREAD

**Issue by Ashutosh-Tiwari** [natario1/CameraView#145]
I am using the latest version of the library.
The bug (unexpected behaviour) can be reproduced in the Demo App itself.

Steps:
1. Open the demo app, default `width` and `height` of the `camera` would be `match_parent`.
2. Capture a photo of an object with "exact corners".
3. Change the `height` of the `camera` (to any acceptable `height` from available options) from the provided "edit" options
4. Capture the photo of the same object with same "exact corners" you captured last time.

You will see that the first capture was accurate, but the second capture will capture, more than what is visible in the preview, from the top.

Screenshots:
1. match_parent height - preview
![match_parent_preview](https://user-images.githubusercontent.com/17219007/35030559-61964c60-fb85-11e7-8da5-c6ac800aea22.png)

2. match_parent height - capture
![match_parent_capture](https://user-images.githubusercontent.com/17219007/35030589-85670b3e-fb85-11e7-8a33-d8a0dbcd5808.png)

3. 672 height - preview
![heigh_672](https://user-images.githubusercontent.com/17219007/35030607-9619559a-fb85-11e7-8ea0-fb6fe68b562e.png)

4. 672 height - capture
![height_672_capture](https://user-images.githubusercontent.com/17219007/35030614-a3fb8a84-fb85-11e7-81cb-4ff29509eaef.png)

U can see that the photo captured in 4th screenshot ha more been captured more from top than what is visible in preview, whereas the capture in match_parent params is just fine.

No issues if the capture from bottom is not cropped and captures the whole screen till the bottom. But the top should not capture what is not visible in the preview.
Please help me on this asap. @natario1

**Comment by natario1** [comment]
If you want your preview to be equal to the result, use wrap_content.

**Comment by natario1** [comment]
I think you just need to set cropOutput to true.
