### ISSUE TITLE
Video duration limit is not working as expected

### ISSUE THREAD

**Issue by Aks-4125** [natario1/CameraView#149]
Code configuration of recording video for 10 sec

      `private void captureVideo() {

        if (camera.getSessionType() != SessionType.VIDEO) {

            message("Can't record video while session type is 'picture'.", false);

            return;

        }
       ....
       ....
        camera.startCapturingVideo(null, 10000);
    }`

actual output is of 8 seconds only: 

![device-2018-01-22-115126](https://user-images.githubusercontent.com/29367708/35207747-b051e27c-ff6a-11e7-82bc-bfa7ac131e4d.png)

#65

**Comment by natario1** [comment]
We are aware... Please subscribe to #65 .
