### ISSUE TITLE
Add prefix for resources

### ISSUE THREAD

**Issue by RocketRider** [natario1/CameraView#160]
The resources "surface_view.xml" and "texture_view.xml" are very generic names and maybe are used by the app or an other library. This could lead to mix up of these resources.
So it is recommended to prefix library resources.

https://medium.com/@maxirosson/how-to-improve-your-android-library-2e8b9fd6c090

**Comment by natario1** [comment]
Right. Could you do this?

**Comment by RocketRider** [comment]
Made a pull request

**Comment by natario1** [comment]
Cool! Let's wait for Travis

**Comment by natario1** [comment]
Thanks!
