### ISSUE TITLE
capturePicture followed by toggleFacing has issues

### ISSUE THREAD

**Issue by yumcoder-platform** [natario1/CameraView#164]
- I am using the latest version
- capturePicture() does not take a picture!

Detailed steps to reproduce the issue:
1- call the  camera1.capturePicture()
2- and if user immediately click on toggle facing buttom (when capturePicture is in progress) the CameraView.toggleFacing() is called
3- camera1.capturePicture() is disable!

#### Expected behavior:
after call toggleFacing, capturePicture take a picture

#### problem description:
1-   camera1.capturePicture() --> mIsCapturingImage = true;
2-  CameraView.toggleFacing() --> camera1.onStop() --> mCamera.release(); and mIsCapturingImage is never false
3- camera1.capturePicture() does not work beacuse when mIsCapturingImage==true capturePicture return immediately

#### how to fix it:
in the last line of camera1.onStop() add the following line:
 **mIsCapturingImage = false;**

**Comment by natario1** [comment]
I don't think `mIsCapturingImage` has a role here, the operations are executed in their order.

But maybe this can be improved.

**Comment by natario1** [comment]
For the moment, you should wait for the picture callback before using toggleFacing.

**Comment by natario1** [comment]
Thanks, I understand what you were saying now that I took a look. It should be fixed as you said! #173
