### ISSUE TITLE
How to set crop width and height?

### ISSUE THREAD

**Issue by asadullahrao** [natario1/CameraView#169]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1.
2.
3.

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by guness** [comment]
I guess you can just set width and height of the preview and let the library crop output for you.

**Comment by xsacha** [comment]
Is there a way to prevent it from doing a center crop?
I would like to view exactly the top of the image as that's the section I process in my jni library.

**Comment by natario1** [comment]
@xsacha no way, sorry, you can only use `wrap_content` to do no crop at all. We crop the preview with a centerCrop behavior.
