### ISSUE TITLE
"Invalid Masking Parameters"

### ISSUE THREAD

**Issue by gohaneri** [natario1/CameraView#185]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ x ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Launch activity with cameraview hidden by a view in portrait
2. Rotate in landscape, remove hidden view, start camera
3. Popup comes up with following text : "Invalid Masking Parameters"

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
Thanks for the report. We are not triggering explicitly the popup, I don't know where it comes from. Searching on google gives 0 results, so I don't think we can go forward on this one. If you have more info feel free to reopen.
