### ISSUE TITLE
How to Crop the "center rectangle" part of the full width camera view?

### ISSUE THREAD

**Issue by asadullahrao** [natario1/CameraView#186]
How to Crop the "center rectangle" part of the full width camera view. How to set camera bounds. And how to crop center rectangle part of the image.

I want  to place a rectangle at the center of the camera frame and want that specific part as output cropped image.

**Comment by natario1** [comment]
You can use a rectangular `CameraView` (set width and height to the same value) and set `cropOutput` to true to get a square picture. 

If you want to crop the inside, that's something you should do on your own on the image result, it's not supported by the library.
