### ISSUE TITLE
Frame processor error

### ISSUE THREAD

**Issue by huweijian5** [natario1/CameraView#197]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ 1.5.0] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1.size:480*320
2.
3.

#### Expected behavior:
frame data size is 230400
#### Actual behavior:
230401
#### Screenshots:
![image](https://user-images.githubusercontent.com/6566963/38541503-de6137ea-3cd1-11e8-9f88-ad21282896d5.png)

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by ssakhavi** [comment]
I also have encountered the same problem.

**Comment by natario1** [comment]
I think we can remove the +1 here

https://github.com/natario1/CameraView/blob/f6b2506ecf755527c93ba419268797a033a785c4/cameraview/src/main/java/com/otaliastudios/cameraview/FrameManager.java#L91

Can some of you submit a PR?

**Comment by natario1** [comment]
Thanks @ssakhavi !
