### ISSUE TITLE
The result image are rotated.

### ISSUE THREAD

**Issue by jinfagang** [natario1/CameraView#203]
Just using the default settings, the result of images are rotated. How to set it as not rotated anyway?

**Comment by canuludag** [comment]
Hi @jinfagang ,
You should use `CameraUtils.decodeBitmap(` method. Camera response `byte[]` data contains image rotation info. And the resulted bitmap conversion works as expected with correct orientation. 
Do not use `Bitmap cameraBitmap = BitmapFactory.decodeByteArray(byteArray, 0, byteArray.length);` bitmap creation method. Instead use this one:

```
CameraUtils.decodeBitmap(byteArray, new CameraUtils.BitmapCallback() {
            @Override
            public void onBitmapReady(Bitmap bitmap) {
                // Do whatever you want with your Bitmap
                // Save it as file or set into ImageView
            }
        });
```
Hope this helps!

**Comment by jinfagang** [comment]
Thanks, already figure it out.

**Comment by MoustafaElsaghier** [comment]
this solution does not work with me.

when I capture an image in landscape mode (in forced portrait activity ) it rotates the image to portrait.

**Comment by jinfagang** [comment]
@MoustafaElsaghier  This happend specific on some model Phones. You can judge it and rotate the matrix.

**Comment by MoustafaElsaghier** [comment]
@jinfagang yeah I did it and worked well by getting value if phone rotated by and rotate the matrix with it.

**Comment by MoustafaElsaghier** [comment]
@jinfagang hello, sorry for asking again. will if differ from front and back camera?

s It works well for me in front camera only and for back camera portrait mode get rotated by 180
