### ISSUE TITLE
Disable Shutter Sound

### ISSUE THREAD

**Issue by Patte1808** [natario1/CameraView#208]
Hey,

in the docs and source code you are saying that 

> the Camera1 engine will always play shutter sounds regardless of this flag

When passing null as a shutter callback, the shutter sound can be disabled and it still seems to work fine. See (Camera1.java, Line 507):
`mCamera.takePicture(
                        null,
                        null,
                        null,
                        new Camera.PictureCallback() {
                            @Override
                            public void onPictureTaken(byte[] data, final Camera camera) {
                                mIsCapturingImage = false;
                                mCameraCallbacks.processImage(data, outputMatchesView, outputFlip);
                                camera.startPreview(); // This is needed, read somewhere in the docs.
                            }
                        }
                );`

Do you see any trade offs passing null there? Would you accept a PR making the shutter optional?

Best,
Patte

**Comment by natario1** [comment]
The docs/comments might be outdated, you can actually use `setPlaySounds()` and we will use `camera.enableShutterSounds(false)`. Not all devices will support this, but that's the best we can do.
