### ISSUE TITLE
How do I connect the flashlight using your library?

### ISSUE THREAD

**Issue by NicolasGuarino** [natario1/CameraView#210]
My question is very simple ...

How do I connect the flashlight of the phone using your camera?

With the normal camera is thus, to serve as reference:

Camera cam = Camera.open ();
Parameters p = cam.getParameters ();
p.setFlashMode (Parameters.FLASH_MODE_TORCH);
cam.setParameters (p);
cam.startPreview ();

**Comment by elementlo** [comment]
like this:
camera.setFlash();//Flash.off etc.
