### ISSUE TITLE
Issue in captured video with certain VideoQualities  on Moto M 

### ISSUE THREAD

**Issue by vikassminq** [natario1/CameraView#211]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [Yes ] *I am using the latest version*

- [Yes ] *I can reproduce the bug in the demo app, and if not...*

- [Yes ] *I have tried to reproduce the bug in the demo app*

#### Expected behavior:
Support for all Video Quality

#### Actual behavior:
Just support for lowest .

#### Interesting logs:
If i use other cameraVideoQuality as highest or any other then it throw "Cant play this video " 
*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
There is nothing we can do about it, it is a device specific issue. There are already a few bugs (maybe one) related to videos not recorded correctly on some VideoQualities. Please subscribe to that to receive updates.
