### ISSUE TITLE
Activity Leak caused by HandlerThread

### ISSUE THREAD

**Issue by orange7** [natario1/CameraView#216]
CameraView is so awesome. I just implemented the Frame processor for barcode detection. However, Leakcanary keeps telling me there is a memory leak!

[x ] I am using the latest version (1.5.0)
 I can reproduce the bug in the demo app, and if not...
 I have tried to reproduce the bug in the demo app
Detailed steps to reproduce the issue:

Install Leakcanary
Use CameraView in an Activity.
finish the Activity with a CameraView and get alerted of the activity leaking.
Expected behavior:

Activity is not leaked.

Actual behavior:

Interesting logs:

The leak trace.

 co.stackstorage.mover.feature.createitem.CreateItemActivity has leaked:
* GC ROOT android.os.HandlerThread.<Java Local>
* references android.os.HandlerThread.uncaughtExceptionHandler
* references com.otaliastudios.cameraview.CameraController$1.this$0 (anonymous implementation of java.lang.Thread$UncaughtExceptionHandler)
* references com.otaliastudios.cameraview.Camera1.mCameraCallbacks
* references com.otaliastudios.cameraview.CameraView$Callbacks.this$0
* references com.otaliastudios.cameraview.CameraView.mContext
* leaks co.stackstorage.mover.feature.createitem.CreateItemActivity instance

**Comment by natario1** [comment]
Make sure you are calling `cameraView.destroy()`, there we release all these references.
