### ISSUE TITLE
Make zoom speed configurable

### ISSUE THREAD

**Issue by MaxMaes** [natario1/CameraView#217]
When mapping the pinch gesture to the zoom action, the zoom speed is too fast for my usecase. I see some sensitivity stuff in the PinchGestureLayout, perhaps if this is made accessible somehow, could we control zoom speed :) ?

**Comment by natario1** [comment]
That makes sense! Feel free to work on it 👍

**Comment by natario1** [comment]
I doubt we'll ever add this so I'm going to close this. Thanks!
