### ISSUE TITLE
Is there a way to turn off continuous focus?

### ISSUE THREAD

**Issue by alxrm** [natario1/CameraView#223]
Hi, great library, really appreciate your work, this one is the best there is IMHO!

Although is there a way to **disable the continuous focus**? It becomes very annoying if you do the full zoom in and try to capture some photos like that. It's pretty easy to capture a blurry photo because of that.

Thanks in advance!

**Comment by natario1** [comment]
Thanks! There is no way and there was some discussion about it in #107 , feel free to follow up there
