### ISSUE TITLE
Feature request: cut video in parts after recording

### ISSUE THREAD

**Issue by agalfioni** [natario1/CameraView#237]
First of all, this library is great!! :)

i dont know if its possible or i must use other library to do that, but i want to cut video recorded in parts. For example, if i have a video with 4:20 minutes length, i want to cut it with parts max duration 1 minute; then the result must be 4 videos of 1 minute length and 1 video with 20 seconds.

Thanks!

**Comment by natario1** [comment]
Not really possible, and goes beyond the scope of the library, sorry!
