### ISSUE TITLE
Prevent rotation and flip?

### ISSUE THREAD

**Issue by wider2** [natario1/CameraView#243]
Is it possible to turn off the features like
OrientationChanged
Flip

I just need to get snapshot photo as is with your library com.otaliastudios:cameraview

**Comment by agalfioni** [comment]
Hello @wider2 , in an Activity u can use :
`int currentOrientation = getResources().getConfiguration().orientation;`
to obtain current orientation, and then set orientation to not change with:
`setRequestedOrientation(currentOrientation)`

Also u can set to portrait or landscape with method `setRequestedOrientation` and use as parameter constant 
`ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE` or `ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT`
