### ISSUE TITLE
Media Recorder Failed: -38 / Camera1: Error while starting MediaRecorder

### ISSUE THREAD

**Issue by bekspur** [natario1/CameraView#244]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ X] *I am using the latest version*
- [] *I can reproduce the bug in the demo app, and if not...*
- [] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Create two camera's instances
2. Start both cameras recording functionalities at same time with "startCapturingVideo()"

#### Expected behavior:

Start recording and save output data in different files.

#### Actual behavior:

Getting this error while trying to startCapturingVideo from both cameras at same time.

`07-18 21:46:42.278 26310-26347/com.*** E/MediaRecorder: start failed: -38
07-18 21:46:42.279 26310-26347/com.*** E/Camera1: Error while starting MediaRecorder. Swallowing. java.lang.IllegalStateException
    java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:632)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
07-18 21:46:42.279 26310-26347/com.*** E/MediaRecorder: stop called in an invalid state: 0`

#### Screenshots:

<img width="1095" alt="screen shot 2018-07-18 at 6 54 45 pm" src="https://user-images.githubusercontent.com/40346442/42916953-580f067a-8abc-11e8-8a59-880fe1c1be2c.png">

**Comment by natario1** [comment]
I don't think you can use two cameras at same time unfortunately.
