### ISSUE TITLE
capturePicture() is not working for the first time. 

### ISSUE THREAD

**Issue by PrinceBE** [natario1/CameraView#258]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ x] *I am using the latest version*
- [ x] *I can reproduce the bug in the demo app, and if not...*
- [x ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. capture picture is not working for the first time when i click the photo. For the second time its working
2.
3.

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
So what error do you see?
