### ISSUE TITLE
MediaRecorder: stop failed: -1007

### ISSUE THREAD

**Issue by tyl210110** [natario1/CameraView#259]
This problem often occurs：MediaRecorder: stop failed: -1007

**Comment by suarezu** [comment]
yes, this is a fabulous library, but when recording video at the first time or switching from video to picture or from picture to video, it always reports this error

MediaRecorder: stop failed: -1007

and all subsequent same type operations seem successful, please help

**Comment by wasim5390** [comment]
Start Recording like this,

**Comment by natario1** [comment]
I'm sorry, MediaRecorder fails for a number of reasons and gives no clue about what's wrong, most of the times it's something device specific that we have no control about.

If you can post a demo app that immediately reproduces this issue, I will take a look and reopen.
