### ISSUE TITLE
Can't perform click event when permission is not granted

### ISSUE THREAD

**Issue by rrocav3** [natario1/CameraView#262]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Disabled Camera permission
2. Call cameraView.start(); inside onResume of Fragment
3. Clicks in UI (Activity views) are not performed

#### Expected behavior:
Can perform click in UI
#### Actual behavior:
Can't perform click in UI
#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

#### Device:
Android 8.0
Xperia X Compact

**Comment by natario1** [comment]
Can you post an app that immediately reproduce this issue? The demo app works well and does the same.
