### ISSUE TITLE
SensorLandscape  orientaion not supported

### ISSUE THREAD

**Issue by abkoradiya** [natario1/CameraView#263]
*SensorLandscape  orientaion not supported by camera as activity *

- [X] *I am using the latest version*
- [X] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. If I set orientation to sensorLandscape in activity, camera not change with orientation.
2.
3.

**Comment by natario1** [comment]
That's how android activity work!
