### ISSUE TITLE
Capture Image Takes long Time for saving

### ISSUE THREAD

**Issue by MoustafaElsaghier** [natario1/CameraView#267]
- [ x ] *I am using the latest version*
- [ x ] *I can reproduce the bug in the demo app, and if not...*
- [ x ] *I have tried to reproduce the bug in the demo app*

1.open camera app (Demo) try to take a photo it gets latency time about 1 second which is not noticeable in-demo as it goes to other activity but my case I'm trying to use it in the same activity and store it to the gallery. but it takes too long time for doing that.

#### Expected behavior:
take a photo fast as normal app doing and would like if there a save to gallery option (maximum speed)

#### Actual behavior:
slow capture and slow save time.

**Comment by natario1** [comment]
You should probably save in a background thread. Also try reducing the picture size before shooting.
