### ISSUE TITLE
onVideoTaken called right after startCapturingVideo(null) 

### ISSUE THREAD

**Issue by SUBINPTPM** [natario1/CameraView#268]
While I take video sometimes its work fine for me. But sometimes While taking a video camera.startCapturingVideo(null);  automatically call the public void onVideoTaken(File video) .

Log :: 
I/CameraController: Restart: returned from start. Dispatching. State: STATE_STARTED
I/CameraCallbacks: dispatchOnCameraOpened com.otaliastudios.cameraview.CameraOptions@61755df
W/MediaRecorder: mediarecorder went away with unhandled events
W/MediaRecorder: mediarecorder went away with unhandled events
I/CameraController: Stop: executing. State: STATE_STARTED
    Stop: about to call onStop()
I/Camera1: onStop: About to clean up.
    onStop: Clean up. Ending video.
    endVideoImmediately: is capturing: false
    onStop: Clean up. Stopping preview.
I/Camera1: onStop: Clean up. Stopped preview.
    onStop: Clean up. Releasing camera.
I/Camera1: onStop: Clean up. Released camera.
W/Camera1: onStop: Clean up. Returning.
I/CameraController: Stop: returned from onStop(). Dispatching.
I/CameraCallbacks: dispatchOnCameraClosed
E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
I/Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
I/CameraPreview: crop: applied scaleX= 1.1407409
    crop: applied scaleY= 1.0

[StackOverflow link](https://stackoverflow.com/q/52362219/6299045)

**Comment by kamleshkarwande** [comment]
I am also facing the same problem, any update on the issue.

**Comment by SUBINPTPM** [comment]
@kamleshkarwandeI add a delay for the camera. start capturing. that adds a delay between camera session switching and he camera.start capturing. IOts not the best solution, may it help to resolve this issue for a while

**Comment by SUBINPTPM** [comment]
I already open an issue in[ stackoverflow](https://stackoverflow.com/q/52362219/6299045)

**Comment by jom16antonio** [comment]
Ive experienced this as well, it happens when I call capturePicture before startcapturingVideo.
I wanted to take a picture shot first, before proceeding to video recording and the issue happens.

**Comment by natario1** [comment]
Can you post a app that reproduce this? A simple patch to demo app maybe? So I can pull your repo and see.
