### ISSUE TITLE
Small error: cameraJpegQuality 0 <= n <= 100

### ISSUE THREAD

**Issue by freimaks** [natario1/CameraView#27]
Apparently there is a small error in the documentation: the quality of the jpeg must be greater than 0 and less than or equal to 100 (0 < n <= 100).

If you try to set 0, then there will be an error:

`java.lang.RuntimeException: Unable to resume activity {com.myapp.myapp/com.myapp.myapp.MainActivity}: java.lang.IllegalArgumentException: JPEG quality should be > 0 and <= 0`

**Comment by natario1** [comment]
I have submitted a fix, thanks!
