### ISSUE TITLE
RuntimeExceptoin: Fail to connect to camera service

### ISSUE THREAD

**Issue by enlte** [natario1/CameraView#270]
at com.otaliastudios.cameraview.Camera1.onStart(Camera1.java:172)
at com.otaliastudios.cameraview.CameraController$3.run(CameraController.java:180)

*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [1.4.1 ] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app, and if not...*
- [x] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. 
2.
3.

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
Please use latest version, and override onCameraError to see the error.
