### ISSUE TITLE
setPictureSize called twice but the 2nd call has no effect

### ISSUE THREAD

**Issue by suarezu** [natario1/CameraView#271]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x ] *I am using the latest version*
- [x ] *I can reproduce the bug in the demo app, and if not...*
- [x ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. setPictureSize(new SizeSelector(){...}) to retrieve the supported resolutions by some device
2. user choose a resolution
3. setPictureSize(SizeSelectors.and(minWidth/minHeight=chosen resolution)

#### Expected behavior:
the picture taken has the chosen specification
#### Actual behavior:
the first resolution in the list in Step 1 is chosen by the camera, no matter what user chooses otherwise
#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
This change will take place only when you restart the camera using stop() and start() again.

**Comment by suarezu** [comment]
is there a way to retrieve the supported resolutions without really configuring the camera? or every time this size changes the camera needs to be restarted? but the video quality can be dynamically set before startCapturingVideo(...) without restarting. so is this an inconsistency?

**Comment by natario1** [comment]
Yes, currently you need to restart it every time the pictureSizeSelector changes for it to take place. But the picture size, influences the preview size and so the preview must stop and restart.

Other parameters like VideoQuality and many more, will not need a restart like you said

**Comment by natario1** [comment]
How can you say that? If you look at the source code you can see that it is replaced instantly.

**Comment by suarezu** [comment]
Sorry for annoying you, I just tried again, I have made a mistake before,  very sorry for my bad. it should be set as follows:
CameraView.setPictureSize(SizeSelectors.and(
                SizeSelectors.minHeight(1920), SizeSelectors.maxHeight(1920),
                SizeSelectors.minWidth(1080), SizeSelectors.maxWidth(1080)));

**Comment by suarezu** [comment]
by the way, would you like to consider the possibility of querying the supported picture resolutions without really start the camera?

**Comment by suarezu** [comment]
yes, that's just an example to narrow the choice to the exact resolution. the flexible means should be taking one Size from those supported.

**Comment by suarezu** [comment]
@natario1 sometimes setPictureSize(new SizeSelector(){...}) will extract an empty list for the supported Sizes. in this occasion, I dont know what will happened if an empty list returned for the size selector. if it's not acceptable, a Size(width, height) should be provided for mandatory manipulation, right?

**Comment by natario1** [comment]
In input you get all the supported Sizes. If you return an empty list, we will default to the biggest of them. We can't create them, the Camera will accept only those that are provided

**Comment by suarezu** [comment]
seems at that rare occasions we have to be blind to take an picture of an unknown size
