### ISSUE TITLE
i want use default camera height=getWindowManager().getDefaultDisplay().getHeight() /2;

### ISSUE THREAD

**Issue by Rupeshrajsingh** [natario1/CameraView#274]
<com.otaliastudios.cameraview.CameraView
    android:id="@+id/camera"
    android:keepScreenOn="true"
    android:layout_width="wrap_content"
    android:layout_height="300dp"
             ....................... />

**Comment by Rupeshrajsingh** [comment]
i used  compile 'com.otaliastudios:cameraview:1.6.0' in my build.gradle(Module.app) 
and app iss running well but i want to customize default camera height.

**Comment by natario1** [comment]
You can ask this question on StackOverflow! This is not related to CameraView
