### ISSUE TITLE
Custom XML to make the preview round not working

### ISSUE THREAD

**Issue by codebreaker9904** [natario1/CameraView#275]
I am trying to make the preview round(Same like you get on Skype or whatsapp), for that i created a XML, and using it as a background with no effect. Below is the snippet of XML:

NOTE: Parent Layout is circular, but the preview comes out to be square.

    <RelativeLayout
        android:layout_width="120dp"
        android:layout_height="120dp"
        android:background="@drawable/circlelayout"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginRight="15dp"
        android:layout_marginBottom="15dp"
        android:id="@+id/selfCameraView"
        >
        <com.otaliastudios.cameraview.CameraView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/circlelayout"
            android:id="@+id/videocameraV"
            app:cameraFacing="front"
            app:cameraWhiteBalance="auto"
            android:keepScreenOn="true"
            />

    </RelativeLayout>

**Comment by natario1** [comment]
Well backgrounds do not clip the view itself. Try asking this on StackOverflow, sorry.
