### ISSUE TITLE
setVideoMax[Duration|Size]() may fail (e.g.: Target duration (x us) too short to be respected)

### ISSUE THREAD

**Issue by Johnson145** [natario1/CameraView#277]
- [x] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Use e.g. an old Samsung Galaxy S2 
2. Set the maximum video duration to e.g. 10s
3. Start recording the video

#### Expected behavior:
The video should stop after 10s. If 10s isn't a valid configuration, there should be an error.

#### Actual behavior:
The video recording never stops. There is no error we can catch. At some point we'll get memory issues and the device freezes completely.

### Description
The changes made in #172 seem to cause troubles at least for some specific configurations. They fail at least on on old Samsung Galaxy S2 with Android 4.1.2. If you take a look at the logs you'll only find something like `StagefrightRecorder: Target duration (5000000 us) too short to be respected`. I searched for the _StagefrightRecorder_ and found [this source code](https://android.googlesource.com/platform/frameworks/av/%2B/69113e8ccc30fbdb8733ca2070bd3491b21e656d/media/libmediaplayerservice/StagefrightRecorder.cpp), which seems to be part of the Android Open Source Project. It causes similar issues for the max file size, but lets look at the maximum video duration for now: The code does only provide a "real error", if the video duration isn't greater than 100ms. It does except all greater values without an error. However, values in [101ms, 15s] do trigger the above warning. The value is changed, but doesn't work at all.

I'm not yet sure how to handle this ideally. We could write a custom fallback, which is triggered after some timeout, if the video has still not been ended correctly. Don't know how many devices are still using the problematic _StagefrightRecorder_. Don't know whether similar bugs are included in other implementations either. If we don't make any code changes, it's probably a good idea to at least add a hint to the docs.

**Update**
I've just found out that the same warning is present on newer devices and Android versions as well. So the same _StagefrightRecorder_ code seems still to be used. However, on newer versions everything works as expected though. So the issue I've described may or may not be directly associated with the problematic behavior. I'll do some more research on this.

**Comment by natario1** [comment]
I would say this is a `StagefrightRecorder` bug in older APIs, and I see no way to fix this without adding a lot of complexity and overhead.
