### ISSUE TITLE
convert frame to YuvImage issue

### ISSUE THREAD

**Issue by VernonLee** [natario1/CameraView#278]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ yes] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1.
2.
3.

#### Screenshots:
![46371798555277](https://user-images.githubusercontent.com/5925253/46252470-74999f80-c49b-11e8-84ee-13de77e9f7e2.jpeg)

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
We pass the byte[] array from Camera1, not modified. Either an issue with your device, your sensor, your yuv conversion or Camera1 internals.
