### ISSUE TITLE
Capturing photo/video on Samsung Galaxy Note 8 not working at all

### ISSUE THREAD

**Issue by arrabidas92** [natario1/CameraView#279]
Prerequisites:

*I am using the latest version*

#### Detailed steps to reproduce the issue:

Try to capture a snapshot/video on Samsung Galaxy Note 8

#### Expected behavior:

Display picture or video preview

#### Actual behavior:

Picture taken or video not displayed and loader is infinite.

The same code run perfectly on other phones like Motorola, Doogee but this issue is only on Samsung devices.
![43119260_1895376183864376_3539953380128456704_n](https://user-images.githubusercontent.com/19395512/46365205-49b87280-c678-11e8-8196-1b4aa8d9538d.jpg)

I also have this issue using directly camera 2 api. If you have some advice, I take it.

**Comment by Namazed** [comment]
Hi, @arrabidas92.
Did you used CameraLogger? Can you show your logs when you taking a picture or video?

**Comment by arrabidas92** [comment]
Finally I solved my issue by disabling hardware acceleration.
Now it works !
