### ISSUE TITLE
Excellent library !

### ISSUE THREAD

**Issue by amervelic** [natario1/CameraView#282]
Excellent library. I've tried CameraKIT (landscape problem preview), CameraFragment (the same), "Photoapparat" (images are too big) but this is BEST!

- takeSnapshot / looks great
- I should have pictures less than 100KB / excellent
- a bit of code / excellent
- a great number of options / great

Thank you !!!

Tip: Compression speed is slightly slower

**Comment by natario1** [comment]
Thanks! Best bug report so far 🙂
