### ISSUE TITLE
Fliped Video Mirror Videos Front Cam

### ISSUE THREAD

**Issue by mnoman47** [natario1/CameraView#283]
- [ yes ] *I am using the latest version*
- [  yes ] *I can reproduce the bug in the demo app, and if not...*
- [  yes ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Record video from Front Cam is fliped or mirrored, how to avoid fliping video.

**Comment by suarezu** [comment]
same issue as #287 , the preview is as expected, but the video/picture taken via front camera should be flipped

**Comment by natario1** [comment]
This is intended behavior, for pictures also.
