### ISSUE TITLE
does CameraUtils.decodeBitmap take front/back camera into aacount?

### ISSUE THREAD

**Issue by suarezu** [natario1/CameraView#287]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [x] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. using the front camera to tacke picture, and CameraUtils.decodeBitmap to show what captured
2. the captured looks 180-degree horizontally flipped
3.

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
No & this is intended behavior for now. But it's easy for you to do this, take a look at StackOverflow.
You just can't use CameraUtils.decodeBitmap(), sorry.

**Comment by suarezu** [comment]
as CameraUtils.decodeBitmap() comments, it processes the orientation of the taken image; android bitmapfactory doesnt, how to combine them?
besides, even if picture can be worked around, how about video? why it is intended? is it possible to expose this parameter for user to make the choice?

**Comment by natario1** [comment]
For two reasons,
- flipping is hard and expensive in terms of performance
- it's questionable wether we should flip. If you lift your left hand, the output picture will have you lifting your left hand. And this is also the Android default.

To flip pictures you would have to add some matrix.setScale() inside decodeBitmap (look on StackOverflow). So you can just copy paste the decodeBitmap code in your app and add that line

**Comment by suarezu** [comment]
yes, I have checked the built-in camera apps on some devices at my hands, some flipped and some didnot, I really recommend leaving the choice of difficulty and expense to the user of the library :D

**Comment by digirishab** [comment]
Yes same, Please add this feature.

**Comment by Rishabh-sx** [comment]
Hi, I am still facing this issue. When I take picture/video from front camera. The output of picture & video both is getting flipped. 

I have used version - 2.0.0-beta04
