### ISSUE TITLE
onFocusStart/onFocusEnd is not called before/after automatic cotinous autoFocus

### ISSUE THREAD

**Issue by wosiu** [natario1/CameraView#291]
- [x ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

onFocusStart/onFocusEnd is only called after cameraView.startAutoFocus(x,y)* or tap if gesture is enabled and not before/after automatic contious autofocus. 
Is there a way to determine start/end of automatic continous autofocus? 
If not, is there a way to turn off continous autofocus so that I can control it manually and have information about its start and end.

My use case: I don't want to process frames which are taken during autofocus, so I need to know when it starts and ends.

*despite situation described in #292 

Expected behaviour:
1. A knob to turn on/off automatic continous autofocus
2. onFocusStart/onFocusEnd also called after automatic continous autofocus if such is turned on.
Maybe 3rd parameter in onFocusStart/onFocusEnd which would indicate the reason of autofocus (gesture / programatically via startAutoFocus / automatically due to continous autofocus turned on)

**Comment by natario1** [comment]
It would be cool but unfortunately there is no way to do it with Camera1 APIs, sorry.
About disabling the continuous feature at all, there is #107 as you said.
