### ISSUE TITLE
why do you say camera 2 integration is in things that need to be done?

### ISSUE THREAD

**Issue by fahime-ghasemi** [natario1/CameraView#296]
as you said, CameraView library is a fork of CameraKit-Android. CameraKit-Android support both camera 1 and camera 2 API. why do you say camera 2 integration is in things that need to be done?

**Comment by natario1** [comment]
CameraKit served as a base years (?) ago, but now the libs are two different things, we have no Camera2 support.

**Comment by kelingyao** [comment]
Camera2 when ready?

**Comment by natario1** [comment]
Some day! I don't see this as urgent, but if anyone wants to work on it, let's discuss.
