### ISSUE TITLE
what is the code to save the captured picture to storage

### ISSUE THREAD

**Issue by jom16antonio** [natario1/CameraView#298]
How do you save picture to a file
how to set the filename

**Comment by natario1** [comment]
Try to ask on StackOverflow, the lib will give you a jpeg byte array

**Comment by Divay-Parashar** [comment]
hey this Code works for me hope this will work for you
 cameraView.addCameraListener(new CameraListener() {
@Override
            public void onPictureTaken(byte[] jpeg) {
                super.onPictureTaken(jpeg);
                 SavePhotoTask(jpeg);
            }
        });
public void SavePhotoTask(byte [] jpeg)
{
   File imagesFolder = new File(Environment.getExternalStorageDirectory(), "msApp");
            imagesFolder.mkdirs();

            final File photo= new File(imagesFolder, "Yourimagename.jpg");
            try
            {
                FileOutputStream fos=new FileOutputStream(photo.getPath());
                fos.write(jpeg[0]);
                fos.close();
            }
          catch(Exception e)
          {
                 
           }
}

**Comment by jom16antonio** [comment]
This worked great. thanks
Hope this gets added to documentation

**Comment by ifanfaizal** [comment]
I followed 

> hey this Code works for me hope this will work for you
> cameraView.addCameraListener(new CameraListener() {
> @override
> public void onPictureTaken(byte[] jpeg) {
> super.onPictureTaken(jpeg);
> SavePhotoTask(jpeg);
> }
> });
> public void SavePhotoTask(byte [] jpeg)
> {
> File imagesFolder = new File(Environment.getExternalStorageDirectory(), "msApp");
> imagesFolder.mkdirs();
> 
> ```
>         final File photo= new File(imagesFolder, "Yourimagename.jpg");
>         try
>         {
>             FileOutputStream fos=new FileOutputStream(photo.getPath());
>             fos.write(jpeg[0]);
>             fos.close();
>         }
>       catch(Exception e)
>       {
>              
>        }
> ```
> }

I followed this, but no pictures were saved 😢 

NB: I've set permission in Manifest too

**Comment by Divay-Parashar** [comment]
Hi. Ifan, please check your app read and write storage and camera permission in your device setting and make sure these permissions are set on for storing and capturing an image. If this does not work please send me the code I'll take look into this.

**Comment by gabriel-TheCode** [comment]
THE METHOD PROVIDED IS :
```java
   @Override
        public void onPictureTaken(@NonNull PictureResult result) {
            super.onPictureTaken(result);
    
        }  
```

NOT

```java
   @Override
        public void onPictureTaken(byte[] jpeg) {
            super.onPictureTaken(result);
        }
        
```

**Comment by 4nku5h** [comment]
there is no method named     -> public void onPictureTaken(byte[] jpeg)

**Comment by 4nku5h** [comment]
cameraView.addCameraListener(new CameraListener() {
            @Override
            public void onCameraOpened(@NonNull CameraOptions options) {
                super.onCameraOpened(options);
            }

            @Override
            public void onCameraError(@NonNull CameraException exception) {
                super.onCameraError(exception);
            }

            @Override
            public void onPictureTaken(@NonNull PictureResult result) {
                Toast.makeText(getActivity(), result.getData().toString(), Toast.LENGTH_SHORT).show();
                SavePhotoTask(result.getData());

                super.onPictureTaken(result);
            }
        });

 public void SavePhotoTask(byte [] jpeg)
    {
        File imagesFolder = new File(Environment.getExternalStorageDirectory(), "msApp");
        imagesFolder.mkdirs();

        final File photo= new File(imagesFolder, "Yourimagename.jpg");
        try
        {
            FileOutputStream fos=new FileOutputStream(photo.getPath());
            fos.write(jpeg[0]);
            fos.close();
        }
        catch(Exception e)
        {

        }
    }

**Comment by Nazir02** [comment]
btn = findViewById(R.id.takePicture);
        camera = findViewById(R.id.camera);
        camera.setLifecycleOwner(this);
        camera.setFacing(Facing.FRONT);


        btn.setOnClickListener(v -> {
            camera.takePicture();
            camera.getResources();
        });
        camera.addCameraListener(new CameraListener() {
            @Override
            public void onPictureTaken(@NotNull PictureResult result) {
                // A Picture was taken!

                SavePhotoTask(result.getData());
                super.onPictureTaken(result);
            }
            // And much more
        });
    }


    public void SavePhotoTask(byte[] jpeg) {
        File imagesFolder = new File(Environment.getExternalStorageDirectory(), "msAPP");
        imagesFolder.mkdirs();

        final File photo = new File(imagesFolder, "1.jpg");
        try {
            Toast.makeText(this, jpeg.toString(), Toast.LENGTH_SHORT).show();
            FileOutputStream fos=new FileOutputStream(photo.getPath());
            fos.write(jpeg[0]);
            fos.close();
        } catch (Exception e) {
            Toast.makeText(this, "noSave", Toast.LENGTH_SHORT).show();
        }
    }




I followed this, but no pictures were saved cry

NB: I've set permission in Manifest too
