### ISSUE TITLE
onPictureTaken is called very late after calling cameraView.capturePicture();

### ISSUE THREAD

**Issue by mohitrajput987** [natario1/CameraView#303]
onPictureTaken is called very late after calling cameraView.capturePicture();
Till then, camera screen looks steady.

**Comment by Namazed** [comment]
Hi, @mohitrajput987 
Which resolution you choose for your picture?
If I right by default biggest resolution.

**Comment by mohitrajput987** [comment]
Yes, default resolution.

**Comment by Namazed** [comment]
@mohitrajput987 
I recommend you don't use default, because the biggest resolution is long processed (devices can have 4k resolution). I tested and decided that optimal resolution is FullHD(1920x1080).
The Telegram app choose this resolution too.

**Comment by fahime-ghasemi** [comment]
@Namazed I have this problem too, How can I change the default resolution? How can I create mPictureSizeSelector?

**Comment by fahime-ghasemi** [comment]
@mohitrajput987 Do you find a solution for this problem?

**Comment by Namazed** [comment]
Hi, @fahime-ghasemi 
For example: https://gist.github.com/Namazed/3bbecb8d25243a6088e578c515598a17

**Comment by Kishor-Giri** [comment]
Hello @Namazed How can i set the output picture size equal to device height and device width?

**Comment by Namazed** [comment]
Hi, @Kishor-Giri 
I answered you in your issue.

**Comment by natario1** [comment]
Thank you.
