### ISSUE TITLE
Video Quality support for 360p

### ISSUE THREAD

**Issue by jom16antonio** [natario1/CameraView#305]
Hi will there be possibility of supporting 360p video quality?

If its already available, how do we achieve this? thanks

**Comment by Namazed** [comment]
Hi, @jom16antonio 
I think you should use this:
```class VideoQuality```
```java
/**
     * Quality level corresponding to the QVGA (320x240) resolution.
     */
    MAX_QVGA(2),
```
```java
cameraView.setVideoQuality(VideoQuality.MAX_QVGA);
```

**Comment by gabriel-TheCode** [comment]
I dont see the method `cameraView.setVideoQuality(VideoQuality.MAX_QVGA);`
