### ISSUE TITLE
attempt to use a camera after disconnect() exception

### ISSUE THREAD

**Issue by fahime-ghasemi** [natario1/CameraView#306]
- [x] *I am using the latest version*
I have one activity that loads two fragments. In one of fragments I added a full screen cameraview and a button that replace the fragment with another one and add camera fragment to back stack. when I hit the back button in second fragment I return back to camera fragment but camera isn't start and I see a black screen. I checked the logcat and found there is an error that say 'attempt to use a camera after disconnect()'
In camera fragment I added these codes to start the camera.

@Override
    public void onResume() {
        super.onResume();
        mCameraView.start();
    }

    @Override
    public void onPause() {
        super.onPause();
        mCameraView.stop();
    }
    @Override
    public void onDestroy() {
        super.onDestroy();
        mCameraView.destroy();
    }

**Comment by natario1** [comment]
I think you should call mCameraView.destroy() during `onDestroyView()`.
