### ISSUE TITLE
How can i use both camera on app?

### ISSUE THREAD

**Issue by VishalChauha** [natario1/CameraView#308]
i am trying to run both camera at same time like half of the screen is from rear camera and other half is from front camera but unfortunately i got result from only rear camera, front camera shows me black screen.

Do anybody have any idea how can i do that?
I have 10.OR.E phone with android version 8.0, Nexus 5X with Android 8.1 and Oppo phone with lollipop version.

Is there any solution that i can make both camera work on all devices?

Thanks.

**Comment by agalfioni** [comment]
With new changes in release version 1.6.0 that can be possible? I also need to record at the same time from frontal and back camera.

**Comment by Namazed** [comment]
@agalfioni 
You can see all changes here:
https://github.com/natario1/CameraView/blob/v1.6.0/CHANGELOG.md

**Comment by natario1** [comment]
It's not possible, sorry.
