### ISSUE TITLE
cameraPlaySounds in xiaomi 5s plus is invalid，/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by asmysoul** [natario1/CameraView#315]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [ ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1.
2.
3.

#### Interesting logs:

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
We do our best, sometimes the sound simply can't be disabled. It is explained in docs and source code I think.
