### ISSUE TITLE
Pinch Zoom laggy

### ISSUE THREAD

**Issue by antoniovlasic** [natario1/CameraView#32]
The pinch zoom is really slow...
And thank you for helping with the last issue! :)

**Comment by natario1** [comment]
I think it is already optimized as possible. We are using google `ScaleGestureDetector` to detect pinches, and then just updating camera parameters

**Comment by droidraja** [comment]
I am also facing this there is a jerky behaviour while using zoom. Is there any way to smoothen the zoom.

**Comment by natario1** [comment]
This can be improved by filtering the updates we pass to the camera engine, e.g. just use some discrete steps instead of passing everything continuous update.
