### ISSUE TITLE
draw in preview

### ISSUE THREAD

**Issue by FBertanha** [natario1/CameraView#321]
how i can draw over a preview? i'm using Firebase ML Kit for barcode detections, its working fine on FrameProcessor callback, but i want to draw in preview the barcode's location. Here's a sample what i want [https://goo.gl/L5D83h](url)

**Comment by wosiu** [comment]
This is not CameraView related question. Search in stackoverflow. 
Keywords: layout overlay / drawable layout overlay / etc..
Basically you add ImageView/Drawable view/etc under CameraView part in xml of your layout.
