### ISSUE TITLE
requestPermissions not called in fragment

### ISSUE THREAD

**Issue by janbolat** [natario1/CameraView#322]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*

#### Detailed steps to reproduce the issue:

`onRequestPermissionsResult()` is not called if the camera is inside the fragment, because you call 
[`activity.requestPermissions()`](https://github.com/natario1/CameraView/blob/master/cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java#L1363). I need to catch it in fragment, but not activity.

#### Expected behavior:

You should call [`Fragment.requestPermissions`](https://developer.android.com/reference/android/support/v4/app/Fragment.html#requestPermissions) if it is a fragment.

As a workaround I am passing the values catched in activity to the fragment now. Is it a only solution?

Thank you.

**Comment by natario1** [comment]
Yes, this is intended behavior. We can only get the activity.

The "workaround" is simply dealing with permissions yourself (that is: don't call `start()` until you have permissions).
