### ISSUE TITLE
Is there any way to monitor the video recording?

### ISSUE THREAD

**Issue by bux-git** [natario1/CameraView#326]
Is there any way to monitor the video recording?

Because of the call to camera. start (); there is a delay in shooting when the camera starts, which results in the difference between the actual recording time and the calculation of recording time outside.

**Comment by natario1** [comment]
Nope, sorry. This has been discussed in a few issues already and we have no real solution ATM.

**Comment by dokiKit** [comment]
Is there a way to know when the recording actually start?

**Comment by natario1** [comment]
There isn't at the moment, sorry
