### ISSUE TITLE
Similar to this method:  textureView.getBitmap()

### ISSUE THREAD

**Issue by prczhb** [natario1/CameraView#329]
Similar to this method:  textureView.getBitmap()

I don't want to take a photo, I just want to get a preview of the camera.

Is there an easier way like this?  ( textureView.getBitmap())

**Comment by wosiu** [comment]
You've got frame processor when you get byte[] with frame in NV21 format AFAIR. Search in doc.
Alternatively you can invoke `cameraView.captureSnapshot()` which is faster than `capturePicture`.

**Comment by natario1** [comment]
Thanks @wosiu !
