### ISSUE TITLE
Black preview while adding custom view on camera

### ISSUE THREAD

**Issue by huseynlilkin** [natario1/CameraView#335]
I want to draw some lines and texts on the camera preview. For this, I've created a custom draw view which uses surfaceHolder and draws on a canvas and added this custom preview to the CameraView instance using camera.addView(myView). 

I can still get images from camera, and can draw lines on my view but preview is totally black, drawing happens on the black background.

- [X ] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

#### Detailed steps to reproduce the issue:

1. Create a custom view which extends SurfaceView and implements SurfaceHolder.Callback
2. Try to draw something on that view
3. Add this view to the camera using camera.addView(yourView)

#### Expected behavior:
Display drawn view on the preview 

#### Actual behavior:
Camera and drawing works normally, only camera preview is black. When preview black I can see drawn lines. 

#### Interesting logs:
There isn't any error

*You can use `CameraLogger.setLogLevel(LEVEL_VERBOSE)`
to add logs to logcat, and `CameraLogger.registerLogger()`
to handle logs yourself (e.g. export to file or a crash reporting service)
so you can collect data from your users.*

**Comment by natario1** [comment]
SurfaceView can't be used for overlays AFAIK, it creates a black hole behind. See Android docs.
