### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError  Failed to allocate a 51121164 byte allocation with 12381112 free bytes and 11MB until OOM

### ISSUE THREAD

**Issue by wider2** [natario1/CameraView#336]
quite usual error, when we are working with bitmaps
used version
    implementation 'com.otaliastudios:cameraview:1.6.0'

mistake:
com.otaliastudios.cameraview.CameraUtils.decodeBitmap (CameraUtils.java:202) 

com.otaliastudios.cameraview.CameraUtils$1.run (CameraUtils.java:105)

**Comment by natario1** [comment]
You should pass a smaller width/height to CameraUtils.
In v2 this exception is swallowed and you will get a null result.
