### ISSUE TITLE
onPictureTaken() and onVideoTaken() called multiple times

### ISSUE THREAD

**Issue by ManuMobsuccess13** [natario1/CameraView#338]
### How do I enter only one time in callback?
Hello guys, Sorry for my English 
First of all , great lib thanks.
My problem is that my onPictureTaken() and onVideoTaken() are called multiple times . 
When I'm taking a picture , it goes only 1 time in onPictureTaken(), when I take another picture it goes 2 times in a row, another picture , 3 times in a row etc ..

Do you know how it's possible , I think I did all good but I don't really know where does it come from

**Comment by ManuMobsuccess13** [comment]
It works , that was dumb ahah thank you 👍

**Comment by alexei-28** [comment]
OK
