### ISSUE TITLE
Pinch zoom flickers the camera view

### ISSUE THREAD

**Issue by Amrutha-shet** [natario1/CameraView#339]
I have used Camera View in my layout and also overridden onMesure() to handle the aspect ratio to fit my screen. 

The issue is every time I pinch zoom there is some kind of flicker.

**Comment by natario1** [comment]
Does this happen with the demo app?

**Comment by Amrutha-shet** [comment]
Nope this does not happen with demo app

**Comment by natario1** [comment]
Are you able to spot the difference? Is this due to your onMeasure implementation?

**Comment by Amrutha-shet** [comment]
Match parent is not fitting the screen due to difference in aspect ratio.

**Comment by natario1** [comment]
Match parent does exactly that, unless your device / activity is not hardware accelerated, in which case the lib unfortunately does not work well.

**Comment by Pinkal7600** [comment]
I am facing the same issue with my app with the camera view and also with the demo app. While I perform pinch to zoom, camera preview is stacking and take some time to stable preview. I have tested two different devices. Please check below Device details and attached video.

1. Device details:
Name : Nokia 6.1
OS : Android 9.0

2. Device details:
Name : Motorola One Power
OS : Android 9.0

Video link: https://drive.google.com/file/d/1o61peUf3xreqEhrvbhh0wLBAW2LVQfBd/view?usp=sharing

**Comment by Pinkal7600** [comment]
As I checked in other Android devices with OS 6.0 and 7.0 its working fine. So, I think an issue is generated in Android 9.0 only. Please check this issue.
