### ISSUE TITLE
Question: Round darken overlay

### ISSUE THREAD

**Issue by Rainer-Lang** [natario1/CameraView#35]
Is something like this https://i.stack.imgur.com/NszHG.png possible?
I need this because I want that my users make profile images - and these pictures are round in my app. So it would be great if the users are seeing exactly what they will get.

**Comment by natario1** [comment]
It is possible, but I think it goes beyond what a camera engine should provide. 

You can display an overlay in another view on top of CameraView, or in CameraView itself using `cameraView.setForeground(Drawable)`. You just need the drawable :)

**Comment by Rainer-Lang** [comment]
@natario1 Thank you very much. I'll try it.
