### ISSUE TITLE
can't install cameraview : camera.setLifecycleOwner(this)

### ISSUE THREAD

**Issue by 8991hnim** [natario1/CameraView#351]
Im doing the first few step to install cameraview. In my activity, i wrote this:
  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        CameraView camera = findViewById(R.id.camera);
        camera.setLifecycleOwner(this);
    }
But the camera.setLifecycleOwner error at (this) and it showed me error: 
setLifecycleOwner (androidx.lifecycle.LifecycleOwner) in CameraView cannot be applied to (com.camera.democamera.MainActivity)
I cant figure out, stuck for hours :( 
**Edit**
I found the solution is go to gradle.properties and add 
android.useAndroidX=true
android.enableJetifier=true
Then AppCompatActivity imported like this : import androidx.appcompat.app.AppCompatActivity;
So i must change all code in my project, is there any other way?

**Comment by natario1** [comment]
The dejetifier should take care about this? Have you tried this 

android.useAndroidX=false
android.enableJetifier=true

and refresh your project. I don't know how this works honestly.

**Comment by vivek-shindhe96** [comment]
Ok, I have no clue how it worked, but I was stumbling around with the same problem. What worked for me was, i disabled both useAndroidX and enableJetifier in the properties.gradle. 

android.useAndroidX = false;
android.enableJetifier = false;

And revamped the AppCompatActivity back to it's original import and it was working fine.

**Comment by letkan** [comment]
This setLifecycleOwner is a show stopper, just can't spend any more time with this library, sorry.

**Comment by Keheira** [comment]
you have to do the following in `gradle.properties`:

```
android.useAndroidX=false
android.enableJetifier=true
```

Fair warning that you have to manually go back and fix all your files to use the new AndroidX support lib if your project is older

**Comment by mansigoel94** [comment]
Issue still reproducible

Setting only enableJetifier to true gives error "AndroidX must be enabled when Jetifier is enabled. To resolve, set android.useAndroidX=true in your gradle.properties file." so I did. And back to square one where AppCompatactivity is imported as  'import androidx.appcompat.app.AppCompatActivity'

**Comment by milansamardzic** [comment]
If I'm not wrong, this is not a bug. It is simple to solve this problem. So, first, check your Android Studio version and update it latest (or at least above 3.2.x, mine is in a moment of writing this post 3.3.1).
If you have multiple Android Studios open, close all except one. From the top menu select **Refactor** > then choose **Migrate to AndroidX**. You will get a question to the backup project as a .zip file. Do that. Wait to update and install finish. If it is necessary clean/rebuild project and Invalidate cache and restart (from the File menu).

That should be it.

Issue is not directly relate to this library!

Happy coding!
