### ISSUE TITLE
Display landscape preview while the device is portrait and take image from the camera without cropping

### ISSUE THREAD

**Issue by ShayFB** [natario1/CameraView#359]
Hi, 
I wish to display the camera preview in landscape format (e.g. 4:3  W=4, H=3)  in a suitable view (4:3) when the device is in portrait mode.

If I print the getPictureFormats i see only 3:4 and 9:16   (not 4:3)

How can I take a picture 4:3 , show the user 4:3 in the preview **without** actually cropping the image.

When I turn the device, the view adapts and now I see it 4:3.   
I don't want to take a snapshot of the view (low quality), I wish to use the real picture of the camera.
Please advice,
Thanks

**Comment by natario1** [comment]
You can't, because that's how your sensor in your device is orientated (makes sense: it takes pictures with the same orientation of the display)

**Comment by ShayFB** [comment]
Thanks for the prompt reply!
But I still don't understand why it is not possible. when you turn the device, the camera "knows" to show the view in the right way. so why can't I do it programmatically?
Isn't it related to https://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation(int) ?

**Comment by ShayFB** [comment]
Thank you very much.
Excellent library by the way :-)

**Comment by natario1** [comment]
Thank you!
