### ISSUE TITLE
How to change the input frame size for frame processing?

### ISSUE THREAD

**Issue by junjuew** [natario1/CameraView#363]
### How do I change the size of frame received by the frame processing callback?
For frame processing, how do I change the size of the frame received by the callback function "process"? I tried setPictureSize and setVideoSize, but none of them worked. (P.S. Thank you for this awesome library!)
```
cameraView.addFrameProcessor(new FrameProcessor() {
    @Override
    public void process(Frame frame) { // how to change the size of the received frame?
        // Process...
    }
}
```

**Comment by natario1** [comment]
You can control with `setPreviewSize`, please read on the website docs about it since it has some consequences.
