### ISSUE TITLE
Date time with captured images in some images.

### ISSUE THREAD

**Issue by sandeep7644** [natario1/CameraView#365]
I am using this library to capture images and upload them to server. But in some images date  and time are printed in bottom right corner. This is happening in only some images. and the printed date and time is also not matching with server date time.I am attaching a file regarding the issue. Date printed on image is 2019/1/1 but server date is 2019/1/5.
![attend_punch_27871](https://user-images.githubusercontent.com/16118061/51162536-90934680-18bc-11e9-969c-295a4830c717.jpg)
What could be the possible cause of this. Please help.

**Comment by natario1** [comment]
I have no idea! Maybe your user are uploading from own gallery and not from CameraView.

**Comment by sandeep7644** [comment]
Uploading image from gallery is not provided in app 
User can only upload images using CameraView.

**Comment by natario1** [comment]
I don't know then, sorry! We're not writing any date

**Comment by sandeep7644** [comment]
Ok
