### ISSUE TITLE
Can you remove the sound

### ISSUE THREAD

**Issue by qiaoyhh** [natario1/CameraView#368]
Can you remove the sound

**Comment by Edeneast13** [comment]
You can use  app:cameraPlaySounds="true|false" in xml or set cameraView.setPlaySounds(false);

**Comment by qiaoyhh** [comment]
thanks but No effect

**Comment by alecio** [comment]
It seems indeed that it doesn't work for capturing the video, but for photos it gets disabled as expected. I'm trying it on Google Pixel 1 using the `cameraview:1.6.1`

**Comment by qiaoyhh** [comment]
@natario1 ok,thanks
