### ISSUE TITLE
Question regarding setPictureSize()

### ISSUE THREAD

**Issue by ShayFB** [natario1/CameraView#370]
Hi,
I have the following definition in my code:
private static final AspectRatio RATIO_3_4 = AspectRatio.of(3, 4);
SizeSelector matchRatioImage = SizeSelectors.or(
                SizeSelectors.and(SizeSelectors.aspectRatio(RATIO_3_4, 0), SizeSelectors.minArea(DEFAULT_PICTURE_SIZE), SizeSelectors.smallest()),
                SizeSelectors.and(SizeSelectors.aspectRatio(RATIO_3_4, 0), SizeSelectors.biggest()));
camera.setPictureSize(matchRatioImage);

I tried to get the first 3X4 ratio > DEFAULT_PICTURE_SIZE. The other state is a failover. 

The problem I having is that if open the camera in **landscape mode**, the actual picture size selected is 4X3 (e.g. 640X480).
However, I intended to open it differently since most devices have many 3X4 resolutions but only a few (if any) 4X3. 

In addition for some reason, I'm not encountering this behavior on all devices, I managed to reproduce it on LG G5 (which has many 3X4 and one 4X3 - 640*480)

Any advice?
Thanks a lot :-)

**Comment by natario1** [comment]
The sizes passed to the SizeSelector are intended with respect to the view.

So what's 4:3 in portrait will become 3:4 in landscape. But you can easily workaround this by using `or()` and `and()` to select what you exactly want.
