### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by SungJoKim** [natario1/CameraView#371]
### Describe the bug

- CameraView version: 2.0.0-beta2
- Reproducible in official demo app: no
- Device / Android version: *Galaxy S9, API 28*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Enable leak canary
2. CameraFragment add, remove

### Expected behavior
a memory nick occurred.

### Logs
- HandlerThread. uncaughtExceptionHandler
- Camera1.mCameraCallbacks
- CameraView$Callbacks.this$0
- CameraView.mParent
- ConstraintLayout.mParent
- ConstraintLayout

**Comment by SungJoKim** [comment]
I called cameraView.destroy() on fragment.onDestory()
maybe, memory leak is  mCameraCallbacks is not null when called cameraView.destory()

**Comment by fornewid** [comment]
me too!

**Comment by natario1** [comment]
Please read instructions [here](https://natario1.github.io/CameraView/about/getting-started.html) : use `setLifecycleOwner(viewLifecycleOwner)` in fragments.

If you still want to call the callbacks manually, `camera.destroy()` must be called `onDestroyView()`, not `onDestroy()`.

**Comment by fornewid** [comment]
Oh, I miscatched that.
I'll recheck my codes.
Thanks for rapid response. :)

**Comment by SungJoKim** [comment]
When I told you to do it, I found that the problem was solved.
thanx
but i saw leak from fragment instance variables in camera frame callback
