### ISSUE TITLE
Disable Shutter Sound 's answer is not solution !

### ISSUE THREAD

**Issue by onurcemkarakoc** [natario1/CameraView#376]
Hi 

i read https://github.com/natario1/CameraView/issues/208

I have problem like this 

I have tried  

setPlaySounds(false)

and xml --

        app:cameraAudio="off"
        app:cameraPlaySounds="false"

but problem is not unsolved.
Help about it

**Comment by natario1** [comment]
Try searching for sound in closed issues, I have answered many times
