### ISSUE TITLE
Retrieve video recording time

### ISSUE THREAD

**Issue by jeremy-jamez** [natario1/CameraView#38]
Can the recording time be retrieved and displayed in either a `TextView` or used to update a `ProgressBar`?

**Comment by natario1** [comment]
You mean while recording? This is not supported, you are responsible for your own ticking (and for ending the video).

Note also that the time parameter in `startRecordingVideo` is not guaranteed to be exact. The video will actually be some milliseconds shorter due to camera lagging.
