### ISSUE TITLE
Question: Automating Tests with a mock preview

### ISSUE THREAD

**Issue by michaels-ciandt** [natario1/CameraView#381]
Hi, is it possible to create automated tests using UIAutomator or Espresso framework with a mock in the camera preview?

I'm working with the Firebase ML Kit and I have a screen that reads the barcodes.
I would like to know if it's possible to automate this implementation?

Thanks in advance!

**Comment by natario1** [comment]
I don't think so.

The only way to hook into your frame processor would be exactly your `FrameProcessor` - you should change the image there
