### ISSUE TITLE
How to remove RECORD_AUDIO permission from Manifest

### ISSUE THREAD

**Issue by therealshabi** [natario1/CameraView#382]
I don't want to keep `<uses-permission android:name="android.permission.RECORD_AUDIO"/>` permission in my Manifest plainly due to the fact that I am not using this in my app. But the project does not build if I don't give this permission. Do you have any solution for that?
### Version used
I am using `com.otaliastudios:cameraview:2.0.0-beta02` version of cameraview

**Comment by natario1** [comment]
What do you mean that the project does not build?

**Comment by therealshabi** [comment]
I meant App is crashing without any reason

**Comment by natario1** [comment]
Try disabling audio with cameraAudio="off"

**Comment by therealshabi** [comment]
No, I actually don't want to keep this permission in the Manifest itself, because I won't be using this.
Moreover, when I'm uploading my app to play store I have to agree to a privacy policy due to this `RECORD_AUDIO` permission which in my opinion is unnecessary

**Comment by natario1** [comment]
I understand! Try doing what I said

**Comment by therealshabi** [comment]
Where do I have to put this `cameraAudio = "off"` btw?

**Comment by natario1** [comment]
In the XML definition of your CameraView, or call cameraView.setAudio(Audio.OFF) as soon as you can

**Comment by therealshabi** [comment]
It's still crashing unfortunately

**Comment by natario1** [comment]
With what stacktrace?

**Comment by dickyabd** [comment]
Hi @natario1 we have same problem where the RECORD_AUDIO permission still in the app's manifest. Note that we've already following this step : https://github.com/natario1/CameraView/issues/382#issuecomment-462054261

if you can help us to solve this, really appreciated

**Comment by dickyabd** [comment]
nevermind, we're able to remove the record_audio permission on our app.
