### ISSUE TITLE
Add overlay on camera preview

### ISSUE THREAD

**Issue by GianfrancoMS** [natario1/CameraView#387]
### How do I add overlay on camera preview?
I'm integrating Firebase Machine Learning Kit with CameraView and I need to show the results of barcode scanning. The best way to do this is to add an overlay on the camera preview. Does this library support adding an overlay on the camera preview? If so, how can I do it?
### Version used
I'm using using version 2.0.0-beta02.

**Comment by RAN3000** [comment]
#353

**Comment by natario1** [comment]
You can always put CameraView inside a FrameLayout and draw stuff over it.

For more complex behavior please follow #353
