### ISSUE TITLE
Disable recording sound beeping

### ISSUE THREAD

**Issue by milansamardzic** [natario1/CameraView#388]
### Problem to be addressed
On each recording with the camera, there is a short sound beep. Setting play sound to false doesn't work.

### Describe the solution you'd like
Fix setPlaySounds to achieve this request or new setter to controlling this feature :-).

### Additional context
I'm not sure if this bug of setPlaySounds or it should be a feature request.

P.S. This doesn't work either on 1.6.1 or 2.0.0-beta version

**Comment by natario1** [comment]
Please search for "sound" in closed issues
