### ISSUE TITLE
Camera Front facing camera preview dark on video

### ISSUE THREAD

**Issue by pankaj89** [natario1/CameraView#389]
### How do I?
When taking video from front facing camera, camera preview become darker. when i toggle facing preview become normal, I checked with device camera, device camera works perfect.

I am checking in 
Device - Pixel 1
Android Version - 9

Is there any special parameter i need to add? or it some kind of issue?  Please help.

### Version used
com.otaliastudios:cameraview:2.0.0-beta02

**Comment by BlindJerobine** [comment]
Same issue with my Pixel 2XL & some other test devices.

Preview stays light till video starts. While the video is recorded, it's extremely dark. The Output is dark, too!

Version used: 2.0.0-beta05

**Comment by TemMax** [comment]
Faced with same issue on my pixel 2

version used: 2.4.0

**Comment by TemMax** [comment]
@natario1 may be you can help with this issue or reopen?

**Comment by yaroslavkulinich** [comment]
The same with Pixel 1.

**Comment by mariuspena** [comment]
please fix this

**Comment by TemMax** [comment]
If you don't need really hq video output just use CameraView#takeVideoSnapshot. With recording from surface this trouble isn't reproduced.
