### ISSUE TITLE
onVideo method calls anonymously, when we retake the video

### ISSUE THREAD

**Issue by andiakashd** [natario1/CameraView#396]
### Describe the bug
If first time user records video for few seconds then after previewing it,
user retakes the video then onVideo method gets called after 3 seconds, hence retake never get succeed
- CameraView version: *1.6.0*
- Reproducible in official demo app: *no*
- Device / Android version: *Any*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Go to Video Camera start capturing
2. Stop capturing, preview the video then again retake the video
3. then onVideo method gets called hence retaking never succeed 

### Expected behavior
When user retakes video, onVideo method should not be called before user presses stop video or before the max duration specified!

**Comment by natario1** [comment]
I'm not planning to work on 1.6.0 anymore, sorry. Make sure to check errors in `onCameraError` and not add multiple listeners (or you will get multiple callbacks).
