### ISSUE TITLE
Not working method takePicture on SENSEIT E510

### ISSUE THREAD

**Issue by mrtsmglv** [natario1/CameraView#398]
### Describe the bug
When I try take picture from main camera nothing happens, but take picture from front camera it's work.

- CameraView version: *2.0.0-beta03*
- Reproducible in official demo app: *yes*
- Device / Android version: *SENSEIT E510/6.0*

### To Reproduce
Steps to reproduce the behavior, in the demo app:
1. Go to demo app
2. Click toggleCamera
3. Click on capture picture (R.id.capturePicture)
4. Opening preview
5. Back pressed
6. Click toggleCamera
7. Click on capture picture (R.id.capturePicture)
8. Notihng
 

### Expected behavior
Opening window of picture preview

### Screenshots
![senseite510](https://user-images.githubusercontent.com/48094478/53576158-196ff400-3b84-11e9-981e-1e3f506ef0b2.gif)

### Logs
[Here](https://gist.github.com/mrtsmglv/0fb89aa6597f836729acefea21db565e)

**Comment by natario1** [comment]
Thanks for the good report, but I don't see anything wrong in these logs. So I don't think I can help without having this specific device at hand.

See if you can spot any issue with the debugger. Feel free to reopen in that case.

**Comment by HBiSoft** [comment]
I have actually had a few users report this to me, I can't log the issue as it only happens on some devices.

@mrtsmglv can you please provide only the part of your log from where you press capture?

**Comment by mrtsmglv** [comment]
@HBiSoft Unfortunately, this device was taken away from me and I cannot get it :(

**Comment by HBiSoft** [comment]
@mrtsmglv No problem, I placed a log so I can catch it in my next release, thank you.
