### ISSUE TITLE
Frame processor is not stopping  on fragment stop

### ISSUE THREAD

**Issue by sam-tech-dev** [natario1/CameraView#408]
### Describe the bug
Frame processor is not stopping  on fragment stop. It continue to override the process method on last frame on stop the fragment.

- CameraView version: 1.6
- Reproducible in official demo app: yes
- Device / Android version: API 28

### Expected behavior
It should  stop calling process method of Fame Processor on stop the fragment of cameraview

**Comment by natario1** [comment]
I'm not planning to fix anything in v1, so if you could try with v2, that would be cool.

But this feature is unit tested and should work - after you call camera.close(), the frame processor stops.
