### ISSUE TITLE
XML 'app:cameraGridColor=' always resolves to 3

### ISSUE THREAD

**Issue by MPArnold** [natario1/CameraView#419]
### Describe the bug
V2-beta04: Default grid color is always 3 because CameraView.java line 106 reads:

int gridColor = a.getColor(R.styleable.CameraView_cameraGrid, GridLinesLayout.DEFAULT_COLOR);

Should be referring to R.styleable.CameraView_cameraGridColor?

**Comment by natario1** [comment]
Thanks for catching this! Do you want to create a PR?

**Comment by MPArnold** [comment]
nice product - just happy to help.

Regards.
Matt
