### ISSUE TITLE
camera preview height not fill parent  with samsung s8 (5.8")

### ISSUE THREAD

**Issue by hazemhamadaqa** [natario1/CameraView#424]
when i am recording with samsung s8 (5.8") the camera preview height not fill parent  as below picture 

<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:keepScreenOn="true"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

### i am used 1.6.0

![856a68d5-713f-4d79-88fa-d69e7dde6a9e](https://user-images.githubusercontent.com/9858597/55006311-37474200-4fe6-11e9-9317-7e8df86e7b4e.jpg)

**Comment by GianfrancoMS** [comment]
I also have the same issue with other Samsung models.

**Comment by GianfrancoMS** [comment]
I have the same issue on some Samsung devices.

**Comment by natario1** [comment]
It might be a problem with your layout, or maybe your app/activity is not hardware accelerated. Anyway I can't give support for v1. Please migrate to v2, and if you still have this issue, you can open a new issue and fill the bug form.
