### ISSUE TITLE
Improve CameraException error messages

### ISSUE THREAD

**Issue by huseyinWA** [natario1/CameraView#425]
### Describe the bug
My users often get this non-fatal error. It may be my mistake, I couldn't reproduce the error. I just want to inform the community.

Non-fatal Exception: com.otaliastudios.cameraview.CameraException
       at com.otaliastudios.cameraview.Camera1.onVideoResult(Camera1.java:649)
       at com.otaliastudios.cameraview.VideoRecorder.dispatchResult(VideoRecorder.java:28)
       at com.otaliastudios.cameraview.FullVideoRecorder.stop(FullVideoRecorder.java:132)
       at com.otaliastudios.cameraview.Camera1$16.run(Camera1.java:786)
       at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

- CameraView version: 2.0.0-beta03
- Reproducible in official demo app: *no*
- Device / Android version: *Many device and OS*

**Comment by natario1** [comment]
I don't know what this is about, video might fail for a number of reason, but I will improve the error messages.

**Comment by HBiSoft** [comment]
@natario1 I've had 11 users in the past week with this issue and there is no way of knowing what is causing it.

**Comment by HBiSoft** [comment]
@huseyinWA check if you can reproduce this by starting the video and stopping it shortly after starting it (within a second of starting it)?

**Comment by HBiSoft** [comment]
What I have done temporarily is to make the "stop button" not clickable - `stopRec.setClickable(false);` for 3 seconds inside a `Thread`, as shown below (I added comments to describe what I'm doing):

    startRec.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                // Make the start button invisible / gone
                startRec.setVisibility(View.GONE);

                //Make the stop button visible
                stopRec.setVisibility(View.VISIBLE);

                // I change the resource of my button to this when recording started
                stopRec.setImageResource(R.drawable.record_vid_started);

                // Then stop button cannot be clicked
                stopRec.setClickable(false);

                //Start video recording
                startCaptureVideo();

                //Set animation to stop button
                stopRec.startAnimation(anim);

                //Start thread
                theadWaitBeforeStop = new Thread() {
                    @Override
                    public void run() {
                        try {
                            synchronized (this) {

                                //Wait 3 seconds
                                wait(3000);

                                runOnUiThread(new Runnable() {
                                    @Override
                                    public void run() {
                                        // After 3 seconds I change the resource, indicating that the stop button can be pressed
                                        stopRec.setImageResource(R.drawable.record_vid_btn_stop);

                                        // I make the stop button clickable again
                                        stopRec.setClickable(true);

                                        // Then I stop the thread
                                        theadWaitBeforeStop.interrupt();

                                    }
                                });

                            }
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }

                    }
                };
                theadWaitBeforeStop.start();
            }
        });

Doing it this way, it is imposable to stop the recording for 3 seconds, in turn will prevent the issue we had. My device's camera prevents me to press the stop button for 1 second, so 3 seconds might be too much, but I will test the times.

Though this resolves the issue (I hope) we experienced, it would still be nice if this was implemented into the library.

**Comment by HBiSoft** [comment]
@natario1 I have updated my app with the above logic, forcing the video not to be stoped within the first 3 seconds of starting the recording. I still get countless logs with this issues.

I even asked one of my users, that contacted me about this issue, to try and record a video of at-least 30 second and check if the error persisted and it did.

I'm at a cross road with this and currently I get more then 10 devices a day that experience this, here is a list of  devices that experienced this the last 2 days:

Samsung Galaxy J7
Samsung Galaxy S5
Samsung Galaxy S8
Samsung Galaxy J5
Samsung Tab A 8
Kameron iTab X Plus 10
OnePlus 6
Google Pixel 2 XL
and 3 other unknown devices

I have improved the error message, as you asked, I tried fixing it by forcing the user not to stop the video for the first 3 second, can you please reply with any suggestions?

**Comment by HBiSoft** [comment]
@natario1 
I got more info from the user that's helping me debug this issue, apparently `onCameraError` is called as soon as the user starts recording, I will provide my implementation below to make sure I haven't made a mistake on my end.


I added comments to make reading/understand my logic easier:

    public class camView extends AppCompatActivity {
        CameraView cameraView;
        ImageView startRec, stopRec, flipCam;
        String filename;
        File directoryToStore;
        File filePlusName;
        ProgressBar progress_loader;
        RelativeLayout rel_startstop;
        TextView determRote;
        Thread thread, theadWaitBeforeStop;
        String showDialog;

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            getWindow().setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
            setContentView(R.layout.activity_cam_view);
            //not importatnt
            showDialog = getIntent().getStringExtra("showDialog");

            initViews();

            cameraView.setLifecycleOwner(this);
            cameraView.setMode(Mode.VIDEO);

            //SET LOG LEVEL
            CameraLogger.setLogLevel(CameraLogger.LEVEL_VERBOSE);
            CameraLogger.registerLogger(new CameraLogger.Logger() {
                @Override
                public void log(int level, @NonNull String tag, @NonNull String message, @Nullable Throwable throwable) {
                    Crashlytics.log(level, tag, message);

                }
            });

            //First make buttons invisible
            rel_startstop.setVisibility(View.INVISIBLE);
            flipCam.setVisibility(View.INVISIBLE);
            //then show them
            final Animation anim = new AlphaAnimation(0.0f, 1.0f);
            animationToShowButtons(anim);

            //FILE NAME AND PATH
            @SuppressLint("SimpleDateFormat") SimpleDateFormat formatter = new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss");
            Date now = new Date();
            filename = formatter.format(now) + ".mp4";
            directoryToStore = getBaseContext().getExternalFilesDir("CameraTemp");
            filePlusName = new File(directoryToStore, filename);

            //CHANGE CAMERA - FRONT/BACK
            flipCam.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (getApplicationContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_FRONT)) {
                        if (cameraView.getFacing() == Facing.FRONT) {
                            cameraView.setFacing(Facing.BACK);
                        } else {
                            cameraView.setFacing(Facing.FRONT);
                        }
                    } else {
                        Toast.makeText(camView.this, "Your device doesn't have a front camera..", Toast.LENGTH_SHORT).show();
                    }

                }
            });

            //START RECORDING
            if (startRec.getVisibility() == View.VISIBLE) {
                startRec.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        stopRec.setImageResource(R.drawable.record_vid_started);
                        startRec.setVisibility(View.GONE);
                        stopRec.setVisibility(View.VISIBLE);
                        stopRec.setClickable(false);

                        //START CAPTURING VIDEO
                        startCaptureVideo();
                    
                        //ANIMATION TO BUTTON WHILE RECORDING
                        stopRec.startAnimation(anim);
                        theadWaitBeforeStop = new Thread() {
                            @Override
                            public void run() {
                                try {
                                    synchronized (this) {
                                        wait(3000);

                                        runOnUiThread(new Runnable() {
                                            @Override
                                            public void run() {
                                                stopRec.setImageResource(R.drawable.record_vid_btn_stop);
                                                stopRec.setClickable(true);
                                                theadWaitBeforeStop.interrupt();

                                            }
                                        });

                                    }
                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }

                            }
                    };
                    theadWaitBeforeStop.start();
                }
                });
            }
        
            //STOP RECORDING
            if (startRec.getVisibility() == View.VISIBLE) {
                stopRec.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        stopRec.setVisibility(View.GONE);
                        startRec.setVisibility(View.VISIBLE);
                        stopRec.clearAnimation();
                        stopCaptureVideo();
                    }
                });

            }

            //CAMERA EVENT LISTENER
            cameraView.addCameraListener(new CameraListener() {
                @Override
                public void onOrientationChanged(int orientation) {
                    flipCam.setRotation(orientation);
                    startRec.setRotation(orientation);
                    stopRec.setRotation(orientation);
                    setCamButtonsRotation(orientation);
                }

                @Override
                public void onCameraOpened(@NonNull CameraOptions options) {
                    super.onCameraOpened(options);
                }

                @Override
                public void onCameraError(@NonNull CameraException exception) {
                    super.onCameraError(exception);
                    progress_loader.setVisibility(View.GONE);

                    Answers.getInstance().logCustom(new CustomEvent("onCameraError was called"));
                    Crashlytics.logException(exception);

                    showErrorDialog();
                }

                @Override
                public void onVideoTaken(@NonNull VideoResult video) {
                    super.onVideoTaken(video);
                    progress_loader.setVisibility(View.GONE);
                    Intent intent = new Intent(camView.this, TestNewPlayer.class);
                    intent.putExtra("videoUri", filePlusName);
                    intent.setData(FileProvider.getUriForFile(getApplication(), getApplication().getPackageName() + ".provider", video.getFile()));
                    intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
                    startActivity(intent);
                    finish();
                }
            });
        }

        //ANIMATION FOR SHOWING BUTTONS IN ONCREATE
        private void animationToShowButtons(Animation anim) {
            anim.setDuration(500);
            anim.setStartOffset(20);
            anim.setRepeatMode(Animation.REVERSE);
            anim.setRepeatCount(Animation.INFINITE);
            thread = new Thread() {
                @Override
                public void run() {
                    try {
                        synchronized (this) {
                            wait(2000);
                            runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    if (showDialog != null && showDialog.equals("showDialog")) {
                                        showRotationDialog();
                                    }
                                    rel_startstop.setVisibility(View.VISIBLE);
                                    flipCam.setVisibility(View.VISIBLE);
                                    thread.interrupt();

                                }
                            });

                        }
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                }
            };
            thread.start();
        }

        //INIT VIEWS
        private void initViews() {
            cameraView = findViewById(R.id.camera);
            determRote = findViewById(R.id.determRote);
            rel_startstop = findViewById(R.id.rel_startstop);
            flipCam = findViewById(R.id.flipCam);
            startRec = findViewById(R.id.startRec);
            stopRec = findViewById(R.id.stopRec);
            progress_loader = findViewById(R.id.progress_loader);
        }

        //SHOW DIALOG WHEN ONERROR IS CALLED
        private void showErrorDialog() {
            Typeface font = Typeface.createFromAsset(camView.this.getAssets(), "fonts/KelsonSansLight.otf");
            final AlertDialog.Builder builder = new AlertDialog.Builder(new ContextThemeWrapper(this, R.style.myDialog));
            @SuppressLint("InflateParams") View vieew = LayoutInflater.from(camView.this).inflate(R.layout.dialog_image_or_video, null);

            builder.setView(vieew);
            TextView title = vieew.findViewById(R.id.title);
            TextView desc = vieew.findViewById(R.id.dialog_desc);
            title.setText(getResources().getText(R.string.dialog_cam_error));
            desc.setText(getResources().getText(R.string.dialog_cam_error_desc));

            desc.setTypeface(font);

            builder.setPositiveButton("Ok", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialogInterface, int i) {
                    dialogInterface.dismiss();
                    finish();
                }
            });

            AlertDialog alert = builder.create();
            alert.show();
            alert.setCancelable(false);
            alert.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(Color.parseColor("#26c2ef"));
            alert.getButton(AlertDialog.BUTTON_POSITIVE).setTypeface(font);
        }
    
        //THIS IS NOT IMPORTANT - I SHOW A DIALOG WHEN THE USER ROTATED THE CAMERA WHILE CAPTURING
        private void showRotationDialog() {
           //removed........
        }

        //ROTATING THE BUTTONS WHEN DEVICE ROTATES
        public void setCamButtonsRotation(int orient) {
            if (orient > 269 && orient < 271) {
                flipCam.setRotation(90);
                startRec.setRotation(90);
                stopRec.setRotation(90);
            }
            if (orient > 89 && orient < 91) {
                flipCam.setRotation(270);
                startRec.setRotation(270);
                stopRec.setRotation(270);
            }
        }

        //START VIDEO RECORDING
        private void startCaptureVideo() {
            try {
                if (!cameraView.isTakingVideo()) {
                    cameraView.takeVideo(filePlusName);
                }
            } catch (Exception e) {
                Crashlytics.logException(e);
            }
        }

        //STOP VIDEO RECORDING
        private void stopCaptureVideo() {
            cameraView.stopVideo();
            progress_loader.setVisibility(View.VISIBLE);
        }

        @Override
        protected void onDestroy() {
            super.onDestroy();
            cameraView.destroy();
        }

    }
