### ISSUE TITLE
Set parameters that might have been set before the camera was opened.

### ISSUE THREAD

**Issue by Lh1600852534** [natario1/CameraView#426]
### Describe the bug
My users get this fatal error.  I couldn't reproduce the error. 
java.lang.RuntimeException: getParameters failed (empty parameters)

I found out through the log that the reason for throwing the error is to execute the getParamters method, and the location where the method is executed. At the same time, there is a line before the method is executed.
//Set parameters that might have been set before the camera was opened.
It may be the reason for the error, so I want to know why there are such comments and scenes.
Source address:
https://github.com/natario1/CameraView/blob/master/cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
Method: createCamera()

**Comment by natario1** [comment]
It's like the comment says, we set parameters that might have been set to `CameraView` before the `Camera` was opened. 

Anyway your app crashes on `getParameters` which is before. So I don't know! If you have more info, feel free to add
