### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by edgyboi** [natario1/CameraView#432]
Force close on Oppo phone when start recording

- CameraView version: 2.0.0-beta04
- Reproducible in official demo app: yes
- OPPO OS 7 and 8

### To Reproduce
1. Go to start recording
2. Force close

### Logs

android.media.MediaCodec.native_dequeueOutputBuffer (MediaCodec.java)
--
  | android.media.MediaCodec.dequeueOutputBuffer (MediaCodec.java:2583)
  | com.otaliastudios.cameraview.MediaEncoder.onPrepare (MediaEncoder.java:10)
  | com.otaliastudios.cameraview.MediaEncoder.drainOutput (MediaEncoder.java:252)
  | com.otaliastudios.cameraview.TextureMediaEncoder.onEvent (TextureMediaEncoder.java:127)
  | com.otaliastudios.cameraview.MediaEncoder$3.run (MediaEncoder.java:101)
  | android.os.Handler.handleCallback (Handler.java:836)
  | android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by natario1** [comment]
Can you post the full stack trace and logs from the device before and during the crash? You can use the demo app for this. The demo app will register Camera logs. Thanks.
