### ISSUE TITLE
Video Compressor

### ISSUE THREAD

**Issue by isfaaghyth** [natario1/CameraView#438]
Hi, any video compressor function in v2? I haven't see `setVideoQuality()` anymore since upgrade from v1 to v2. thanks.

_CameraView version: 2.0.0-beta03_

**Comment by isfaaghyth** [comment]
hi @natario1, do you have any suggest for it? thanks!

**Comment by natario1** [comment]
Hey @isfaaghyth you can take a look at the video options in documentation (video/audio bit rate, setVideoSize, ...).
