### ISSUE TITLE
Crash using focus Gesture on Tap

### ISSUE THREAD

**Issue by SharozKhalid** [natario1/CameraView#44]
same happens with focusWithMarker aswell.
This is from Android monitor:

       
                                                         [ 09-16 19:23:39.469   542: 5980 E/         ]
                                                         Camera[ERROR] aec_biz_set_debug_data_enable: 1448: aec_biz_set_debug_data_enable:1448  aec set param AEC_SET_PARAM_DEBUG_DATA_LEVEL failed with result 1
09-16 19:23:42.459 5692-5890/app.storywatch E/AndroidRuntime: FATAL EXCEPTION: CameraViewController
                                                              Process: app.storywatch, PID: 5692
                                                              java.lang.RuntimeException: setParameters failed
                                                                  at android.hardware.Camera.native_setParameters(Native Method)
                                                                  at android.hardware.Camera.setParameters(Camera.java:1984)
                                                                  at com.otaliastudios.cameraview.Camera1$1.run(Camera1.java:51)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              
                                                              
                                                              [ 09-16 19:23:42.459   542: 5981 E/         ]
                                                              Camera[ERROR] af_process_frame: 838: af_process_frame:838  af_mode=2, af_state=0, caf_state=0, status=1, trigger_caf=0
                                                              
                                                              
                                                              [ 09-16 19:23:42.459   542: 5981 E/         ]
                                                              Camera[ERROR] af_port_stats_done_callback: 1412: af_port_stats_done_callback:1412  af_port_stats_done_callback DONE AF STATS ACK back
09-16 19:23:42.749 5692-5931/app.storywatch E/libGLESv1: HWUI Protection: wrong call from hwui context F:ES1-glDeleteTexturesSEC
09-16 19:23:42.749 5692-5703/app.storywatch E/BufferQueueProducer: [SurfaceTexture-0-5692-0] queueBuffer: BufferQueue has been abandoned
09-16 19:23:42.779 5692-5703/app.storywatch E/BufferQueueProducer: [SurfaceTexture-0-5692-0] queueBuffer: BufferQueue has been abandoned
09-16 19:23:42.809 5692-5704/app.storywatch E/BufferQueueProducer: [SurfaceTexture-0-5692-0] queueBuffer: BufferQueue has been abandoned
09-16 19:23:42.849 5692-5703/app.storywatch E/BufferQueueProducer: [SurfaceTexture-0-5692-0] queueBuffer: BufferQueue has been abandoned
09-16 19:23:42.879 5692-5704/app.storywatch E/BufferQueueProducer: [SurfaceTexture-0-5692-0] queueBuffer: BufferQueue has been abandoned
09-16 19:23:43.049 5692-5692/app.storywatch E/Sensors: ~SensorEventQueue 0

PS: nice library, good work, appreciated!

**Comment by natario1** [comment]
Please follow up in #61
