### ISSUE TITLE
I get an endless loop of  permission request dialogs

### ISSUE THREAD

**Issue by mercuriy94** [natario1/CameraView#441]
Why are you using onResume lifecycle method, for request permissions? If i'm used OnResume, Then I get an endless loop of permission  request dialogs, when i deny permission.

I 'm suggesting  to use onStart lifecycle method.

I'm using 1.6.1 version.

Thank you for this lib.

**Comment by mondoktamas** [comment]
The same problem.. If I check "Do not ask me again" app freezing because request is looping

1.6.1 version
