### ISSUE TITLE
NoSuchMethodError: SurfaceTexture.releaseTexImage

### ISSUE THREAD

**Issue by p30arena** [natario1/CameraView#443]
### Describe the bug
getting java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.releaseTexImage while taking picture

- CameraView version: *2.0.0-beta04*

You said this plugin Works down to API level 15
BUT
releaseTexImage is introduced in API lvl 19
https://github.com/natario1/CameraView/blob/master/cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotPictureRecorder.java#L142

**Comment by p30arena** [comment]
I had to switch to Preview.TEXTURE

**Comment by natario1** [comment]
Thanks! Will take a look
