### ISSUE TITLE
AutoFocus Reset Delay Feature

### ISSUE THREAD

**Issue by MohamedDounnani94** [natario1/CameraView#444]
Hi, I saw that you are implementing the AutoFocus Reset Delay and I would like to know when it will be released. 
I'm currently using beta04 and this feature isn't available yet.

Thank you

**Comment by RhaegarLannister** [comment]
Can I disable autofocus after I manually focus?

**Comment by natario1** [comment]
Yeah, this was never published! Will be present in the next version.
