### ISSUE TITLE
LifecycleObserver not found

### ISSUE THREAD

**Issue by Divay-Parashar** [natario1/CameraView#448]
### How do I?
when I write this line 
 camera.setLifecycleOwner(this);
in onCreate method and compile my code this says
error: cannot access LifecycleObserver
the class file for androidx.lifecycle.LifecycleObserver not found. How do I fix this error?

### Version used
CameraView exact version.
implementation 'com.otaliastudios:cameraview:2.0.0-beta04'

**Comment by yelsane** [comment]
You're probably not using the AndroidX Support Libraries. There's a note in the [documentation](https://natario1.github.io/CameraView/about/getting-started.html):

> Can’t resolve the lifecycle owner interface? Read [below](https://natario1.github.io/CameraView/about/getting-started.html#without-support-libraries).

Either add the support library or implement it as shown in the docs without the libraries.

**Comment by natario1** [comment]
Yes, you should migrate your app to AndroidX if you want to use CameraView v2.
