### ISSUE TITLE
camera.setPlaySounds(false);无效

### ISSUE THREAD

**Issue by admasterlu** [natario1/CameraView#454]
请问关闭拍照声音怎么无效

**Comment by wosiu** [comment]
Oh come on! :D 
1) At least use google translate: "How can I turn off the camera sound?"
2) This topic was answered several times, good practice before posting a new issue: check isseus -> closed -> search
3) TLDR: For some devices it is not possible to disable shutter sound for Camera1 API. There is nothing one could make about it.
