### ISSUE TITLE
Orientation automatically changes after i take image on some devices

### ISSUE THREAD

**Issue by sandeep7644** [natario1/CameraView#455]
When i am taking images from front camera orientation automatically changes to landscape mode.
Please suggest me something to fix this issue.

**Comment by wosiu** [comment]
Maybe:
```
int rotationCompensation = Utils.getExifRotation(jpegBytes);
Matrix trans = new Matrix();
trans.setRotate(rotationCompensation);
```
and rotate bitmap decoded from `jpegBytes` using `trans` matrix

**Comment by wosiu** [comment]
Not sure if you also might need a device rotation for this. I had similar issue with back camera -> #446

**Comment by sandeep7644** [comment]
> Maybe:
> 
> ```
> int rotationCompensation = Utils.getExifRotation(jpegBytes);
> Matrix trans = new Matrix();
> trans.setRotate(rotationCompensation);
> ```
> 
> and rotate bitmap decoded from `jpegBytes` using `trans` matrix

where is Utils ??

**Comment by sandeep7644** [comment]
I used takeSnapShot instead of takePicture and the issue is resolved.
