### ISSUE TITLE
getParameters Exception when restarting Frozen Camera.

### ISSUE THREAD

**Issue by looplearn** [natario1/CameraView#463]
### Describe the bug
Unhandled Exception Thrown when starting or restarting camera when in a frozen state.

- CameraView version: 2.0.0-beta04
- Reproducible in official demo app: No (but can add logic to restart frozen camera).
- Device / Android version: Rockchip Nano PC-T4, API 27

### To Reproduce
1) Remove Application from battery optimisation list (not optimised for battery / always on)
2) Run application for very long time (happens more often if power supply or battery is low)
3) Camera becomes frozen, but can be restarted by minimising and restoring app screen)
4) Once frozen, try to close and restart camera from application code to reproduce issue.

### Expected behavior
Expected "onCameraError" Event instead of throwing unhandled exception

### Logs
Fatal Exception: java.lang.RuntimeException
getParameters failed (empty parameters)
android.hardware.Camera.native_getParameters (Camera.java)
android.hardware.Camera.getParameters (Camera.java:1968)
com.otaliastudios.cameraview.Camera1.createCamera (Camera1.java:237)
com.otaliastudios.cameraview.Camera1.onStart (Camera1.java:270)
com.otaliastudios.cameraview.CameraController$3.run (CameraController.java:189)
android.os.Handler.handleCallback (Handler.java:790)
android.os.HandlerThread.run (HandlerThread.java:65)

**Comment by natario1** [comment]
Can you provide a sample project to reproduce this easily?
