### ISSUE TITLE
手电筒的问题

### ISSUE THREAD

**Issue by chenhangyuan** [natario1/CameraView#465]
我想在页面中动态设置开关手电筒
if (b) {
            cv_view.setFlash(Flash.ON);

        }else {
            cv_view.setFlash(Flash.OFF);
        }
但是这样貌似不管用
是我哪里写错了嘛

**Comment by chenhangyuan** [comment]
知道了  把手电筒和闪光弄混了

**Comment by allenZ7** [comment]
请问你是怎么解决的，我按照 setFlash 来设置，但没效果
打不开闪光灯

**Comment by natario1** [comment]
Not sure what to say! :-)

**Comment by leielyq** [comment]
> 请问你是怎么解决的，我按照 setFlash 来设置，但没效果
> 打不开闪光灯

now Flash.TORCH
