### ISSUE TITLE
takeVideoSnapshot is not working properly in demo app in LG G7 ThinQ

### ISSUE THREAD

**Issue by sudhakar434** [natario1/CameraView#469]
### Describe the bug
In the official demo app, video snapshot is getting struck at preview screen at first frame but the audio is playing

- CameraView version: v2.0.0-beta04
- Reproducible in official demo app: yes
- Device / Android version: LG G7 ThinQ, API 26

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Go to Demo app
2. Click on settings icon and change to video mode
3. Now click on video snap shot record option 
4. After 5 sec of video record, in the preview screen video is struck at first frame but audio is playing

### Screenshots
![device-2019-05-24-171508](https://user-images.githubusercontent.com/13488085/58326547-c340e300-7e4a-11e9-963b-3e870c106074.png)
![device-2019-05-24-171525](https://user-images.githubusercontent.com/13488085/58326548-c3d97980-7e4a-11e9-880a-7ce049458cb5.png)
![device-2019-05-24-171535](https://user-images.githubusercontent.com/13488085/58326549-c3d97980-7e4a-11e9-94a0-4995bbdadd5e.png)

In the first screenshot, video is recorded and in the second screen video will get stuck at first frame but audio will be playing.
Please help me with this issue. Thank you very much for providing the wonderful camera library.

**Comment by dummy-amit** [comment]
@natario1 same error for me as well, could you please shed some light on this. thanks.

**Comment by natario1** [comment]
You can follow #449
