### ISSUE TITLE
How can I save a captured frame as an image file?

### ISSUE THREAD

**Issue by ankitivo** [natario1/CameraView#473]
Hi,
I have a very general requirement where I want to process a frame and then save that frame as an image file based on the result of my processing.

I am able to successfully process a frame byte[] but facing an issue while saving the frame to an image file.

I am using below code to convert frame byte[] into a bitmap:

`Size size = SystemServiceUtils.getWindowRealSize(context);
        Bitmap bitmap = CameraUtils.decodeBitmap(data.array(), size.getMaxOfWidthHeight(), size.getMaxOfWidthHeight(),
                new BitmapFactory.Options());`

but the converted bitmap is always null. I see the following error in the log line:

` D/skia: --- Failed to create image decoder with message 'unimplemented'`

I am using the 2.0.0-beta05 version of this library.

**Comment by natario1** [comment]
That's because frames come in `ImageFormat.NV21` (as you can see from frame.getFormat()) so they are not JPEGs. You should find some other way of visualizing, maybe using the `YuvImage` class.

**Comment by ankitivo** [comment]
Thanks, I did figure it out.
