### ISSUE TITLE
Taken photo is bigger than the preview

### ISSUE THREAD

**Issue by luangs7** [natario1/CameraView#489]
### How do I?
I'm facing a problem using a Samsung J1 device here.
But the image taken is bigger than the preview one.

This is the preview that I got:
![Screenshot_2019-07-04-11-39-28](https://user-images.githubusercontent.com/16122202/60674591-d0d98780-9e50-11e9-88c1-bfe36c13ed0d.png)

and this is the final bitmap result:

![Screenshot_2019-07-04-11-39-35](https://user-images.githubusercontent.com/16122202/60674611-d9ca5900-9e50-11e9-8dad-79071484479d.png)

I'm calling camera view with this attributes:
 <com.otaliastudios.cameraview.CameraView
            android:id="@+id/camera"
            app:cameraGesturePinch="zoom"
            app:cameraFlash="auto"
            app:cameraAutoFocusResetDelay="0"
            app:cameraGestureTap="focusWithMarker"
            android:keepScreenOn="true"
            app:cameraPreview="glSurface"
            app:cameraPictureSizeSmallest="true"
            android:adjustViewBounds="true"
            app:cameraGestureScrollHorizontal="exposureCorrection"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

I already tried to use cameraPictureSizeAspectRatio with 4:3 but no success with it.

Did I do something wrong?

### Version used
2.0.0-beta05

**Comment by natario1** [comment]
You can either use takePictureSnapshot(), OR leave one of the CameraView dimensions to wrap_content .

**Comment by luangs7** [comment]
Thanks for your help, I'll try it when I return to the office.

Looking at the images, only the height is diff between the final bitmap and the preview.
Do you think that is a aspect ratio problem because of the portrait orientation?

**Comment by natario1** [comment]
Your screen aspect ratio is not supported by your device, so since you use match_parent for both dimensions, CameraView trims the exceeding top&bottom during the preview.

**Comment by luangs7** [comment]
I get it.
Work as expect using takePictureSnapshot.
Thanks mate!
