### ISSUE TITLE
Delay when taking a video

### ISSUE THREAD

**Issue by android4canada** [natario1/CameraView#500]
Hello
I have a button with clicking listener that as soon as I click, it will do cameraview.takeVideo(videoFile);
and start countdown timer

The problem that I notice that the first ~1 second of my video is always not taken. Is this a bug?  Is it because recording a video takes time to start up? If this is the case then is there some sort of listener for that event ? My timer is 5 seconds so not a lot of time given to the user
Thanks

**Comment by natario1** [comment]
It takes time. In next version there will be onVideoRecordingStart() callback which will work better. #498
