### ISSUE TITLE
Camera provides noisy images

### ISSUE THREAD

**Issue by JirkaKrivanek** [natario1/CameraView#505]
I am using the CameraView in a very basic manner:

        getBinding().cvCamera.setLifecycleOwner(getViewLifecycleOwner());
        getBinding().cvCamera.setMode(Mode.PICTURE);
        getBinding().cvCamera.setHdr(Hdr.OFF);
        getBinding().cvCamera.setWhiteBalance(WhiteBalance.AUTO);
        getBinding().cvCamera.setAudio(Audio.OFF);
        getBinding().cvCamera.setFacing(Facing.BACK);
        getBinding().cvCamera.addCameraListener(mHandleCameraEvents);

The preview is just fine. But the final image is noisy (colour noise).

The callback is like this (btw: I know the thread inside is crazy - will punish young programmer who did it :) ):

    /**
     * Handles the camera events.
     */
    @NonNull private final CameraListener mHandleCameraEvents = new CameraListener() {
        @Override
        public void onPictureTaken(@NonNull final PictureResult picture) {
            final int www = picture.getSize().getWidth();
            final int hhh = picture.getSize().getHeight();
            if (BuildConfig.DEBUG) {
                Log.d(CaptureFaceDialogFragment.this.toString(),
                      "Rotation=" + picture.getRotation() + ", size.W=" + www + ", size.H=" + hhh);
            }
            new Thread(() -> {
                final byte[] data = picture.getData();
                Bitmap input = BitmapFactory.decodeByteArray(data, 0, data.length);
                if (input == null) {
                    input = Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888);
                }
                final Bitmap rotated = rotateImageIfNecessary(input, www < hhh ? -90 : 0);
                requireActivity().runOnUiThread(() -> getViewModel().setFullFaceImage(rotated));
            }).start();
        }
    };

**Comment by natario1** [comment]
Does this happen with the demo app? If not it might be something with your processing.
