### ISSUE TITLE
Bug: Capturing videos on Android API < 23 fails

### ISSUE THREAD

**Issue by Johnson145** [natario1/CameraView#51]
I got another issue: at least when using the Android Emulator, taking videos failes for Lollipop and older. Unfortunately, I can't test it on a real device, but maybe anybode can confirm the bug or restrict it to the Emulator?

Trying to read the created video file, it seems as if it does not contain a single frame. The file itself was created though and has write access.

![This happens in the demo app after recording (instead of playing the video)](https://user-images.githubusercontent.com/6339078/30941573-683d34c6-a3e6-11e7-91f6-6a8547c001c0.png)

[This is the full log.](https://github.com/natario1/CameraView/files/1338925/bug_sdk_22.txt)

Running my own app, I get the same problem, but the [log](https://github.com/natario1/CameraView/files/1338936/bug_sdk_22_own_device.txt) looks a little bit different. The only obviously-related error I can find is `09-27 18:51:50.900 2218-2218/com.siwalusoftware.dogscanner E/MediaRecorder: stop failed: -1007`.

**Comment by natario1** [comment]
This should never happen with a real device.

The emulator does a lot of weird stuff when emulating hardware, video recording is officially not supported, there is a small note [here](https://developer.android.com/reference/android/media/MediaRecorder.html) about MediaRecorder.

Out of curiosity, were you able to make this work with some API levels? In title you mention 23 then in the description 21.

**Comment by Johnson145** [comment]
Sounds good! 23 and up are working in the emulator just as good as on a real device. 22, 21 and so on do not work.

By the way: THANK YOU VERY MUCH FOR THIS AWESOME LIBRARY! I used to use CameraKit as well and gave up facing all the bugs. This one seems to be way more sophisticated so far. (Didn't plan to spam the issue with this, but just realized for the first time that GitHub does not have a personal message system..)

**Comment by natario1** [comment]
Yeah, that looked like a robust base to start but in the end I had to change everything.

Spamming with compliments is allowed :)
