### ISSUE TITLE
can you give support version

### ISSUE THREAD

**Issue by lisong15** [natario1/CameraView#515]
### 
My project is an old one. I can't upgrade to Androidx for the time being. Can you provide a support library for us? Because I can't shut down the photo sound, I need a support library version with Camera 2. I downloaded 1.6.1 at present, but I don't have Camera 2. Thks
###

**Comment by natario1** [comment]
Your best option would be to fork CameraView, remove AndroidX and use it in your project as a local dependency.

**Comment by lisong15** [comment]
Okay, thank you for your reply.
