### ISSUE TITLE
Getting frame size bigger than preview size in some devices

### ISSUE THREAD

**Issue by hmittal1990** [natario1/CameraView#533]
### Describe the bug

- CameraView version: *2.0.0-rc-2*
- Reproducible in official demo app: yes
- Device / Android version: *Opp f1s , vivo y69, API 22*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
3. See error

### Expected behavior
frame  size should be sames as preview size as i need to use frame for face detection
preview size is coming 720 x 960 and frame size is 1080x 1440. I am not able to match face  box coordinates that i need to match in my application
I am using camera engine -camera1, surfaceview.
Preview size- wrap_content

Please let me know either i will get same values or any method to change frame size.

### Logs
Use `CameraLogger.setLogLevel(LEVEL_VERBOSE)` to see all logs into LogCat.
Use `CameraLogger.registerLogger()` to export to file or crash reporting service.

### APK
Link to a Github repo where the bug is reproducible.

**Comment by natario1** [comment]
Can you fill all the bug info? Thanks!

**Comment by hmittal1990** [comment]
Info filled

**Comment by natario1** [comment]
What is preview size? How are you getting it?

**Comment by hmittal1990** [comment]
Preview size is the cameraview dimensions i am assuming.

**Comment by natario1** [comment]
There can be a difference between the two, but the aspect ratio is always the same (4:3 in your case). So you can just scale down or up to match the other size without distortion.

**Comment by hmittal1990** [comment]
Can you provide me any example ?

**Comment by hmittal1990** [comment]
Thanks for the information

**Comment by natario1** [comment]
Depends on what you are doing, I think you might find help asking on StackOverflow.

**Comment by hmittal1990** [comment]
I have solved it with mathematical calculation. Thanks for the great library
