### ISSUE TITLE
Frame processing from video

### ISSUE THREAD

**Issue by gbcapps** [natario1/CameraView#536]
How do you get the frames from a video? I would like to process these frames and make changes to them.

**Comment by natario1** [comment]
It's not something we support here. You can take a look at https://github.com/natario1/Transcoder for how to read and process video data.

**Comment by CameraCornet** [comment]
If this comes up as an added feature, I too am interested in this. I'm looking to do motion detection for security camera.  Thanks.

**Comment by natario1** [comment]
No, we have no plans to add video processing features to the camera library, sorry! You can take a look at the library some comments above.

**Comment by luozhanming** [comment]
垃圾
