### ISSUE TITLE
Filter after taking video snapshot

### ISSUE THREAD

**Issue by JeevanDeep** [natario1/CameraView#538]
Hi, thank you for this great library. I have one question. Is it possible to apply filters ( i have quite a few open gl filters) after the video has been made (by video snapshot)

**Comment by natario1** [comment]
If you post-process them... It doesn't matter if it was a snapshot or not.

You can start from https://github.com/natario1/Transcoder . It does not support filters, but is a good starting point.

If you have good quality filters, feel free to send a PR here 🙂
