### ISSUE TITLE
Very high size of output file

### ISSUE THREAD

**Issue by JeevanDeep** [natario1/CameraView#540]
Hi, I am using this library for making snapshot videos. A 3-minute video has a size of 99mb. Is there any way to reduce this size, perhaps some settings? I tried reducing snapshotmaxwith and height but that made video pixelated. Thank you for this wonderful library.

**Comment by natario1** [comment]
There are many, the most important being probably `videoBitRate`. A combination of `videoBitRate`, `snapshotMaxWidth`, `snaposhotMaxHeight`, `audio=mono` might work.

Or you can post-process the video using https://github.com/natario1/Transcoder where you can also change the video frame rate.
