### ISSUE TITLE
toggleFacing() while takings video

### ISSUE THREAD

**Issue by akokulyuk** [natario1/CameraView#543]
Hi, guys is it possible to switch facing without stopping recording?
Now if i toogleFacing() I just get video only from 1 facing, rest of the video is not available

### Version used
v. 2.1.0

**Comment by natario1** [comment]
No, sorry!

**Comment by JeevanDeep** [comment]
Hi, is it not possible to do even in snapshot mode?

**Comment by natario1** [comment]
If you fork the project and change a few things you can make it work for video snapshots.

But we don't support this officially because changing the `Facing` value can change the view size, change the preview stream size and aspect ratio, and cause issues in the output video.

**Comment by JeevanDeep** [comment]
@natario1 Can you guide me towards this approach? I forked the project and found that you restart the camera when switching the facing. Do i have to change something in stop and start function?

**Comment by natario1** [comment]
@JeevanDeep it's not an easy task, I can't really write it in a comment... and I have never tried to do so. You should make sure the video recorder is not stopped, and the preview stream size stays consistent or you account for changes in it.

**Comment by denizsubasi** [comment]
is there any development about this feature ?

**Comment by BhavyaRattan** [comment]
@natario1 do we support this behaviour now, I wanted to add same functionality in my app?
