### ISSUE TITLE
Unable to view/play the recorded video.

### ISSUE THREAD

**Issue by vishnusp** [natario1/CameraView#553]
Unable to view/play the recorded video using `CameraView.takeVideoSnapshotFile file)`. The file is created but it doesn't play. Might be a problem when the maxDuration is set as 0? 
But `CameraView.takeVideoSnapshot(File file, int durationMillis)` works fine.

- CameraView version: 2.0.0
- Device / Android version: Moto G4 Plus with Android 7.0

**Comment by natario1** [comment]
This is fixed by #551 .
