### ISSUE TITLE
E/Frame: Frame is dead! time: -1 lastTime: 1565808924463

### ISSUE THREAD

**Issue by wiztensai** [natario1/CameraView#554]
### Describe the bug
When i use frame processor in ML Kit Face detection.. in long time, always frame is dead.. is there a listener when frame is dead?

- CameraView version: *2.0.0-rc2r*
- Reproducible in official demo app: *yes/no* (i dont understand this)
- Device / Android version: *Redmi note 4, Nougat*

### Expected behavior
- I want a listener when frame is dead
- i want the frame not dead. because, my tracking in ml kit is stoping for about 5 second and then works again.

### Logs
E/Frame: Frame is dead! time: -1 lastTime: 1565811012759

W/CameraCallbacks: dispatchFrame: Error during processor implementation. Can happen when camera is closed while processors are running. java.lang.RuntimeException: You should not access a released frame. If this frame was passed to a FrameProcessor, you can only use its contents synchronously,for the duration of the process() method.

**Comment by natario1** [comment]
Can you fill the bug information, including logs from the demo app and your `FrameProcessor` code? Thanks!
