### ISSUE TITLE
Cannot take picture after focus

### ISSUE THREAD

**Issue by PhungVanHoa** [natario1/CameraView#555]
- CameraView version: 2.1.0
- Reproducible in official demo app: yes
- Device / Android version: Galaxy Note 9, API 28

After focus by touch (**in picture mode**), I call takePicture() to take picture from main camera but nothing happens. onPictureTaken() no longer dispatched.

**Expected behavior**
onPictureTaken() should be dispatched after calling takePicture().

**Comment by natario1** [comment]
Can you fill the bug report information, including logs from the demo app? Thanks!
