### ISSUE TITLE
How to get a medium size of video

### ISSUE THREAD

**Issue by gabriel-TheCode** [natario1/CameraView#556]
### How do I?
I try to record a video with cameraview but I would like it to be between 4 and 6 MB, but the method "cameraVideoSizeSmallest" returns a video of 600kb but unusable because too blurry for facial recognition and the method "cameraVideoSizeSmallest" returns a nice video but too heavy (11Mo)

### Version used
2.0.0-beta04

**Comment by natario1** [comment]
You can use `setVideoSize()` and choose a size that you like.

**Comment by gabriel-TheCode** [comment]
I think that this method stops the recorder when the desired size is reached, no matter the time of the video.
I want to record a video of 5 seconds with size between 4 and 6 MB, with this method it is possible?

**Comment by luangs7** [comment]
Same question here

**Comment by luangs7** [comment]
any answer about it?

**Comment by gabriel-TheCode** [comment]
Nothing new ...

**Comment by gabriel-TheCode** [comment]
I found an alternative by defining the bitRate of my video as I liked according to the resolution I wanted with the method `app:cameraVideoBitRate="@integer/video_bit_rate"`.

 So for a 360p video I set 400kbps. And It works fine !

**Comment by indracs97** [comment]
Set max and min bounds to same
app:cameraVideoSizeMinHeight="1920"
app:cameraVideoSizeMinWidth="1080"
app:cameraVideoSizeMaxWidth="1080"
app:cameraVideoSizeMaxHeight="1920"
