### ISSUE TITLE
Layout Editor freezes "Waiting for build to finish" after upgrading library to version 2.1.0

### ISSUE THREAD

**Issue by dssob** [natario1/CameraView#557]
### Describe the bug
Hello, I was using version 1.6.1 and it was working fine but after upgrading the library to version 2.1.0, when I open an XML layout that contains CameraView, Android Studio's layout editor change state to "Waiting for the build to finish" for all projects on mine PC. The only thing can help is Invalidate cache and restart or restart

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
Open activity_main.xml with CameraView
You will see the text "Waiting for build to finish"

**Comment by iRYO400** [comment]
#542 check it out =)
