### ISSUE TITLE
can version1.x use live filter?

### ISSUE THREAD

**Issue by ruidge** [natario1/CameraView#558]
### How do I?
We has a new function is take photos, and use version 1.6.1 to develop ,it works well. But we need a live filter feature which is supported after version 2.0 , and We need to update gradle version and migration to androidx first which is a huge work (because we have a lot partner lib and we dont know the migration may cause the function error or not) .so we may migration lately not now.

my question is what can I do to use live filter ?  Im thinking to copy version 1.6.1 and add live filter or copy version 2.1.0 and change code to support our project . 

what is your suggestion.

### Version used
1.6.1

**Comment by natario1** [comment]
No, sorry! You should update your project.
