### ISSUE TITLE
How can i get high Quality Picture? 

### ISSUE THREAD

**Issue by sunnyj0613** [natario1/CameraView#561]
Cameraview Ver 2.1.0 

I want to get high quality picture. 
But i don't know how can i get. 

I just tested using demo. and takePicture() not takePicturSnapshot().

I read docs that takePicture() gets hight Quality Picture and takePictureSanpshot() gets low quality. 

But, Although i used takePicture(), but the result is not high Qulity. 

i will show the sample image. Before take picture, the screen looks good high qulity, but after Taking picture the preview activity show low quality less than before take picture. 

is it possible get to more hight quality picture ?
if that is possible, can you know me?

Thank you ! 

![cameraview_before](https://user-images.githubusercontent.com/29723576/63406697-9ab68e00-c425-11e9-9128-488f82b318eb.jpg)
![cameraview_after](https://user-images.githubusercontent.com/29723576/63406700-9be7bb00-c425-11e9-9cef-aa4f353f8e40.jpg)

**Comment by natario1** [comment]
The demo app resizes the image to 1000 pixels to avoid `OutOfMemory` errors, but your real image should be OK!

**Comment by sunnyj0613** [comment]
> The demo app resizes the image to 1000 pixels to avoid `OutOfMemory` errors, but your real image should be OK!

That's work! Thank you so much!!
