### ISSUE TITLE
Getting crashed after taking image

### ISSUE THREAD

**Issue by hamzamon** [natario1/CameraView#566]
Hello, I have implemented the library and tested but getting crashed after taking image.....
but image is saving to the preferred destination and not works sizes

Code:

camera = (CameraView) view.findViewById(R.id.camera);
camera.setLifecycleOwner(getViewLifecycleOwner());

file = new File(Environment.getExternalStorageDirectory()+"/"+ UUID.randomUUID().toString()+".jpg");

camera.setMode(Mode.PICTURE);

SizeSelector width = SizeSelectors.maxWidth(480);
SizeSelector height = SizeSelectors.maxHeight(320);
SizeSelector dimensions = SizeSelectors.and(width, height); // Matches sizes bigger than 1000x2000.
SizeSelector ratio = SizeSelectors.aspectRatio(AspectRatio.of(3, 2), 0); // Matches 1:1 sizes.

SizeSelector result = SizeSelectors.or(
SizeSelectors.and(ratio, dimensions), // Try to match both constraints
ratio, // If none is found, at least try to match the aspect ratio
SizeSelectors.biggest() // If none is found, take the biggest
);
camera.setPictureSize(result);

camera.addCameraListener(new CameraListener() {
@Override
public void onPictureTaken(PictureResult result) {

result.toFile(file,callback);

// Access the raw data if needed.
byte[] data = result.getData();
CameraUtils.writeToFile(data, file, callback);
callback = new FileCallback() {
@Override
public void onFileReady(@Nullable File file) {

}
};

}

Error when crashing:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.otaliastudios.cameraview.FileCallback.onFileReady(java.io.File)' on a null object reference
at com.otaliastudios.cameraview.CameraUtils$1$1.run(CameraUtils.java:121)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6806)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

PLZ HELP ME

**Comment by Cutta** [comment]
is there any solution?
