### ISSUE TITLE
Focus Marker not visible on tap

### ISSUE THREAD

**Issue by sid-udawat** [natario1/CameraView#57]
Enabling single tap gesture to perform "Focus with marker" -  Marker is not visible. Just realised that even the grid marker is not visible.

I spent few hour and found the issue. If you can grant me access to push I can create a PR.

**Comment by natario1** [comment]
@sid-udawat feel free to open a PR! where's the issue?

**Comment by Johnson145** [comment]
@sid-udawat can you fork this repository and create a pull request from the fork? Focus marker is missing in my case, too.
