### ISSUE TITLE
After zooming autofocus stops working

### ISSUE THREAD

**Issue by ozzeusz** [natario1/CameraView#570]
### Describe the bug
When pinching to zoom in auto focus stops working. Taping on screen changes exposition only.
- CameraView version: *2.0.0*
- Reproducible in official demo app: *yes*
- Device / Android version: *Oneplus 6, API 29*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Go to demo app,
2. Zoom in by pinching,
3. Try to focus camera by tapping on screen

### Expected behavior
Camera should focus on clicked object.

**Comment by natario1** [comment]
With Camera1 or Camera2 engine?

**Comment by ozzeusz** [comment]
Camera2 only
