### ISSUE TITLE
Why do I take a picture with my front camera and then display the photo in reverse? Is there any solution?

### ISSUE THREAD

**Issue by 1334075863** [natario1/CameraView#571]
Why do I take pictures with a potential camera and then display the photos in reverse? Is there any solution?

**Comment by najTim** [comment]
Well, it`s kinda how camera works. You can flip your image with matrix.postScale(-1, 1, cx, cy); and make new bitmap to show when from front camera.

**Comment by natario1** [comment]
Yes! This was discussed many times in closed issues.
