### ISSUE TITLE
setPictureSize can't be changed

### ISSUE THREAD

**Issue by umitemre** [natario1/CameraView#575]
Hello,

I don't know why but setPictureSize is not changeable once camera is open. This should be fixed in future versions.

**Comment by natario1** [comment]
I will consider this! For now you should change the picture size, then call close(), then call open().

**Comment by umitemre** [comment]
> I will consider this! For now you should change the picture size, then call close(), then call open().

While you are considering, can you also consider making onCameraReady event too? It can inform when camera is ready to open or ready to spit out previews and can be last event call before onCameraOpened
