### ISSUE TITLE
WARNING: API 'variant.getJavaCompile()' 

### ISSUE THREAD

**Issue by unengchen** [natario1/CameraView#577]
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: cameraview

**Comment by natario1** [comment]
You must be using a newer gradle version than this project does. When this warning appears in this project, we'll fix it.

**Comment by Johnson145** [comment]
@unengchen @natario1 

[Here](https://github.com/Johnson145/CameraView/commit/7a412ab11f6ebbae859b930e3f080542227a83ff) is a fix for this error.

(Not raising a PR, because my fork has diverged too much).
