### ISSUE TITLE
How to focus on an area rather than a point?

### ISSUE THREAD

**Issue by shedeed1** [natario1/CameraView#579]
### How do I?
Ok so I've been trying to request focus before I take a specific picture because my application requires taking pictures of highest detail possible. Here is what I do:

`camera.startAutoFocus((camera.getX() + camera.getWidth()) / 2, (camera.getY() + camera.getHeight()) / 2);`

Then on its callback I take my picture:

```
public void onAutoFocusEnd(boolean successful, @NonNull PointF point) {
                if (successful)
                    camera.takePicture();
}
```

The problem with this approach that it focuses on a single point and (sometimes) blurs out other areas so I lose a lot of detail in the picture.

My question is: is there an approach to focus on the whole picture before I take it? Or focus on a certain rectangle in the picture?

Thank you for your hard work in this library, it's really one of the best libraries I have ever used on Android in my 2 years of development.

### Version used
2.2.0

**Comment by natario1** [comment]
Thanks! 

I'm not sure about 2.2.0, but the current master branch already does this for you. It will be available in the next version.

About focusing to a rectangle you might want to add this idea to #487, maybe one day we'll support this.

**Comment by shedeed1** [comment]
Oh ok. Waiting for the next release then! Thanks!
