### ISSUE TITLE
Focus Fixed

### ISSUE THREAD

**Issue by ozzeusz** [natario1/CameraView#583]
### How do I?
Is there a way to fix focus for example in the most macro state possible?

### Version used
CameraView 2.2.0

**Comment by natario1** [comment]
We're not planning to do this anytime soon but you can subclass `Camera2Engine` and override the focus methods and apply the focus that you like there. This requires you to dig into the source code but it is possible.

Quick steps: 

- subclass `CameraView` 
- override `CameraView.instantiateCameraEngine()` 
- there, return a subclass of `Camera2Engine`
- in your `Camera2Engine`, override any protected methods as you wish
