### ISSUE TITLE
How to set fixed size of video recording?

### ISSUE THREAD

**Issue by himanshuagarwal77225** [natario1/CameraView#586]
### How do I record video in specific sizes?
I want to record video or snapshot video in specific dimensions of 640X360 for all devices.
I have tried using 

`cameraView.setSnapshotMaxWidth(640);
cameraView.setSnapshotMaxHeight(360);`

also 
` app:cameraVideoSizeMinWidth="100"
    app:cameraVideoSizeMinHeight="100"
    app:cameraVideoSizeMaxWidth="640"
    app:cameraVideoSizeMaxHeight="360"`

Still if I check the output size `VideoResult.getSize()` it shows the size of device resolution.

### Version used
`implementation 'com.otaliastudios:cameraview:2.2.0'`

**Comment by natario1** [comment]
Using `takeVideoSnapshot()` and using as you said:

```java
cameraView.setSnapshotMaxWidth(640); 
cameraView.setSnapshotMaxHeight(360);
```

For exact results you should also ensure that CameraView has the same aspect ratio (640:360). I think `ConstraintLayout` lets you select the child view aspect ratio.
