### ISSUE TITLE
Flash or Filter not support at same time?

### ISSUE THREAD

**Issue by ruidge** [natario1/CameraView#599]
### How do I?
If I want to take picture with Flash Api , I use takePicture();
If I want to use live filter capture ,I Use takePictureSnapshot();
how to support Flash or Filter at same time??

### Version used
2.1.0

**Comment by ruidge** [comment]
or can I turn flash on when takePictureSnapshot and close it in onPictureTaken programly

**Comment by natario1** [comment]
In version 2.3.0, you can simply set `app:cameraPictureSnapshotMetering="true"` so that picture snapshots will perform 3A metering and quality improvements including Flash support.

**Comment by ruidge** [comment]
seems not work only setPictureSnapshotMetering(true);
