### ISSUE TITLE
Samsung S10e dark preview

### ISSUE THREAD

**Issue by pro2on** [natario1/CameraView#603]
### How do I?
Was found a device-specific issue. At the moment only on Samsung S10e camera preview is really dark. Please advise what can be done in this situation. 

### Version used
2.2.0

**Comment by natario1** [comment]
I have no idea! :-) I do not own this device so there's nothing I can really do. I have never encountered this issue before. Feel free to add info if you find any, but I'm unlikely to find a solution.

**Comment by pro2on** [comment]
Ok, will try to play with settings and provide more detailed info
