### ISSUE TITLE
Overlay is offset when frame size is different from overlay view size

### ISSUE THREAD

**Issue by tyczj** [natario1/CameraView#604]
I am trying to integrate Firebase barcode scanning with showing an overlay on the preview. When I try to show the bounding box overlay returned from the firebase processor the bounding box is offset from the actual position of the image (depending on the device it could be offset above or below the actual position on image).

From what I can tell the `frame.size` returns the size of the camera image which is different from the overlay view size and I think that may be what causing the issue but how do I fix it?

I use the frame information from `processFrame` to create the meta data and the image

```
val metadata = FirebaseVisionImageMetadata.Builder()
                    .setWidth(frame.size.width)
                    .setHeight(frame.size.height)
                    .setFormat(FirebaseVisionImageMetadata.IMAGE_FORMAT_NV21)
                    .setRotation(getRotation(frame.rotation))
                    .build()

val image = FirebaseVisionImage.fromByteArray(frame.data, metadata)
```

If I use the overlay with/height the barcode never gets detected

**Comment by 0xsilver-bullet** [comment]
Hello !
did you find any solution to this problem ?
