### ISSUE TITLE
Support Overlay for TakeVideo Method

### ISSUE THREAD

**Issue by lucazin** [natario1/CameraView#612]
### How do I?

natario1 my frontal camera not work anyway with snapshot mode..i dont know why my friend..
in demo or in my app.. not work .. and i need this lib too much ..congrats for the work.. 
i will talk with my partner for we donate too, because i know the hard work you had

But this problem with record a video with front camera...drives me crazy man.. i canf figure out.
because is not a normal exception..

So its possible the takevideo method have overlay support?

### Version used
2.3.0

**Comment by natario1** [comment]
No, sorry! It can only work with takeVideoSnapshot(), we should improve that one instead.
