### ISSUE TITLE
Robolectric tests fail since cameraview 2.0.0 version

### ISSUE THREAD

**Issue by sendgerson** [natario1/CameraView#616]
We were using 2.0.0-beta05 version of CameraView and I need to upgrade to 2.2.0 version. With this change, I noticed that from version 2.0.0 the robolectric tests no longer work.

Here is my build activity test code snippet:

    `Robolectric.buildActivity(ScanActivity::class.java).create().start().resume().get()`

My activity xml code snippet:
```
<com.otaliastudios.cameraview.CameraView
    android:id="@+id/camera"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:adjustViewBounds="true"
    app:cameraFacing="back"
    app:cameraFlash="off"
    app:cameraAudio="off"
    app:cameraHdr="on" />
```

I tried to analyze changes made in CameraView code but I got no conclusion about the problem.
Do you have any suggestions on how to solve this problem in my test or we have a bug in CameraView?

**Comment by natario1** [comment]
I have no idea! I have not used Robolectric recently.
