### ISSUE TITLE
camera preview is upside down when switch to reverse landscape mode.

### ISSUE THREAD

**Issue by SachinCTI** [natario1/CameraView#623]
If we enable the device rotation, and rotate our device to landscape to 180 landscape, the preview we get is upside down.

**Comment by natario1** [comment]
@SachinCTI can you fill the bug information? Thanks.

**Comment by SachinCTI** [comment]
**Describe the bug**
CameraView version: 2.2.0
Camera engine used: *camera2
Reproducible in official demo app: no
Device / Android version: xiaomi 6 pro pro, API 28

step1: Enable the auto rotation of device.
step2: Open the app in landscape mode. Preview we get is fine.
step3: Now flip the device to landscape to reverse landscape. (180 degree)
step4: Then the preview we get is upside down. 

![Screenshot_2019-10-16-16-59-30-188_com otaliastudios cameraview demo](https://user-images.githubusercontent.com/51712355/66915394-8d3d0f00-f036-11e9-99a4-f1e1833b9c3c.png)
![Screenshot_2019-10-16-16-59-51-314_com otaliastudios cameraview demo](https://user-images.githubusercontent.com/51712355/66915395-8d3d0f00-f036-11e9-8123-15f393a58b35.png)
