### ISSUE TITLE
Can't see camera view  

### ISSUE THREAD

**Issue by 23nJay** [natario1/CameraView#625]
### Add library into build.gradle(Module:app)
implementation 'com.otaliastudios:cameraview:2.3.0'

### Add some permission at meanifeast.xml 
<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.Camera" />

### Issue
But still camera view not see only black color layer visible

Look attached screen shot 
![Screenshot_20191007-192409](https://user-images.githubusercontent.com/51122535/66318602-431ea400-e939-11e9-92a3-ec227d192a40.jpg)

Thanks.

**Comment by natario1** [comment]
Please take a look at the sample app or read the official documentation on how to get started.
