### ISSUE TITLE
Camera view does not fill the screen

### ISSUE THREAD

**Issue by Isquierdo** [natario1/CameraView#63]
I'm having some problems with the CameraView size, in some devices it does not fill all the screen, showing the background sides or bottom/top depending on the device.

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/camera_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentBottom="true"
            android:layout_alignParentEnd="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentRight="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:keepScreenOn="true"
            app:cameraSessionType="video" />
    </RelativeLayout>
```

The problem x working in some devices (S6 Edge) 
<img src="https://user-images.githubusercontent.com/15673911/31456614-b4e2761a-ae90-11e7-866b-7bbccb8853e3.png" width="250"> <img src="https://user-images.githubusercontent.com/15673911/31456975-c09a8596-ae91-11e7-9958-9de910fe3679.png" width="250">

**Comment by natario1** [comment]
Would this happen without RelativeLayout? Are you doing anything strange?

**Comment by Isquierdo** [comment]
@natario1 I found the problem in my project Manifest, the hardwareAccelerated was "false".
Just changed to "true" and now it's working fine.

**Comment by softmarshmallow** [comment]
why would this happen?
