### ISSUE TITLE
Preview becomes black and stucks in Note5 Android 7.0 in Demo app

### ISSUE THREAD

**Issue by usmanrana07** [natario1/CameraView#631]
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.3.0*
- Camera engine used: *both*
- Reproducible in official demo app: *yes*
- Device / Android version: *Note 5 API 24*

Steps to reproduce the behavior, possibly in the demo app:
1. Go to Settings
2. Choose Preview Surface 'gl surface'
3. Preview will become black and stucked 

It is working fine (but rendering is slow) in Huawei Y9 2019 Android Api 28. But in Note 5 it isn't working at all in gl surface mode.

**Comment by natario1** [comment]
Can you fill the bug report information? Thanks.

**Comment by usmanrana07** [comment]
It was misbehaving that day but didn't face that issue later on and in other devices. May be device was low at performance at that time.
