### ISSUE TITLE
How to save real time filter into image file?

### ISSUE THREAD

**Issue by ductranit** [natario1/CameraView#635]
### How do I?
I follow [this document](https://natario1.github.io/CameraView/docs/filters.html) to apply filter into the preview and it works well. Then I want to save the file with filter result in preview, but seems the `cameraView.takePicture()` doesn't support for it, I don't see any filter in the image result.
So my question is how to save the preview filter into the image?

### Version used
2.3.0

Thanks!

**Comment by ductranit** [comment]
It works with `takePictureSnapshot()`

**Comment by this-mayuresh** [comment]
just stumbled upon this, have the same issue, can anyone help? I want the filters to be applied using cameraView.takePicture(), using snapshot looses a lot of quality
