### ISSUE TITLE
Calling 'takeVideo' right after switching mode doesn't record video

### ISSUE THREAD

**Issue by usmanrana07** [natario1/CameraView#636]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.3.0*
- Camera engine used: *both*
- Reproducible in official demo app: *yes (but code needs some change)*
- Device / Android version: *All devices*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. set  Mode=PICTURE before calling 'takePicture' on click on a button or set  Mode=VIDEO before calling 'takeVideo' on long click on a button.
2. It will fail to record video or capture image in first try because camera closes and restarts when mode is changed. As recording method is called in very next line after changing the mode. So, it might not be ready and skips the recording and no action is done. 

### Expected behavior
There shouldn't be need of switching mode at our end each time before calling 'takePicture' or 'takeVideo' because if we're calling 'takeVideo' that means mode should be video and if it isn't that already then change it  (May be there is some concern behind it that I couldn't understand). Besides that it shouldn't fail recording when we setMode and call takePicture/takeVideo without giving  a delay.

**Comment by natario1** [comment]
I believe this should work now.

**Comment by BhavyaRattan** [comment]
@natario1 I am facing the same issue with library version "2.6.2" can you guide me in the right direction?
