### ISSUE TITLE
Don't open the camera defualt

### ISSUE THREAD

**Issue by yangwuan55** [natario1/CameraView#638]
I want keep the camera close at start activity,and it open when I click some button.
How can I do this?
Thanks very!!!

**Comment by usmanrana07** [comment]
Just don't attach lifecycle of activity 'setLifecycleOwner' in your onCreate method, but set it onCreate of the button and call camerView.open() method then. As if lifecycle is attached then CameraView auto starts camera in onResume state.

**Comment by yangwuan55** [comment]
Thank u very much! @usmanrana07
