### ISSUE TITLE
Post-processing - apply filters to file or bitmap

### ISSUE THREAD

**Issue by ductranit** [natario1/CameraView#643]
I'm going create a camera app that can have multiple filters. After users take a picture (or a snaphot when using filter), they can change result with other filters from the original file (Post-processing)
I'd like to apply the same Filter algorithm for the file or bitmap just like the preview.
Is it possible?

**Comment by natario1** [comment]
It is possible to post-process using `Filter`s if you have GLES experience. However this is out of the scope for this library, sorry!
