### ISSUE TITLE
TAP to FOCUS

### ISSUE THREAD

**Issue by SayantanBanerjee16** [natario1/CameraView#644]
### Problem to be addressed
Can anybody give me an idea of how to apply tap in focus?

### Describe the solution you'd like
The portion in the camera view user press a tap, focus center shifts to there.

### Additional context
It can be found in any inbuilt phone camera.

**Comment by ductranit** [comment]
You should read the document: https://natario1.github.io/CameraView/docs/gestures.html
`cameraView.mapGesture(Gesture.TAP, GestureAction.AUTO_FOCUS); // Tap to focus!`

**Comment by SayantanBanerjee16** [comment]
Thanks for the link.
