### ISSUE TITLE
Urhosharp freezes/crashes after repeated display in content page - UrhoSharp FormsSample

### ISSUE THREAD

**Issue by dhsxdd1** [natario1/CameraView#657]
I'm using UrhoSharp 1.9.67 with origin sample FormsSample (with charts). I'm testing it on Samsung SM-T800.
If I click on button "LAUNCH SAMPLE" then on "back" button and again "LAUNCH SAMPLE" then on "back" button repeatedly five or ten times then the application crashes. It shows in log "eglSwapBuffersWithDamageKHR" and then it freezes. I have the same problem in my application. I have only used origin example.

log from Android Device Monitor
10-22 05:19:43.637: E/TinyUCM(3776): Failed to get AIF2 digital mute
10-22 05:19:43.637: E/TinyUCM(3776): Failed to get AIF2 digital mute
10-22 05:19:45.782: E/libEGL(4887): call to OpenGL ES API with no current context (logged once per thread)
10-22 05:19:47.582: E/Urho3D(4887): Could not initialize audio output
10-22 05:19:50.017: E/libEGL(4887): call to OpenGL ES API with no current context (logged once per thread)
10-22 05:19:51.317: E/Urho3D(4887): Could not initialize audio output
10-22 05:19:53.032: E/libEGL(4887): call to OpenGL ES API with no current context (logged once per thread)
10-22 05:19:54.322: E/Urho3D(4887): Could not initialize audio output
10-22 05:19:55.677: E/libEGL(4887): call to OpenGL ES API with no current context (logged once per thread)
10-22 05:19:57.042: E/Urho3D(4887): Could not initialize audio output
10-22 05:19:58.587: E/Watchdog(3952): !@Sync 832 [10-22 05:19:58.592]
10-22 05:19:58.997: E/libEGL(4887): call to OpenGL ES API with no current context (logged once per thread)
10-22 05:20:01.362: E/Urho3D(4887): Could not initialize audio output
10-22 05:20:02.967: E/libEGL(4887): **eglSwapBuffersWithDamageKHR:1392 error 300d** (EGL_BAD_SURFACE)
10-22 05:20:03.067: E/libEGL(4887): eglSwapBuffersWithDamageKHR:1392 error 300d (EGL_BAD_SURFACE)
10-22 05:20:03.172: E/BufferQueueProducer(2230): [SurfaceView] cancelBuffer: BufferQueue has been abandoned
10-22 05:20:04.132: E/Urho3D(4887): Could not initialize audio output

This bug can be reproduce.
Thanks
Dhsx

**Comment by natario1** [comment]
Posted on the wrong browser tab?
