### ISSUE TITLE
How store Video with filters?

### ISSUE THREAD

**Issue by saadbzu** [natario1/CameraView#666]
I user your filter class to apply filters and it work correctly in camera preview. But when i record the video after recording the filter remove , video still in its original condition. Please help how i store video with filter

**Comment by natario1** [comment]
You should record the video using `takeVideoSnapshot` instead of `takeVideo`.

**Comment by saadbzu** [comment]
I use taktakeVideoSnapshot but after recording the video, the video quality is decrease. Any suggestion?
