### ISSUE TITLE
Lost focus after taking picture

### ISSUE THREAD

**Issue by daright** [natario1/CameraView#67]
Hi. I have an issue with focus after taking picture. Autofocus works ok on tap, but after I press capture the picture loses its focus and gets blurry. Is there any solution for this?

**Comment by diegosaul402** [comment]
I have this issuse too, only happens on LG - Stylo with android 6.0

**Comment by daright** [comment]
Here Xiaomi redmi 3s and also Android 6.0

**Comment by natario1** [comment]
So the saved picture is blurred? Can you explain better, or post a video of this happening?

**Comment by natario1** [comment]
Closing this for a month of inactivity. Feel free to open another if the issue persists with latest version, and fill the issue form. A video would help in this case.
