### ISSUE TITLE
integration issue

### ISSUE THREAD

**Issue by tabassumLatif** [natario1/CameraView#70]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by natario1** [comment]
So see logs?

**Comment by RobertoMorelos** [comment]
I'm facing the same error:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.1.0) from [com.android.support:cardview-v7:26.1.0] AndroidManifest.xml:25:13-35
  	is also present at [com.android.support:exifinterface:26.0.2] AndroidManifest.xml:25:13-35 value=(26.0.2).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:23:9-25:38 to override.

**Comment by RobertoMorelos** [comment]
Apparently there are different versions of the android support library, I'm using the latest one (26.1.0) but the library is using the 25.

**Comment by v-gar** [comment]
Hello, same problem here. @natario1 I already wrote you an email about this topic on Monday.

**Comment by natario1** [comment]
I think you can compile using `exclude group: 'com.android.support'` to fix this. Anyway if someone wants to PR and upgrade this to 26.1.0, that's welcome!

**Comment by v-gar** [comment]
Opened #73

**Comment by natario1** [comment]
Merged, thanks

**Comment by v-gar** [comment]
Can you push it to the Gradle repo?

**Comment by RobertoMorelos** [comment]
If we exclude 'com.android.support' some features don't work properly like the cameraCropOutput and CameraUtils (I got some crashes). @natario1 in which version this upgrade/fix will be at? Thanks a lot!

**Comment by natario1** [comment]
Oh sure. I will release a new version in the next days, meanwhile you can use some other workaround, just google the error to find. (or you can use 26.0.1 in your other dependencies since there's no real difference). Thanks!

**Comment by v-gar** [comment]
Works now. (v1.3.0) :+1:
