### ISSUE TITLE
Skip starting of video

### ISSUE THREAD

**Issue by saadbzu** [natario1/CameraView#702]
Hi, i don't know why every time when i record video after the video recording complete the starting 2 second video is automatically skip. I check the issues list here is github in your project, one person also ask this question why 2 second video is skip. Your answer is this was not the fault from your side. Then explain why video skip 2 seconds? This is not the normal behavior of a camera.

**Comment by TemMax** [comment]
Android devices has specific freeze in the start of recording. If you don't want see this freeze — use capturing from surface [takeVideoSnapshot(File)](takeVideoSnapshot(File))
