### ISSUE TITLE
Unable to add dependency

### ISSUE THREAD

**Issue by MdFarhanRaja** [natario1/CameraView#71]
Unable to add dependency, it shows error like bellow
Error:Failed to resolve: com.android.support:support-annotations:26.0.2
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/home/rakshit/Downloads/CameraTest/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

After clicking on Install Repository....... Nothing happend.

Please help me out from this issue. I need your library for my project.

**Comment by natario1** [comment]
You might need to add the Google maven repo https://developer.android.com/studio/build/dependencies.html#google-maven
