### ISSUE TITLE
Camera Flash is not working on Motorola Moto E5 plus Android 8.0.0. api 26

### ISSUE THREAD

**Issue by MuhammadAjmal661** [natario1/CameraView#719]
when i setFlash(Flash.ON) Or setFlash(Flash.Auto) on Motorola Moto e5 plus and Oppo CPH1853 Android 8.1 APi 27 it is not working, it is working fine on other device like Huawei  Samsung etc.
thanks .

**Comment by natario1** [comment]
See #736 (feel free to add the missing information there)
