### ISSUE TITLE
Whether the front and rear cameras are supported to work at the same time

### ISSUE THREAD

**Issue by ZSK-CRS** [natario1/CameraView#733]
Excuse me, does this project support front and rear cameras working at the same time? When I put two CameraView components on the interface, one with the front camera and the other with the rear camera, and then it doesn't work.

**Comment by natario1** [comment]
I don't think this will work, sorry!

**Comment by VolodymyrMachekhin** [comment]
It is device spcific feature. For example, it works on one plus, nexus devices, pixel but fails on samsung, huawei, htc. So it is impossible in android system. There is also nothing in the Google Play that works everywhere
