### ISSUE TITLE
Is there a way to set preview active area?

### ISSUE THREAD

**Issue by flyingV805** [natario1/CameraView#749]
I think I read everything in the documentation, but did not find the answer to this question. I would be grateful if someone tells me how to achieve this.
Is it possible to achieve something like this with CameraView?
![615BwG64JUL](https://user-images.githubusercontent.com/23304936/72334339-5931c280-36e7-11ea-9e62-074ad0754e11.jpg)

**Comment by mucahidkambur** [comment]
Hi @flyingV805, did you find a solution for this?
