### ISSUE TITLE
Allow to clearLifecycleOwner()

### ISSUE THREAD

**Issue by methelas** [natario1/CameraView#763]
### Problem to be addressed
Hey 👋 
I'm using `setLifecycleOwner()` so that I don't have to deal with all stuff related to opening/closing the camera myself. But... there comes a point in my apps flow where I need to close the camera
so that it won't open until manually opened again without leaving the screen.
I could of course temporarily replace the lifecycleOwner with new one fixed in ON_PAUSED state, but it feels dirty to do so.

### Describe the solution you'd like
Simple `clearLifecycleOwner()` or allowing to pass `null` to existing `setLifecycleOwner()` would be enough.
Another option(maybe even better) would be to introduce some kind of `lock` that would keep the camera in `closed` state while lifecycle methods are called, with the exception of `onDestroy` where at this point the camera would no longer be usable anyway.

**Comment by natario1** [comment]
> allowing to pass null to existing setLifecycleOwner() 

I'm fine with this! Do you want to set up a PR?
