### ISSUE TITLE
cameraVideoSizeAspectRatio for Font facing not working

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [natario1/CameraView#768]
### Expected behavior
Squre video

<com.otaliastudios.cameraview.CameraView
                android:id="@+id/cameraView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_centerInParent="true"
                app:cameraEngine="camera2"
                app:cameraPreview="texture"
                app:cameraVideoSizeAspectRatio="1:1"
                app:cameraSnapshotMaxWidth="480"
                app:cameraFacing="front"
                app:cameraHdr="on"
                app:cameraFlash="auto"
                app:cameraWhiteBalance="auto"
                app:cameraUseDeviceOrientation="false"
                app:cameraMode="video"/>
</CameraView>

**Comment by natario1** [comment]
If you want square video snapshot, you must make your View square. See https://natario1.github.io/CameraView/docs/snapshot-size
