### ISSUE TITLE
Frame and preview size are different!

### ISSUE THREAD

**Issue by assemmohamedali** [natario1/CameraView#770]
### How do I?
`Process a frame and draw a canvas using SurfaceTexture.`

So far, I did that but the problem is the frame size is not the same as preview size this leads to draw on the wrong position at the preview size.

I changed frame size to be equal to preview size but this of course affect the performance.

### Version used
2.6.1.

**Comment by assemmohamedali** [comment]
@natario1 hope you could help on that

**Comment by natario1** [comment]
Yes, they are different! However you have methods to get the two sizes, and you should account for differences in scale and aspect ratio when drawing
