### ISSUE TITLE
FIlter only works with snapshot normal camera does not apply filter plz fix

### ISSUE THREAD

**Issue by blazingdevil44** [natario1/CameraView#773]
Filter doesn't work with normal camera and its really annoying right after I finished making my app I noticed to make sure I even downloaded ur demo to check and its the same filter doesn't work for normal camera maybe im doing something wrong please help since I don't want to change library I dumb and spent days in it please

**Comment by army650663** [comment]
same issues

**Comment by natario1** [comment]
The solution is to use snapshots.

**Comment by iamkdblue** [comment]
@natario1 but the quality of snapshots is not good as normal video recording, how can improve?
