### ISSUE TITLE
Capture media with custom filter

### ISSUE THREAD

**Issue by PearKMA** [natario1/CameraView#781]
Hi I have created a filter based on yours. When i set it to preview, it works normally but when i captured by takePictureSnapshot() or takeVideoSnapshot(), it does not work. What do I have to do to make it work? [This](https://github.com/PearKMA/CameraFilter/blob/master/CameraFilterBlend.java) is my filter. (https://github.com/PearKMA/CameraFilter/blob/master/CameraFilterBlend.java).

**Comment by natario1** [comment]
When media is taken, onCopy is called and a new instance is created. The new instance operates in the same gl context, so you don't have to recreate the texture, but probably just pass `filterInstance` integer to the copy.

**Comment by PearKMA** [comment]
thanks
