### ISSUE TITLE
Is it possible to show square (preview square) in the center and translucent background?

### ISSUE THREAD

**Issue by alexei-28** [natario1/CameraView#783]
android project:

```
implementation "com.otaliastudios:cameraview:2.6.0"

<androidx.constraintlayout.widget.ConstraintLayout
               android:id="@+id/containerCameraView"
               android:layout_width="0dp"
               android:layout_height="0dp"
               android:layout_margin="@dimen/min_height"
               app:layout_constraintBottom_toTopOf="@+id/scanHinttextView"
               app:layout_constraintEnd_toEndOf="parent"
               app:layout_constraintStart_toStartOf="parent"
               app:layout_constraintTop_toTopOf="parent">

               <com.otaliastudios.cameraview.CameraView
                   android:id="@+id/cameraView"
                   android:layout_width="0dp"
                   android:layout_height="0dp"
                   android:keepScreenOn="true"
                   app:cameraAudio="off"
                   app:cameraMode="picture"
                   app:cameraPictureFormat="jpeg"
                   app:cameraRequestPermissions="false"
                   app:layout_constraintBottom_toBottomOf="parent"
                   app:layout_constraintEnd_toEndOf="parent"
                   app:layout_constraintStart_toStartOf="parent"
                   app:layout_constraintTop_toTopOf="parent" />

           </androidx.constraintlayout.widget.ConstraintLayout>

```

I need:
1. translucent background
2. square in center
3. Also I need rectangular corners (white color)

smt like this:

![image](https://user-images.githubusercontent.com/303539/74513421-2dd30b00-4f13-11ea-9d2c-8c79ede3043a.png)

is it possible?

**Comment by yuripourre** [comment]
@alexei-28 yes, it is possible. You could create a RelativeLayout or a FrameLayout and add CameraView and then your overlay (the square) to it. As overlay you could create a vertical linearlayout, for example, and divide into three parts:

- The upper part would be transparent (black tint).
- The middle part could be another LinearLayout but this time horizontal, weighted and divided into three (transparent, your image, transparent), remember to use the same weight into transparent parts
- The bottom part would be transparent (black tint) the same as the upper.

```
<RelativeLayout>
  <com.otaliastudios.cameraview.CameraView>
  ...
  </com.otaliastudios.cameraview.CameraView>
  <View>
  <!--my overlay-->
  </View>
</RelativeLayout>
```

You should be able to do that in any Android App. It is not related/specific to CameraView library
A more complete answer: https://stackoverflow.com/a/7519248/7030976

Please tell me if you need more details

**Comment by theanilpaudel** [comment]
Is there any way to capture only the part that is visible in the overlay square?
