### ISSUE TITLE
CircularReveal and cameraview

### ISSUE THREAD

**Issue by mariuspena** [natario1/CameraView#785]
### How do I?
I show/hide the camera preview with an CircularReveal animation. It worked in v1, now I migrated to the v2 and the circularReveal does not mask the preview anymore.
Is there something I could do to obtain the effect I want ? thanks

### Version used
2.6.1

**Comment by natario1** [comment]
You can try changing the cameraSurface attribute to texture, but you will loose a lot of functionality (see docs).

**Comment by mariuspena** [comment]
I switched to texture for now. but do you see any fix for this in the future ?

**Comment by natario1** [comment]
No because surface view draws on a separate window that likely can't be clipped by the circular reveal animation.

**Comment by mariuspena** [comment]
got it. thanks!
