### ISSUE TITLE
Live Preview all filters

### ISSUE THREAD

**Issue by msroid** [natario1/CameraView#808]
I want to have a preview of any available filter so that user can see it before selecting.
I want to do something like this at the bottom of  the image:

[https://evolutionmentor.com/wp-content/uploads/2018/02/instagram-2.jpg](url)

this is for image but I want live preview  of camera.

If I use recyclerview and use cameraview as the child of it the app crashes. Also I pass the preview from the main CameraView to the recyclerview adapter but it didn't work too.
the most important problem is the CameraView lifecyclerowner and that't because I am using CameraView in a adapter!

I appreciate any help

best regards

**Comment by natario1** [comment]
We do not support multiple instances of CameraView. Adding multiple previews is complex so I can't help here, sorry. If you represent a company feel free to send an e-mail.

**Comment by msroid** [comment]
Any idea how can I apply those filters on a bitmap?
I have no experience of working with opengl!
If there's a way for doing this I can get the preview bitmap and then apply the filter on it.
best regards

**Comment by natario1** [comment]
You can't apply them directly to Bitmaps unfortunately.
