### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by a1void** [natario1/CameraView#809]
### How do I?
Hello, I just started learning java and android, Where can I find a simple CameraView example code?

### Version used
2.7.0

**Comment by natario1** [comment]
You can take a look at the website https://natario1.github.io/CameraView and at the sample application in the `app` module

**Comment by a1void** [comment]
Could you please give an example of a code to just take a snapshot with a button?
Thank you for this amazing library

**Comment by yuripourre** [comment]
@a1void https://natario1.github.io/CameraView/about/getting-started
