### ISSUE TITLE
camera preview show cropped view

### ISSUE THREAD

**Issue by Miteshmakwana73** [natario1/CameraView#818]
### Describe the bug
camera not showing full preview it is showing half preview but captured image is showing full preview i don't understand why it is happening

 this is my code for cameraview

```
 <com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        android:layout_centerInParent="true"
        android:layout_gravity="center"
        android:keepScreenOn="true"
        app:cameraAudio="on"
        app:cameraFacing="back"
        app:cameraFlash="off"
        app:cameraGestureLongTap="none"
        app:cameraGesturePinch="none"
        app:cameraGestureScrollHorizontal="none"
        app:cameraGestureScrollVertical="none"
        app:cameraGestureTap="focus"
        app:cameraGrid="off"
        app:cameraJpegQuality="100"
        app:cameraPlaySounds="true"
        app:cameraSessionType="picture"
        app:cameraVideoQuality="max720p"
        app:cameraWhiteBalance="auto"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/view19">

    </com.otaliastudios.cameraview.CameraView>
```
this is the camera preview of camera
![Screenshot_20200408_105336_com flipquick](https://user-images.githubusercontent.com/38969602/78747953-637ef800-7988-11ea-8dc2-deeb369a6385.jpg)
this is captured image preview 
![Screenshot_20200408_105524_com flipquick](https://user-images.githubusercontent.com/38969602/78747981-7396d780-7988-11ea-892e-13e00f6cbdf8.jpg)

you can see that captured image showing more than camera preview 
my requirement to show same preview as captured image

**Comment by ZakroKhitalishvili** [comment]
Same issue

**Comment by fjr619** [comment]
same issues, the aspect ratio between preview and capture is not same when preview is match parent

**Comment by ZakroKhitalishvili** [comment]
I solved this issue by cropping to preview's aspect ratio
Here is code:
```
private static Bitmap cropToAspectRatio(Bitmap image, float aspectRatio) {
        int width = image.getWidth();
        int height = image.getHeight();
        float imageAspectRatio = (float) width / (float) height;

        if (imageAspectRatio == aspectRatio) {
            return image;
        }

        int newWidth = (int) (height * aspectRatio);
        if (newWidth < width) {
            int margin = (width - newWidth) / 2;
            return Bitmap.createBitmap(image, margin, 0, newWidth, height);
        } else {
            int newHeight = (int) (width / aspectRatio);
            int margin = (height - newHeight) / 2;
            return Bitmap.createBitmap(image, 0, margin, width, newHeight);
        }
    }
```

**Comment by Miteshmakwana73** [comment]
@ZakroKhitalishvili 
just add 
`        app:cameraCropOutput="true"` 

in CameraView it will work fine

**Comment by ZakroKhitalishvili** [comment]
@Miteshmakwana73 
That attribute is not supported anymore in v2.

According to docs:

> Both cameraCropOutput and setCropOutput() have been removed. This was an expensive operation that worked with pictures only. In v2, if you want your output to be cropped to match the view bounds, you will use the *snapshot() APIs .

But a produced snapshot is significantly reduced in quality.

**Comment by ZakroKhitalishvili** [comment]
To sum up this is not a bug, but a feature.

We have three options:

- Downgrade to v1
- Using snapshot API
- Cropping manually

**Comment by Miteshmakwana73** [comment]
@ZakroKhitalishvili thank you for this information i don't know about this but i still think they should provide better solution for this scenario
