### ISSUE TITLE
cameraPictureSizeAspectRatio cameraVideoSizeAspectRatio not working on all devices

### ISSUE THREAD

**Issue by AlexInn** [natario1/CameraView#819]
### How do I?
Hi, sorry for disturbing you.
Congratulations for the library, it's wonderful!
I have a problem on Xiaomi devices, the camera preview as the picture/video that I make wont get the correct aspect ratio that I've set on the View ( f.e.: cameraVideoSizeAspectRatio="1:1").

It's a known bug or maybe is me?

Thanks a million for your attention.

### Version used
CameraView version: 2.6.2

**Comment by natario1** [comment]
You can't be sure that the device will support 1:1 pictures/videos. I suggest making **CameraView** 1:1 (for example with ConstraintLayout) and using takePictureSnapshot and takeVideoSnapshot to get 1:1 pictures/videos.

**Comment by AlexInn** [comment]
Perfect! Sorry for the waste of time was my error!

Thanks again!
