### ISSUE TITLE
After taking a picture, frame process will not receive any frame in Camera1.

### ISSUE THREAD

**Issue by Weakey** [natario1/CameraView#824]
Hi,
In Full1PictureRecorder.java, it stops the preview callback by set to null before takePicture.
The preview callback will be set back on onPictureTaken function but forget to re-add callback buffer.

Reference:
https://developer.android.com/reference/android/hardware/Camera
Camera.PreviewCallback: a callback object that receives a copy of the preview frame, or null to stop receiving callbacks and "clear the buffer queue".

**Comment by natario1** [comment]
Thanks for reporting @Weakey ! Would you like to fix it? I think we should call FrameManager.release() when removing the callback, and FrameManager.setUp() when adding it back.

**Comment by jeffreyfjohnson** [comment]
@natario1 I can put in a fix for this. In the meantime, I'm trying to prove something out, do you know of a workaround here?

**Comment by natario1** [comment]
I don't know any workaround, sorry, it's really just an internal bug. Thanks for fixing it

**Comment by larkonesvk** [comment]
Hi @natario1,
 when do you plan to release new version with this fix?
