### ISSUE TITLE
Pixel 4 issues on upgrade 2.6.1 -> 2.6.2

### ISSUE THREAD

**Issue by sameerjj** [natario1/CameraView#830]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.6.2
- Camera engine used: camera2
- Reproducible in official demo app: yes
- Device / Android version: *Pixel API 29, targetSDK 29*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. See error immediately on default cameraview, display is glitchy

### Expected behavior
normal camera preview

### XML layout
see demo app 

### Screenshots
![image](https://user-images.githubusercontent.com/7051257/80045870-ba331880-84d6-11ea-9f88-9f8ac52cc6b3.png)

### Logs
Sorry, using client device, unable to get them currently

### APK
see demo app

**Comment by honzasmuk** [comment]
Hi,
I can confirm the same issue on Pixel 4a (Android 11).
CameraView v2.6.1 works but v2.6.2 does not. I tried the newest v2.7.0 and problem is still present.

Preview shows trippled image:
![Screenshot_20210512-112320](https://user-images.githubusercontent.com/19922539/117961724-bad76080-b31e-11eb-818a-281d7bfa0c99.jpg)

And after few seconds app crashes.

Full log:
[cameraview-2.7.0-pixel4a.txt](https://github.com/natario1/CameraView/files/6465560/cameraview-2.7.0-pixel4a.txt)
