### ISSUE TITLE
Camera2 engine optimization

### ISSUE THREAD

**Issue by qingshanchangyi** [natario1/CameraView#836]
Hello, how is the development of your Camera2 engine? When I use this engine: `app:cameraengine = "Camera2"` , and set` app: cameraexperimental = "true"`, it's hard for me to delay taking photos for about two seconds, but when I set `app: cameraexperimental = "false"`, the photos will be stuck for about one second. This problem appears in the current new model, compared with Such as Huawei mate30. Is there any way to optimize, that is, I can call the takepicture method to quickly capture photos.
If there is any progress I haven't known, please let me know in time. Thank you！

**Comment by maylamayana** [comment]
that is my problem too
