### ISSUE TITLE
The video is stretched when using takeVideoSnapshot to take a multiFilter video

### ISSUE THREAD

**Issue by developertry** [natario1/CameraView#837]
### How do I?
Hello, I use multiFilter in the demo project. The video I get when using takeVideoSnapshot is stretched. How can I modify it?
I found that the rotation is 0 in the result page of the video, but the rotation is 90 when using takeVideo.

### Version used
2.6.2

**Comment by developertry** [comment]
when takeVideoSnapshot
![微信图片_202004301647321](https://user-images.githubusercontent.com/4442449/80691101-5aee8d00-8b02-11ea-9e4d-1c6eeb78dfa2.jpg)

the result
![微信图片_20200430164732](https://user-images.githubusercontent.com/4442449/80691099-5924c980-8b02-11ea-97c2-580287a91629.jpg)

**Comment by grigM** [comment]
Hi @natario1 ! 
thank you for your's amazing work on this library!
 
i'm also have some video stretching problems when using multiFilter with videoSnapshot.
Preview on screen - is ok , with proper aspect ration, but video result is not.

maybe the reason of this line number 248 of SnapshotVideoRecorder.java:
mCurrentFilter.setSize(mResult.size.getWidth(), mResult.size.getWidth());

i't would be great. if you can check this

**Comment by natario1** [comment]
I think this is because of #875 (open) @grigM

**Comment by phamluanhanu2010** [comment]
@natario1 Do you have any update for this issue? I use the newest version but it still stretched video after user multifiler. 
Please guide me fix it.
