### ISSUE TITLE
How to access SurfaceView for setZOrderMediaOverlay / setZOrderOnTop?

### ISSUE THREAD

**Issue by chitrang200889** [natario1/CameraView#838]
### How do I?

First of all, many thanks for creating this wonderful library.

I am using GLSurfaceView for taking a video snapshot. Video is being played with PlayerView(ExoPlayer) inside a square layout, and on the right top corner I need to show CameraView, and vice versa. UI is kind of similar as in WhatsApp video call, where a user can switch between two views.

Either CameraView overlaps PlayerView entirely or it shows some partial cut where both views intersect.

So is there a way to get CameraPreview and through that SurfaceView in order to usesetZOrderMediaOverlay / setZOrderOnTop?

### Version used
CameraView exact version.
api 'com.otaliastudios:cameraview:2.6.2'

**Comment by natario1** [comment]
You can either, 
- use camera.findViewById(). I don't remember the id but you can check the source code 
- find recursively using getChildAt() until you find a SurfaceView somewhere
- extend CameraView and override instantiateCameraPreview
