### ISSUE TITLE
Question about aspect ratio

### ISSUE THREAD

**Issue by fjr619** [natario1/CameraView#840]
### How do I?
1. how to take snapshot with flash on? even if i already set `camera.setflash(Flash.ON)` and `camera.setPictureSnapshotMetering(true)`

2. Right now im using preview with match parent, how to make capture size in same aspect ratio with the preview? because right now im getting aspect ratio 4:3 for capture, and preview aspect ratio maybe 16:9

3. 
```
        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/cameraView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:keepScreenOn="true"
            app:cameraEngine="camera2"
            app:cameraPreview="glSurface"
            app:cameraAudio="off"
            app:cameraGrid="off"
            app:cameraGestureTap="autoFocus"
            app:cameraPlaySounds="false"
            app:cameraFacing="back"
            app:cameraFlash="off"
            app:cameraGesturePinch="zoom"
            app:cameraMode="picture"
            app:cameraPictureSnapshotMetering="true"
            app:cameraPictureMetering="true"
            app:cameraPictureSizeAspectRatio="16:9"
            app:aspectRatio="16:9"
            app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker">

```
I already set my aspectRation = 16:9 but my preview and capture size still 4:3, how to change aspect ratio? i need take picture to 16:9 or full screen

4. How we set watermark in capture result like in snapshot?

### Version used
2.6.2

**Comment by neuralitgit** [comment]
Hi , how to have multiple aspects ratio in Library.
