### ISSUE TITLE
After calling takePicture camera tries to keep focusing for long time

### ISSUE THREAD

**Issue by ARTonu** [natario1/CameraView#842]
I am trying to disable auto focus as described [#107](https://github.com/natario1/CameraView/issues/107) here.
Now autofocus stops when camera open for first time but while taking picture it continuously try to gain focus.
How can i stop this?

Thank you in advance!

**Comment by Breno1112** [comment]
override fun onTakePicture(stub: PictureResult.Stub, doMetering: Boolean) {
        super.onTakePicture(stub, false) // this tells it not to focus when taking a picture. It goes on the MyCameraEngine class

**Comment by ARTonu** [comment]
Thank you for instruction.
