### ISSUE TITLE
How  to take  square  image  . 

### ISSUE THREAD

**Issue by rahat14** [natario1/CameraView#848]
i have  camera  view of full screen . how  can i take  square image  like  Instagram with this  view  . tried  set max width and  height didn't worked . 
![Screenshot_2020-05-11-02-38-55-131_com newtown stories](https://user-images.githubusercontent.com/27925309/81510006-9a9e4b80-9330-11ea-892a-c70cf2dce00c.jpg)

### Version used
CameraView latest version.

**Comment by Namazed** [comment]
Hi, @rahat14 
If you mean about result of takePicture, I advice you look at this part of documentation https://natario1.github.io/CameraView/docs/capture-size

Maybe you need write custom Selector, because by default cameraView take biggest size for picture.
