### ISSUE TITLE
Trying to remove `CameraListener` from `CameraListener` methods leads to a crash

### ISSUE THREAD

**Issue by ManueGE** [natario1/CameraView#85]
##### Detailed steps to reproduce the issue:

Add this code:

```
camera.addListener(new CameraListener() {
    @Override
    public void onCameraClose() {
        camera.removeListener(this);
        // Set parameters and start again.
        camera.start();
    }
});
camera.stop();
```

##### Expected behavior:
The listener must me removed. 

##### Actual behavior:
The app crashes with this error: 

```
 java.util.ConcurrentModificationException
```

##### Suggestions:

Replace the `mListeners` list in the calls to listeners by an iterator

**Comment by natario1** [comment]
Thanks! AFAIK the iterator would break anyway, I think we should use `CopyOnWriteArrayList`s instead of `ArrayList`
