### ISSUE TITLE
Set Activity android:screenOrientation="landscape", picture rotate sometime.

### ISSUE THREAD

**Issue by wanglelecn** [natario1/CameraView#859]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: *2.6.2*
- Camera engine used: *both*
- Reproducible in official demo app: *yes*
- Device / Android version: *Honor 9 Lite, Pixel, API 28 & OPPO A57  API 23（6.0.1）*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
1. Set android:screenOrientation="landscape"；
2. Set app:cameraUseDeviceOrientation="false"；
3. Tilt the top of the phone before Lauching Activity；
4. Lauching Activity；
5. Take picture  snapshot.You will find the picture is rotated；
6. Then  adjust phone orientation and take picture snapshot again, the picture orientation is right.

### XML layout

```xml
<com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginBottom="88dp"
        android:keepScreenOn="true"
        app:cameraAudio="on"
        app:cameraAutoFocusMarker="@string/cameraview_default_autofocus_marker"
        app:cameraEngine="camera2"
        app:cameraExperimental="true"
        app:cameraFacing="back"
        app:cameraFlash="auto"
        app:cameraGestureLongTap="none"
        app:cameraGesturePinch="zoom"
        app:cameraGestureScrollHorizontal="filterControl1"
        app:cameraGestureScrollVertical="exposureCorrection"
        app:cameraGestureTap="autoFocus"
        app:cameraGrid="off"
        app:cameraMode="picture"
        app:cameraPlaySounds="true"
        app:cameraPreview="glSurface"
        app:cameraUseDeviceOrientation="false" />
```

**Comment by nestoleh** [comment]
I also have this issue sometimes
