### ISSUE TITLE
How to overlay the frame processor?

### ISSUE THREAD

**Issue by ArcSoul** [natario1/CameraView#863]
### How do I?
Hello, how can I make each frame processor have an overlay, because I am using mlkit but I only want that in some part of the overlay the frame can be processed, for that I put an overlay where everything is lead and only in a circle you can see the camera (face), but the overlay does not add it to the frame

my overlay is a ring:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="ring"
    android:thicknessRatio="1"
    android:innerRadiusRatio="2.3"
    android:useLevel="false">
    <solid android:color="#AAAAAA" />
    <size
        android:height="160dp"
        android:width="120dp" />
</shape>
```

### Version used
2.6.2

**Comment by sertunc** [comment]
Hello, can you share your addFrameProcessor method body? Thank you
