### ISSUE TITLE
how can i use lookuptablefilter

### ISSUE THREAD

**Issue by Jey1992** [natario1/CameraView#878]
### How do I?
i want use a lookuptable image to translate filter , but i fannally didnot find a way to use it, can you fix my problem?

**Comment by javaerwjy** [comment]
//        GPUImageLookup64Filter gpuImageLookup64Filter = new GPUImageLookup64Filter();
//        gpuImageLookup64Filter.setParameter1(1);
//        gpuImageLookup64Filter.setLookupResource(R.drawable.lookup_64);
//        cameraView.setFilter(new MultiFilter(new NoFilter(), gpuImageLookup64Filter));

**Comment by Jey1992** [comment]
there is no GPUImageLookup64Filter class find

**Comment by Jey1992** [comment]
> // GPUImageLookup64Filter gpuImageLookup64Filter = new GPUImageLookup64Filter();
> // gpuImageLookup64Filter.setParameter1(1);
> // gpuImageLookup64Filter.setLookupResource(R.drawable.lookup_64);
> // cameraView.setFilter(new MultiFilter(new NoFilter(), gpuImageLookup64Filter));

can you show me you GPUImageLookup64Filter class , thanks
