### ISSUE TITLE
Why "Watermarks" and "Overlays" don't work with "takePicture()" and "takeVideo()"?

### ISSUE THREAD

**Issue by rajib010** [natario1/CameraView#881]
### 
Why "Watermarks" and "Overlays" don't work with "takePicture()" and "takeVideo()" as "takePictureSnapshot()" and "takeVideoSnapshot()"?
How can I add Overlay in high-resolution picture and video?

### Version used
2.6.2

**Comment by natario1** [comment]
That's how the library is designed. If you want you can post-process the image and video to add the overlays, but not with this library.
