### ISSUE TITLE
Frame processing not working once video starts recording

### ISSUE THREAD

**Issue by heyletscode** [natario1/CameraView#893]
- CameraView version: 2.6.2
- Camera engine used: camera1
- Device / Android version: Nokia, API 29

Steps to reproduce
Process image using ML Kit while recording video. "do not know color format" gets printed in logcat

### Expected behavior
ML Kit unable to perform correctly

### XML layout
`<com.otaliastudios.cameraview.CameraView
                android:id="@+id/cameraView"
                android:layout_width="140dp"
                android:layout_height="180dp"
                app:cameraAudio="mono"
                app:cameraAudioBitRate="64"
                app:cameraFacing="front"
                app:cameraFlash="off"
                app:cameraMode="video"
                app:cameraVideoBitRate="1000" />`

**Comment by SAFatemi** [comment]
Hello.
I have same issue, how can I resolve this problem?

- CameraView version: 2.6.4
- Camera engine used: camera1
- Device / Android version: Samsung A71F, API 30
