### ISSUE TITLE
Front Camera dark video recording in Pixel 2

### ISSUE THREAD

**Issue by buntupana** [natario1/CameraView#898]
### Describe the bug
When I record a video with the front camera it becomes really dark (preview and result) while preview is OK when is not recording, so far is happening just with a Pixel 2

- CameraView version: 2.6.2
- Camera engine used: *default*
- Reproducible in official demo app: yes
- Device / Android version: Pixel2, API 29

### Expected behavior
The video should be recorded with a proper exposure measurement

### XML layout

```xml
        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/cameraView"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:keepScreenOn="true"
            app:cameraPlaySounds="false"
            app:cameraRequestPermissions="false"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintDimensionRatio="1"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

**Comment by jonathanlmarsh** [comment]
I'm experiencing the same issue on Pixel 2 and Pixel 3 XL with the front camera. However, setting `app:cameraEngine="camera2"` and `app:cameraExperimental="true"` seems to solve the issue.
