### ISSUE TITLE
how to get video recording time ?

### ISSUE THREAD

**Issue by iamkdblue** [natario1/CameraView#904]
First of all thanks for this great library.

I want to show a text in which shows the live recording time.

how to achieve this.

**Comment by maphongba008** [comment]
https://natario1.github.io/CameraView/docs/camera-events

**Comment by iamkdblue** [comment]
@maphongba008 which method contains timing? I checked but no luck.

**Comment by maphongba008** [comment]
in `onVideoRecordingStart`, set a timer to count every second, update the textView, then in `onVideoRecordingStop`, stop it

**Comment by iamkdblue** [comment]
@maphongba008 great and quick solution, I like your problem-solving skill. Thanks :)
