### ISSUE TITLE
How to get the frames with watermark?

### ISSUE THREAD

**Issue by autismbug** [natario1/CameraView#926]
How to get frames with watermark?
I need to get the image frame with watermark and then call the push stream SDK to send the frame data.
Through the wiki I found that cameraview can only watermark previews, photos and recordings.

` 
cameraView.addFrameProcessor(new FrameProcessor() {
            @Override
            @WorkerThread
            public void process(@NonNull Frame frame) { }
 });
`
Frame data in this event does not contain watermarks.Is there any parameter setting that can meet my needs?
thanks

**Comment by natario1** [comment]
You can use takePictureSnapshot() and use the picture data (JPEG)

**Comment by autismbug** [comment]
25-30 frames a second .Call this method twenty times one second?

**Comment by natario1** [comment]
I'd expect some 10-20 fps depending on device and light conditions, but you can see try and see how much you get.
