### ISSUE TITLE
Video-Audio Stream order being interchanged on taking video snapshots.

### ISSUE THREAD

**Issue by gauravk95** [natario1/CameraView#936]
### Describe the bug
- CameraView version: *2.6.3*
- Camera engine used: *camera2*
- Device / Android version: *Samsung A50, API 29*
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): *yes*

### To Reproduce
1. Take multiple video snapshots using and let the video save in device
```camera.takeVideoSnapshot(videoFile)```
2. Use any tool such as FFprobe or VLC Media player to check out stream information

### Expected behavior
Ideally the stream #0:0 should be h264 and stream #0:1 should be aac(mp4a)

Though the video itself are fine, snapshots with different streams will require additional encoding and decoding, when multiple such videos are merged using ffmpeg concat cmd.

```camera.takeVideo(videoFile)``` doesn't have this interchangeable streams which makes it way faster to merge videos using ffmpeg without decoding and encoding again.

### Screenshots
![Video_0_info](https://user-images.githubusercontent.com/15252140/89716460-d3e76580-d9ca-11ea-90eb-26c8d69d1494.png)
![Video_3_info](https://user-images.githubusercontent.com/15252140/89716462-d649bf80-d9ca-11ea-9c24-6d0cd5c9e9b8.png)

It would be great to have the video generated consistent streams to reduce further processing.

Thanks!

**Comment by natario1** [comment]
After going through source code, I can say that we won't address this because it would require significant changes to the recorder design - big effort for little benefit. Sorry!
