### ISSUE TITLE
FrameProcessor when orientation changes

### ISSUE THREAD

**Issue by mariuspena** [natario1/CameraView#937]
### How do I?
My scenario is the following
1. my app is only landscape, so I use android:screenOrientation="sensorLandscape" for every activity, including my CameraActivity. I also use a frame processor for a custom effect. 
2. I start the camera, the preview is ok, frameProcessor is sending frames' bitmaps with the correct orientation.
3. I turn the phone up side down, preview is restarted and re-orientated ok, but the frame processor keeps sending frames with the old orientation.

Is this the way it should behave ? Should I take care of rotating the frame bitmap with 180 when orientation changes ? Or is it a bug ? Or what can I do in this scenario so I have that frame's bitmap orientated as the preview ?

### Version used
CameraView exact version = 2.6.0

There is another issue. In the cameraLis

**Comment by natario1** [comment]
You should use the frame rotation, passed to the `Frame` object

**Comment by mariuspena** [comment]
thanks!
