### ISSUE TITLE
Capturing image from rectangular view

### ISSUE THREAD

**Issue by Oblivious-Kibria** [natario1/CameraView#942]
Using this library, is it possible to capture image only from a inside the rectangular view? I want to set a rounded rectangular view on the camera view. Areas outside of the rectangular view will be translucent. 
![123](https://user-images.githubusercontent.com/11848389/91041400-cddfbe80-e631-11ea-9378-c78e46bdce45.jpg)

**Comment by FitApps7** [comment]
yes, it is possible, but using firebase object detection ml kit

**Comment by Oblivious-Kibria** [comment]
> yes, it is possible, but using firebase object detection ml kit

**Comment by Oblivious-Kibria** [comment]
@FitApps7 Thanks for your reply. I do not want to use object detection. I just want to set that layout on top of cameraview. Then it will only capture the image shows inside the rectangle, not the portion out of the box.
