### ISSUE TITLE
Feature request: use FrameProcessors to do pre-processing (e.g. live effects)

### ISSUE THREAD

**Issue by morejump** [natario1/CameraView#95]
it really difficult to start without sample!!

**Comment by morejump** [comment]
now i want to get frame to process in opencv  c++, i have to get frame and use JNI then. But i dont now how to get instance of frame

**Comment by natario1** [comment]
We provide a java callback, then it's up to you. The only docs we can provide are already here https://github.com/natario1/CameraView#frame-processing . I know nothing about JNI but I am sure you can find a lot of info.

**Comment by aaronjrenfroe** [comment]
Is it possible to process the frames before they get displayed?

**Comment by natario1** [comment]
@aaronjrenfroe no, sorry! Not easy.

**Comment by morejump** [comment]
@natario1 I dont know how to use instance of frame before returning it to the preview. Can u give more detail about that, plz!!!

**Comment by Hrishi1999** [comment]
Well, I am not natario but ;) I've successfully implemented a frame processor in my app. You can ask me.

**Comment by natario1** [comment]
@morejump it is not supported. you can only do post-processing (barcodes, face detection, ...)
@Hrishi1999 if your solution is open source somewhere we can take a look!

**Comment by morejump** [comment]
@Hrishi1999 come on, can u tell me, how can it do it, plz :(

**Comment by Hrishi1999** [comment]
I am sorry if I misunderstood. Or maybe a few comments have been edited. What I meant is I can use the frames to do something, like maybe a realtime barcode scanner, or OCR?? Please explain me more, I implemented a frame processor, maybe I can help.

**Comment by natario1** [comment]
What he and some others are asking for, is to process the frames before they are displayed, so the preview displays the edited frame buffer instead of the real image. This is not possible with CameraView.

**Comment by abhisheksoni27** [comment]
@natario1 But if I want to Post-process the frame, how can I display the edited frame after-wards?

This is what I am currently doing:
```java
cameraView.addFrameProcessor(new FrameProcessor() {
    @Override
    @WorkerThread
    public void process(Frame frame) {
        byte[] data = frame.getData();
        Size size = frame.getSize();

        // Process `data` using OpenCV
        // Now, how should I set set the changed data?
    }
});
```

As you know, the Frame class doesn't have setters. Does this mean a LivePostProcessing pipeline can't be implemented?

**Comment by JeremeLau** [comment]
> @natario1 But if I want to Post-process the frame, how can I display the edited frame afterwards?
> 
> This is what I am currently doing:
> 
> ```java
> cameraView.addFrameProcessor(new FrameProcessor() {
>     @Override
>     @WorkerThread
>     public void process(Frame frame) {
>         byte[] data = frame.getData();
>         Size size = frame.getSize();
> 
>         // Process `data` using OpenCV
>         // Now, how should I set set the changed data?
>     }
> });
> ```
> 
> As you know, the Frame class doesn't have setters. Does this mean a LivePostProcessing pipeline can't be implemented?

I have the same request, pls someone help

**Comment by natario1** [comment]
Please refer to #176 for updates about this

**Comment by assemmohamedali** [comment]
> > @natario1 But if I want to Post-process the frame, how can I display the edited frame afterwards?
> > This is what I am currently doing:
> > ```java
> > cameraView.addFrameProcessor(new FrameProcessor() {
> >     @Override
> >     @WorkerThread
> >     public void process(Frame frame) {
> >         byte[] data = frame.getData();
> >         Size size = frame.getSize();
> > 
> >         // Process `data` using OpenCV
> >         // Now, how should I set set the changed data?
> >     }
> > });
> > ```
> > 
> > 
> > As you know, the Frame class doesn't have setters. Does this mean a LivePostProcessing pipeline can't be implemented?
> 
> I have made my request done. If ur request is the same as mine.
> My request is 2 have the faces detected in scene and label the faces with square frames.
> Devious solution：
> 1、put a ‘SurfaceView’ just On Top of ‘CameraView’
> 2、set it TRANSPARENT
> 3、get SurfaceHolder
> 4、here we have the method 'lockCanvas', do what u have 2 do(DrawRect etc),call 'unlockCanvasAndPost(canvas)', done.
> If ur request is more complex, then good luck

This will work only if a preview frame as same as a preview surface because when you draw the canvas it will be located at a different place as the preview surface is larger. Is there anyone who has a workaround?

I think the library already set function to set the preview size and camera frame size as well but I'm so concerned with performance.
