### ISSUE TITLE
How do i use it inside recycler view>

### ISSUE THREAD

**Issue by Aimank96** [natario1/CameraView#96]
*If you are trying to report a bug, please file the information below.
Prerequisites:*

- [x] *I am using the latest version*
- [ ] *I can reproduce the bug in the demo app, and if not...*
- [ ] *I have tried to reproduce the bug in the demo app*

**Comment by natario1** [comment]
You can only have 1 active CameraView per sensor (so 1 with back camera and 1 with front camera, if you can setup them). The others will be black. So this is not really a good idea.
