### ISSUE TITLE
filter not save in video.

### ISSUE THREAD

**Issue by ashishvirani** [natario1/CameraView#965]
preview filter show in camera but record that filter video there are not apply filter in video

**Comment by hani0312** [comment]
I faced same issue. It is working fine with redmi note 3 (Android M) and Mi A2 (Android 10). But it is not working with one plus 6t, 6 (Android 10). I don't know that it is OS related issue or device specific.

Please help me with this.

**Comment by PraveenOjha** [comment]
only videosnapshot will save glsurface filter to mp4. 

try : camView.takeVideoSnapshot(file f);
