### ISSUE TITLE
How to check camera support flash or not?

### ISSUE THREAD

**Issue by 24Lathiya** [natario1/CameraView#973]
### How do I?
I would like hide flash icon if camera not support flash. for example many front cameras does not support flash.

### Version used
CameraView exact version : 2.6.4
@natario1

**Comment by PraveenOjha** [comment]
CameraOptions cameraOptions=camView.getCameraOptions();
Collection modes  cameraOptions.getSupportedFlash();
boolean b= modes.contains(Flash.ON);

can check for Flash.torchetc

**Comment by 24Lathiya** [comment]
@PraveenOjha getting `mCameraView.getCameraOptions() ` null at initialise camera
@natario1 Please let me know if any solution.

**Comment by 24Lathiya** [comment]
Thanks @PraveenOjha your trick work like charm with few changes like below

```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                CameraOptions cameraOptions = mCameraView.getCameraOptions();
                if (cameraOptions != null) {
                    Collection<Flash> modes = cameraOptions.getSupportedFlash();
                    boolean isSupportFlash = modes.contains(Flash.ON);
                    System.out.println("=====flash=====" + isSupportFlash);
                }
            }
        },300);
```
