### ISSUE TITLE
Getting uncompressed photo

### ISSUE THREAD

**Issue by R3nd0gg** [natario1/CameraView#976]
My goal is to save snapped image into PNG to do further processing on it. I know I can snap image as DNG and convert that to PNG but that includes extra step. Is there a way to get uncompressed (e.g. YUV_420_888 image format) that I can manually convert to PNG (e.g. using Bitmap.compress()) ?
I know that FrameProcessor returns frames in that format but I have to use snapped pictures which are properly focused and have used flash on them.

### Version used
2.6.4

Thanks

**Comment by PraveenOjha** [comment]
Their is raw data inside lib you can fork or copy this project to use as a lib
 save it as per your wish .

if using  camera 1 engine .

File Name : com.otaliastudios.cameraview.picture.Full2PictureRecorder
Line Number 
   public void onPictureTaken(byte[] data, final Camera camera) { } 
 
//   data here is raw and may be in nv1 format. 

if using camera 2 engine .
File Name : com.otaliastudios.cameraview.picture.Full2PictureRecorder

  public void onImageAvailable(ImageReader reader) 
   {
       Image image = null; 
        LOG.i("onImageAvailable started.");
      //noinspection TryFinallyCanBeTryWithResources
        try {
//Line number 128       
           image = reader.acquireNextImage();
//Here you got raw data may be in YUV_420_888
