### ISSUE TITLE
Is there a way to get preview frame instead of camera frame for processing?

### ISSUE THREAD

**Issue by catmasteryip** [natario1/CameraView#980]
### How do I get preview frame instead of camera frame for processing?
I checked frame processing part of the documentation. It seems users can only get and process camera frames but then overlay analysis results (bounding boxes for example) on top of the preview frames. Is there a way to get preview frame instead of camera frame for processing, or at least coordinates of preview frame rectangle within the camera frame?

### Version used
2.6.4

**Comment by PraveenOjha** [comment]
You can calculate that easily the relation between preview, frame . 

if (frame.getDataClass() == byte[].class) {
				byte[] data = frame.getData();
				Size s = frame.getSize();
				YuvImage yuv = new YuvImage(data, ImageFormat.NV21, s.getWidth(), s.getHeight(), null);
				ByteArrayOutputStream stream = new ByteArrayOutputStream();
				yuv.compressToJpeg(new Rect(0, 0, s.getWidth(), s.getHeight()), 100, stream);
				byte[] buf = stream.toByteArray();
				Int roatation=frame.getRotationToUser();
				Bitmap b =BitmapFactory.decodeByteArray(buf, 0, buf.length, null);
				// Process byte array...
			} else if (frame.getDataClass() == Image.class) {
				Image data = frame.getData();
				ByteBuffer buffer = data.getPlanes()[0].getBuffer();
				byte[] bytes = new byte[buffer.capacity()];
				buffer.get(bytes);
				Int r=frame.getRotationToUser();
				Bitmap b =BitmapFactory.decodeByteArray(bytes, 0, bytes.length, null);
			}
		}
	});


You can have frame as a bitmap ,can easily find its height and width , CameraView is a view so its height and width is known.
You can even draw this bitmap with 50%alpha over cameraview to check your bond .
