### ISSUE TITLE
Image Rotated

### ISSUE THREAD

**Issue by nawazish011** [natario1/CameraView#982]
When I rotate the device it capture the rotated image.

**Comment by PraveenOjha** [comment]
cameraView.setUseDeviceOrientation(true); // rotate media 
cameraView.setUseDeviceOrientation(false); // don't

**Comment by nawazish011** [comment]
Thank You so much @PraveenOjha for your kind reply. I have already fix it with the same solution.

**Comment by PraveenOjha** [comment]
Please close this issue then .
