### ISSUE TITLE
Display problems on Android 11 (API 30)

### ISSUE THREAD

**Issue by JoAdams34** [natario1/CameraView#986]
On a Google Pixel 4a running Android 11 (API 30) the default cameraView (GL) display looks like this with a strange split into multiple panes:
![Screenshot_20201030-110953b](https://user-images.githubusercontent.com/36496435/97714198-dbf50400-1ae6-11eb-91c5-8ec9c2cd9de5.png)

**Comment by polokoio456** [comment]
I test multiple Android 11 devices, only Pixel 4a has this problem.
I think it has nothing to do with Android 11.
Hoping someone for solving this issue.

**Comment by polokoio456** [comment]
I test multiple Android 11 devices, only Pixel 4a has this problem. (Only back facing for me with pixel 4a)
Interesting, Pixel 4a's hardware supported level is LEVEL_FULL.

I found camera1 would not occur this issue.

Hoping someone for solving this issue.

**Comment by polokoio456** [comment]
I found that I use camera2 and set the cameraExperimental to false, the camera work normally.

**Comment by JoAdams34** [comment]
How can one use Camera2 without cameraExperimental? If you look at method "instantiateCameraEngine" in "CameraView.java" it says:
if (mExperimental && engine == Engine.CAMERA2 && Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) { return new Camera2Engine(callback); } else { mEngine = Engine.CAMERA1; return new Camera1Engine(callback); }

Otherwise it always uses Camera1, so the above implies that CameraView with Camera2 is broken on the Pixel4a.
