### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 24243 (FallbackCameraT)

### ISSUE THREAD

**Issue by android-dataticket** [natario1/CameraView#987]
### Describe the bug
Please add a clear description of what the bug is, **and** fill the list below.
- CameraView version: 2.6.4
- Camera engine used: camera2
- Reproducible in official demo app: no
- Device / Android version: Samsung Galaxy S8+ / Android 9
- I have read the [FAQ page](https://natario1.github.io/CameraView/about/faq): yes

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
The demo app switches to a preview of the photo after each snap, I don't think its viable to recreate this issue.
My app allows taking the photos rapidly, the photos are processed in the background and thumbnails are added to a GridView.
Also, this camera layout is *forced landscape*, so no matter what you tilt the phone, it's always in an official landscape layout.
I *think* this happens when holding the device in portrait, snapping photos (snapshots), and then holding it in landscape and snapping more photos (snapshots, always snapshots).  Again, no matter that the device is being held in portrait or landscape, the layout is in strict landscape mode, and the snapshots are cropped accordingly.

### Expected behavior
I expect the snapshots to continue to process, but randomly the SIGSEGV fatal signal gets thrown and the activity in which this camera resides is destroyed abruptly.

### XML layout
Part of the XML layout with the CameraView declaration, so we can read its attributes.

     <com.otaliastudios.cameraview.CameraView
                android:id="@+id/camview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:padding="5dp"
                app:cameraFacing="back"
                app:cameraFlash="off"
                app:cameraGesturePinch="zoom"
                app:cameraGestureTap="autoFocus"
                app:cameraMode="picture"
                app:cameraPictureFormat="jpeg" />

### Screenshots
no screenshot

### Logs (taking snapshots back to back, changing orientation for some)
1 CameraOrchestrator/FLASH (OFF) - Scheduling.
1 CameraOrchestrator/FLASH (OFF) - Executing.
1 CameraOrchestrator/FLASH (OFF) - Finished.
1 Angles/Angles changed: sensorOffset: 0 displayOffset: 90 deviceOrientation: 0
1 CameraEngine/START: scheduled. State: OFF
1 CameraOrchestrator/OFF >> ENGINE - Scheduling.
1 CameraOrchestrator/ENGINE >> BIND - Scheduling.
1 CameraOrchestrator/OFF >> ENGINE - Executing.
1 CameraOrchestrator/BIND >> PREVIEW - Scheduling.
1 CameraEngine/collectCameraInfo Facing: BACK Internal: 0 Cameras: 2
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 0
1 CameraCallbacks/onDeviceOrientationChanged 0
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 0
2 CameraView/doInstantiateEngine: instantiating. preview: GL_SURFACE
2 CameraView/doInstantiateEngine: instantiated. preview: GlCameraPreview
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
2 CameraView/onMeasure: surface is not ready. Calling default behavior.
1 OverlayLayout/normal draw called.
1 CameraPreview/dispatchOnSurfaceAvailable: w= 1071 h= 634
1 CameraEngine/onSurfaceAvailable: Size is 1071x634
1 CameraOrchestrator/ENGINE >> BIND - Scheduling.
1 CameraOrchestrator/BIND >> PREVIEW - Scheduling.
1 CameraEngine/onStartEngine: Applying default parameters.
1 CameraEngine/onStartEngine: Ended
1 CameraOrchestrator/OFF >> ENGINE - Finished.
1 CameraOrchestrator/ENGINE >> BIND - Executing.
1 CameraCallbacks/dispatchOnCameraOpened com.otaliastudios.cameraview.engine.options.Camera1Options@f42a45b
1 CameraEngine/onStartBind: Started
1 CameraEngine/computeCaptureSize: result: 4032x3024 flip: false mode: PICTURE
1 CameraEngine/getPreviewStreamAvailableSizes: [1920x1080, 1440x1080, 1088x1088, 1280x720, 960x720, 720x720, 720x480, 640x480, 352x288, 320x240, 176x144]
1 CameraEngine/computePreviewStreamSize: targetRatio: 4:3 targetMinSize: 1071x634
1 CameraEngine/computePreviewStreamSize: result: 1440x1080 flip: false
1 CameraOrchestrator/ENGINE >> BIND - Finished.
1 CameraOrchestrator/BIND >> PREVIEW - Executing.
1 CameraEngine/onStartPreview Dispatching onCameraPreviewStreamSizeChanged.
1 CameraCallbacks/onCameraPreviewStreamSizeChanged: posting a requestLayout call. Preview stream size: 1440x1080
1 CameraPreview/setStreamSize: desiredW= 1440 desiredH= 1080
1 CameraEngine/onStartPreview Starting preview with startPreview().
1 CameraView/onMeasure: requested dimensions are (1378[UNSPECIFIED]x660[UNSPECIFIED])
1 CameraView/onMeasure: previewSize is (1440.0x1080.0)
1 CameraView/onMeasure: both are completely free. We respect that and extend to the whole preview size. (1440.0x1080.0)
1 CameraView/onMeasure: requested dimensions are (1440[EXACTLY]x1080[EXACTLY])
1 CameraView/onMeasure: previewSize is (1440.0x1080.0)
1 CameraView/onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (1440x1080)
1 CameraView/onMeasure: requested dimensions are (1089[EXACTLY]x652[EXACTLY])
1 CameraView/onMeasure: previewSize is (1440.0x1080.0)
1 CameraView/onMeasure: both are MATCH_PARENT or fixed value. We adapt. This means CROP_CENTER. (1089x652)
1 CameraEngine/onStartPreview Started preview.
1 CameraOrchestrator/BIND >> PREVIEW - Finished.
1 CameraOrchestrator/ENGINE >> BIND - Executing.
2 CameraOrchestrator/ENGINE >> BIND - State mismatch, aborting. current: PREVIEW from: ENGINE to: BIND
1 CameraOrchestrator/ENGINE >> BIND - Finished because ABORTED.
1 CameraOrchestrator/BIND >> PREVIEW - Executing.
2 CameraOrchestrator/BIND >> PREVIEW - State mismatch, aborting. current: PREVIEW from: BIND to: PREVIEW
1 CameraOrchestrator/BIND >> PREVIEW - Finished because ABORTED.
1 CameraCallbacks/onDeviceOrientationChanged 270
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 270
1 CameraCallbacks/onDeviceOrientationChanged 0
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 0
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
1 WorkerHandler/get: Creating new handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6778792265
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@336a391
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6779298414
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@6785e3d
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
1 CameraCallbacks/onDeviceOrientationChanged 270
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 270
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6780192284
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@df13f73
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6781091110
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@f643019
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6781860261
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@39ff1af
1 CameraCallbacks/onDeviceOrientationChanged 0
1 Angles/Angles changed: sensorOffset: 90 displayOffset: 90 deviceOrientation: 0
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6782590259
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@d6b41b5
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6783156829
1 CameraCallbacks/dispatchOnPictureTaken com.otaliastudios.cameraview.PictureResult$Stub@98c5a84
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: false
1 CameraEngine/onTakePictureSnapshot: executing.
1 CameraEngine/onTakePictureSnapshot: executed.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
2 WorkerHandler/get: Reusing cached worker handler. FallbackCameraThread
1 SnapshotPictureRecorder/takeFrame: timestampUs: 6783693994
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Scheduling.
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Executing.
1 CameraEngine/takePictureSnapshot: running. isTakingPicture: true
1 CameraOrchestrator/TAKE PICTURE SNAPSHOT - Finished.
*** CRASH HERE ***
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 24243 (FallbackCameraT)
*** CRASH HERE ***

### APK
My apologies, our application is private :( I'll provide what I can upon request.

**Comment by android-dataticket** [comment]
As probably already known, this error is not thrown when using the TextureView preview instead of OpenGL preview.

**Comment by BubbleTrouble14** [comment]
I also seem to be getting this issue randomly. Doing live face recognition and drawing a rectangle around the face. I get the crash after navigating back from the fragment, but at random. Haven't been able to figure out why or when it occurs. Tried using TextureView, but that seemed to cause different issues.

**Comment by devsontx** [comment]
Maybe my case is famillar with @BubbleTrouble14 's
It happened with both camera engine 1 and 2, CameraView 2.6.4, Picture mode.

It's observed on few models e.g Samsung J730G (Android 9) and Nokia 2.1 (Android 10) that working with tensorflow (any version) will cause crash after reporting `A/libc: Fatal signal 11 (SIGSEGV), code 1 ` 
No action like take snapshoot was needed to reproduce the error.

Susspected Tensorflow at first but then when I replace it by another CameraView library to produce frames, the error will disapear.

**Comment by BubbleTrouble14** [comment]
I was actually able to fix it, was caused due to the face recognition library i was using. And also ended up not constantly drawing a rectangle around the face the whole time.

**Comment by devsontx** [comment]
@BubbleTrouble14 may i ask what was the face recognition library. What is the root cause of your problem?

**Comment by BubbleTrouble14** [comment]
Luxand Facerecogniton, yes I am about 80 percent sure. I was setting the size of an array of facetemplates incorrect which would cause memory leaks inside the library an cause a crash.

**Comment by isabsent** [comment]
I catch this bug each time I trying to use Database Inspector in Android Studio under debug. It doesn't depend with CameraView usage. When I don't use Database Inspector this bug doesn't appear.

**Comment by CalderonRigoberto** [comment]
@BubbleTrouble14 where you modify your settings? I'm strugglin with the same problem.

**Comment by longpq-vmo** [comment]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffff00000066 in tid 26770
me too, pls help me check issue when back fragment

**Comment by longquangpham90** [comment]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffff00000066 in tid 26770 
me too, pls help me check issue when back fragment

**Comment by longpq-vmo** [comment]
Thanks all
I think issue by result bitmap screen 
Don't should use bitmap, we will save file data

**Comment by longquangpham90** [comment]
Thanks all
I think issue by result bitmap screen
Don't should use bitmap, we will save file data
