### ISSUE TITLE
takePictureSnapshot - Flash not working

### ISSUE THREAD

**Issue by abhilash007** [natario1/CameraView#988]
- CameraView version: 2.6.4
- Camera engine used: both
- Device / Android version: Redmi 5 Pro

Flash not working on takePictureSnapshot()

**Comment by android-dataticket** [comment]
It's a snapshot of the preview, you'd have to use the torch mode for flash

**Comment by NaveenPokhriyal** [comment]
Auto Flash not working while clicking snapshot.

**Comment by android-dataticket** [comment]
> Auto Flash not working while clicking snapshot.

you can't expect the snapshot to trigger flash.  snapshot is designed to be fast, quick, snappy.

if you want flash while using snapshot, you will need to use flash in torch mode, and toggle it manually on and off accordingly.

**Comment by NaveenPokhriyal** [comment]
Is there any way to make autoflash run like while we set the focus for dim light surface?

**Comment by android-dataticket** [comment]
> Is there any way to make autoflash run like while we set the focus for dim light surface?

You're defeating the purpose of the snapshot (speed) by making the flash toggle on and off automatically (it's much better, for the focus of the object being photographed, to have the flash toggled already with TORCH before using snapshot to take a photo), however if you were to do it, you could programmatically:

cameraView.setFlash(Flash.TORCH);
//maybe wait 200ms to ensure the flash has illuminated and the display preview has focused better on the illuminated object??
//Thread.sleep(200);
cameraView.takePictureSnapshot();
cameraView.setFlash(Flash.OFF);

**Comment by NaveenPokhriyal** [comment]
Yes, I have achieved that flash functionality.
But can you help me with the auto flash issue. 
it didn't work when i set CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH for  -mOrignalaeMode.

**Comment by NaveenPokhriyal** [comment]
I'm using the torch as Flash and later on setting that off and I also change action sequence for ( Actions.timeout(LOCK_TIMEOUT, new LockAction()), new FlashAction());) it handles flash on the exact surface.
