### ISSUE TITLE
Front camera focus not avaliable

### ISSUE THREAD

**Issue by Jack-SunQi** [natario1/CameraView#995]
when i call cameraOptions?.isAutoFocusSupported, the result is always false, while the system camera support front camera focus!

tested on huawei, oppo, xiaomi

version: 2.6.4

**Comment by kyygit** [comment]
what, this is important. can this be reopened?

**Comment by ankitbatra11** [comment]
I am also looking up to this functionality. @yong2khoo-lm Were you able to achieve this?
